import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { Language } from '../types';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const INDIC_TO_ARABIC_DIGITS_MAP: Record<string, string> = {
  // Devanagari (Hindi, Marathi)
  '०': '0', '१': '1', '२': '2', '३': '3', '४': '4', '५': '5', '६': '6', '७': '7', '८': '8', '९': '9',
  // Bengali, Assamese
  '০': '0', '১': '1', '২': '2', '৩': '3', '৪': '4', '৫': '5', '৬': '6', '৭': '7', '৮': '8', '৯': '9',
  // Gurmukhi (Punjabi)
  '੦': '0', '੧': '1', '੨': '2', '੩': '3', '੪': '4', '੫': '5', '੬': '6', '੭': '7', '੮': '8', '੯': '9',
  // Gujarati
  '૦': '0', '૧': '1', '૨': '2', '૩': '3', '૪': '4', '૫': '5', '૬': '6', '૭': '7', '૮': '8', '૯': '9',
  // Odia
  '୦': '0', '୧': '1', '୨': '2', '୩': '3', '୪': '4', '୫': '5', '୬': '6', '୭': '7', '୮': '8', '୯': '9',
  // Tamil
  '௦': '0', '௧': '1', '௨': '2', '௩': '3', '௪': '4', '௫': '5', '௬': '6', '௭': '7', '௮': '8', '௯': '9',
  // Telugu
  '౦': '0', '౧': '1', '౨': '2', '౩': '3', '౪': '4', '౵': '5', '౬': '6', '౭': '7', '౮': '8', '౯': '9',
  // Kannada
  '೦': '0', '೧': '1', '೨': '2', '೩': '3', '೪': '4', '೫': '5', '೬': '6', '೭': '7', '೮': '8', '೯': '9',
  // Malayalam
  '൦': '0', '൧': '1', '൨': '2', '൩': '3', '൪': '4', '൫': '5', '൬': '6', '൭': '7', '൮': '8', '൯': '9',
  // Arabic / Urdu
  '۰': '0', '۱': '1', '۲': '2', '۳': '3', '۴': '4', '۵': '5', '۶': '6', '۷': '7', '۸': '8', '۹': '9',
  '٠': '0', '١': '1', '٢': '2', '٣': '3', '٤': '4', '٥': '5', '٦': '6', '٧': '7', '٨': '8', '٩': '9',
};

/**
 * Safely parses any value (number, localized Indic numerals, string with currency, undefined)
 * into a pure JavaScript native number (English standard digits).
 * Always falls back to 0 instead of NaN.
 */
export function parseNumericValue(value: unknown): number {
  if (typeof value === 'number') {
    return isNaN(value) || !isFinite(value) ? 0 : value;
  }
  if (value === null || value === undefined || value === '') {
    return 0;
  }
  // Normalize localized Indic/Perso-Arabic numeral characters to standard ASCII digits
  let str = String(value).replace(
    /[०-९০-৯੦-੯૦-૯୦-୯௦-௯౦-౯೦-೯൦-൯۰-۹٠-٩]/g,
    (d) => INDIC_TO_ARABIC_DIGITS_MAP[d] || d
  );
  // Strip out any non-numeric characters except minus and period
  const cleaned = str.replace(/[^0-9.-]+/g, '');
  const parsed = parseFloat(cleaned);
  return isNaN(parsed) || !isFinite(parsed) ? 0 : parsed;
}

/**
 * Price & Currency Display:
 * Keeps numeric values displayed using standard Arabic digits (0-9) and prefixed with the Indian Rupee symbol `₹`:
 * Format: `₹${Number(val).toLocaleString('en-IN')}`
 * Ensure fallback handling: if any result is isNaN(result), show `₹0` instead of `₹NaN`.
 */
export function formatINR(amount: unknown): string {
  const num = parseNumericValue(amount);
  if (isNaN(num) || !isFinite(num)) {
    return '₹0';
  }
  const isNegative = num < 0;
  const absVal = Math.abs(Math.round(num));
  const formatted = absVal.toLocaleString('en-IN', { maximumFractionDigits: 0 });
  return isNegative ? `-₹${formatted}` : `₹${formatted}`;
}

export interface TranslationStrings {
  appName: string;
  tagline: string;
  audioMode: string;
  audioPlaying: string;
  stopAudio: string;
  sunlightMode: string;
  selectCrop: string;
  selectCropSubtitle: string;
  voiceSearchPrompt: string;
  voiceSearchActive: string;
  decisionSignal: string;
  highestPriceToday: string;
  perQuintal: string;
  sellTodayVerdict: string;
  waitVerdict: string;
  riskVerdict: string;
  netProfitTitle: string;
  netProfitSubtitle: string;
  yourHarvestQuantity: string;
  chooseVehicle: string;
  dieselTransportCost: string;
  grossSale: string;
  actualNetCash: string;
  bestProfitBadge: string;
  extraCash: string;
  offlineBannerTitle: string;
  sendSmsBtn: string;
  playAudioBtn: string;
  missedCallTitle: string;
  missedCallNumber: string;
  missedCallDesc: string;
  distance: string;
  buyersToday: string;
  paymentInstant: string;
  sevenDayTrend: string;
  today: string;
  keyFactors: string;
  weatherNotice: string;
  locationLabel: string;
  changeLocation: string;
  detectLocation: string;
  detectedNotice: string;
  searchPlaceholder: string;
  allCrops: string;
  categoryCereals: string;
  categoryPulses: string;
  categoryOilseeds: string;
  categorySpices: string;
  categoryVegetables: string;
  categoryCashCrops: string;
  categoryFruits: string;
  // CropSelector & Filter badges
  sellBadge: string;
  waitBadge: string;
  riskBadge: string;
  selectedBadge: string;
  selectCropBtn: string;
  resetFilters: string;
  filterOptions: string;
  cropSelectedBanner: string;
  noCropsFound: string;
  tryDifferentSearch: string;
  allSignals: string;

  // Navigation workflow buttons
  proceedToDecision: string;
  backToCrops: string;
  proceedToProfit: string;
  backToDecision: string;
  proceedToWeather: string;
  backToProfit: string;
  proceedToHelp: string;
  checkAnotherCrop: string;

  // Floating Actions & Pooling
  voiceSearchBtn: string;
  connectWithFarmersBtn: string;
  poolTruckSubtitle: string;
  poolTruckloadBtn: string;
  farmersPooledStatus: string;
  smallYieldBadge: string;
  smallYieldAlert: string;

  // Decision & Metrics
  arrivalsLabel: string;
  volumeTrendLabel: string;
  sameStateMandiBanner: string;
  kmAway: string;
  transitCautionLabel: string;
  safeHoldingLabel: string;
  recommendedStorageLabel: string;
  quintalsUnit: string;
  kgUnit: string;

  // Profit & Logistics
  costOfCultivationLabel: string;
  calculateIndividualProfit: string;
  calculatePooledProfit: string;
  editPoolBtn: string;
  bulkPoolingSavings: string;
  roundTrip: string;
  activeTradersLabel: string;
  licensedTraders: string;
  paymentLabel: string;

  // Weather & Storage
  scientificStorageTitle: string;
  scientificStorageSubtitle: string;
  hideGuidelines: string;
  viewGuidelines: string;
  safeDurationLabel: string;
  moistureStandardLabel: string;
  keyDirectivesLabel: string;

  // Helpline & Offline
  lowInternetBadge: string;
  shareWithKisanGroup: string;
  smsPrefilledNotice: string;
  kisanCallCenterTitle: string;
  kisanCallCenterDesc: string;
  callFreeBtn: string;
  outdoorSunlightTitle: string;
  sunlightModeDesc: string;
  turnSunlightOn: string;
  turnSunlightOff: string;

  // Modals & Header Extras
  languagesCountTitle: string;
  changeZoneBtn: string;
  zoneLabel: string;
  cloudSyncTitle: string;
  signInBtn: string;
  onlineStatus: string;
  pinCrop: string;
  pinnedCrop: string;
  changeCropAction: string;
}

export const translations: Record<Language, TranslationStrings> = {
  en: {
    appName: 'MandiMitra',
    tagline: 'All-India Smart Crop Decision & Net Profit System',
    audioMode: 'Listen to Advice',
    audioPlaying: 'Reading Advice...',
    stopAudio: 'Stop Audio',
    sunlightMode: 'Sunlight Mode',
    selectCrop: 'Select Your Crop',
    selectCropSubtitle: 'Tap your crop to view today’s mandi rates & smart decision',
    voiceSearchPrompt: 'Tap mic & speak any crop name in your language',
    voiceSearchActive: 'Listening... Speak your crop name',
    decisionSignal: 'Decision Signal',
    highestPriceToday: 'Highest Mandi Price Today',
    perQuintal: 'per quintal (100 kg)',
    sellTodayVerdict: 'Sell Today - Mandi Prices are Peaking',
    waitVerdict: 'Wait 2–3 Days - Expected Rate Increase',
    riskVerdict: 'Sell Immediately - High Weather/Spoilage Risk',
    netProfitTitle: 'Net In-Hand Profit Calculator',
    netProfitSubtitle: 'Don’t just look at mandi rate! Compare real take-home cash after diesel/transport costs.',
    yourHarvestQuantity: 'Your Crop Quantity (Quintals)',
    chooseVehicle: 'Choose Transport Vehicle',
    dieselTransportCost: 'Est. Fuel / Transport Cost',
    grossSale: 'Gross Mandi Sale',
    actualNetCash: 'Actual Net Cash In-Hand',
    bestProfitBadge: 'Best Profit Choice',
    extraCash: 'Extra Cash In-Hand',
    offlineBannerTitle: 'Low Internet or Feature Phone?',
    sendSmsBtn: 'Send Rates to My Phone via SMS',
    playAudioBtn: 'Play Voice Advisory',
    missedCallTitle: 'Free Toll-Free Missed Call',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'Give a missed call from any keypad phone to hear current rates in your regional language',
    distance: 'Distance',
    buyersToday: 'Active Traders',
    paymentInstant: 'Payment',
    sevenDayTrend: '7-Day Price Trend & Forecast',
    today: 'Today',
    keyFactors: 'Why this decision?',
    weatherNotice: 'Weather Alert',
    locationLabel: 'State Location',
    changeLocation: 'Change Location',
    detectLocation: 'Detect via GPS',
    detectedNotice: 'Location detected: Switched language & regional mandis',
    searchPlaceholder: 'Search all crops across India (Wheat, Cotton, Soybean, Onion, Tur)...',
    allCrops: 'All Crops',
    categoryCereals: 'Cereals & Millets',
    categoryPulses: 'Pulses (Dal)',
    categoryOilseeds: 'Oilseeds',
    categorySpices: 'Spices',
    categoryVegetables: 'Vegetables',
    categoryCashCrops: 'Cash Crops',
    categoryFruits: 'Fruits & Plantation',
    sellBadge: 'Sell Today',
    waitBadge: 'Wait',
    riskBadge: 'Risk / Sell Now',
    selectedBadge: 'Selected',
    selectCropBtn: 'Select',
    resetFilters: 'Reset Filters',
    filterOptions: 'Options',
    cropSelectedBanner: 'Selected Crop',
    noCropsFound: 'No crops found matching your filters',
    tryDifferentSearch: 'Try searching a different name or clear category filter',
    allSignals: 'All',
    proceedToDecision: '2. Today\'s Decision ➡️',
    backToCrops: '⬅️ 1. Choose Crop',
    proceedToProfit: '3. Mandi Net Cash ➡️',
    backToDecision: '⬅️ 2. Today\'s Decision',
    proceedToWeather: '4. Weather & Storage ➡️',
    backToProfit: '⬅️ 3. Mandi Net Cash',
    proceedToHelp: '5. Kisan Help ➡️',
    checkAnotherCrop: '1. Check Another Crop',
    voiceSearchBtn: 'Voice Search',
    connectWithFarmersBtn: 'Connect with Farmers',
    poolTruckSubtitle: 'Pool truckload within 10 km',
    poolTruckloadBtn: 'Pool Truckload',
    farmersPooledStatus: 'nearby farmers pooled • Shared Truck',
    smallYieldBadge: '< 15 Qtl',
    smallYieldAlert: 'Small harvest (< 15 Qtl): Solo truck freight may take 25-35% of profit. Pool a truck with nearby farmers to save ₹80-120/qtl!',
    arrivalsLabel: 'Arrivals',
    volumeTrendLabel: 'Volume Trend',
    sameStateMandiBanner: '≤ 100 KM MANDIS',
    kmAway: 'km away',
    transitCautionLabel: 'Mandi Transit Caution',
    safeHoldingLabel: 'Safe Holding Window',
    recommendedStorageLabel: 'Recommended Storage',
    quintalsUnit: 'Quintals',
    kgUnit: 'kg',
    costOfCultivationLabel: 'Cost of Cultivation (₹/Qtl)',
    calculateIndividualProfit: 'Calculate Individual Profit',
    calculatePooledProfit: 'Calculate Pooled Group Profit',
    editPoolBtn: 'Edit Pool',
    bulkPoolingSavings: 'Bulk Pooling Savings',
    roundTrip: 'round trip',
    activeTradersLabel: 'Active Traders',
    licensedTraders: 'licensed',
    paymentLabel: 'Payment',
    scientificStorageTitle: 'Scientific Storage Reference Guidelines',
    scientificStorageSubtitle: 'Safe holding duration, moisture standards & warehouse transit details',
    hideGuidelines: 'Hide',
    viewGuidelines: 'View Guidelines',
    safeDurationLabel: 'Safe Duration',
    moistureStandardLabel: 'Moisture Standard',
    keyDirectivesLabel: 'Key Directives',
    lowInternetBadge: 'Low Internet & Keypad Phone Accessibility',
    shareWithKisanGroup: 'Share with Kisan Group',
    smsPrefilledNotice: '✓ Opened SMS app. Rates and advisory pre-filled for sending!',
    kisanCallCenterTitle: 'Kisan Call Center',
    kisanCallCenterDesc: 'Connect with agricultural scientists in 22 regional languages. Open 6:00 AM – 10:00 PM daily.',
    callFreeBtn: 'Call 1800-180-1551 (Toll-Free)',
    outdoorSunlightTitle: 'Outdoor Sunlight Mode',
    sunlightModeDesc: 'Increases text contrast and black borders for easy reading under direct farm sunlight.',
    turnSunlightOn: 'Turn Sunlight Mode ON',
    turnSunlightOff: 'High Contrast ON',
    languagesCountTitle: '13 Indian Languages',
    changeZoneBtn: 'Change',
    zoneLabel: 'Zone',
    cloudSyncTitle: 'Kisan Cloud Sync',
    signInBtn: 'Sign In',
    onlineStatus: 'Online',
    pinCrop: 'Pin Crop',
    pinnedCrop: 'Pinned',
    changeCropAction: 'Change Crop',
  },
  hi: {
    appName: 'मंडी मित्र',
    tagline: 'अखिल भारतीय किसान मंडी भाव और असली मुनाफा प्रणाली',
    audioMode: 'सलाह सुनें',
    audioPlaying: 'सलाह पढ़ी जा रही है...',
    stopAudio: 'आवाज रोकें',
    sunlightMode: 'धूप मोड',
    selectCrop: 'अपनी फसल चुनें',
    selectCropSubtitle: 'आज के मंडी भाव और सही फैसला जानने के लिए फसल पर टैप करें',
    voiceSearchPrompt: 'माइक दबाकर किसी भी फसल का नाम बोलें (जैसे "गेहूं", "चना", "प्याज")',
    voiceSearchActive: 'सुन रहे हैं... फसल का नाम बोलें',
    decisionSignal: 'फैसला संकेत (Decision Signal)',
    highestPriceToday: 'आज का सबसे ऊंचा मंडी भाव',
    perQuintal: 'प्रति क्विंटल (100 किलो)',
    sellTodayVerdict: 'आज ही बेचें - मंडी भाव उच्चतम स्तर पर हैं',
    waitVerdict: '2–3 दिन रुकें - भाव और बढ़ने की उम्मीद है',
    riskVerdict: 'तुरंत बेचें - मौसम खराबी या सड़ने का खतरा',
    netProfitTitle: 'हाथ में आने वाला असली मुनाफा (Net Profit)',
    netProfitSubtitle: 'सिर्फ मंडी भाव मत देखें! डीजल और भाड़ा घटाकर हाथ में बचने वाले असली पैसे देखें।',
    yourHarvestQuantity: 'फसल की कुल मात्रा (क्विंटल)',
    chooseVehicle: 'परिवहन वाहन चुनें',
    dieselTransportCost: 'अनुमानित डीजल / भाड़ा खर्च',
    grossSale: 'कुल मंडी बिक्री',
    actualNetCash: 'हाथ में शुद्ध नकद (Net Cash)',
    bestProfitBadge: 'सबसे ज्यादा फायदे का सौदा',
    extraCash: 'अतिरिक्त नकद बचत',
    offlineBannerTitle: 'धीमा इंटरनेट या सादा कीपैड फोन?',
    sendSmsBtn: 'एसएमएस (SMS) से अपने फोन पर भाव मंगाएं',
    playAudioBtn: 'ऑडियो सलाह हिंदी में सुनें',
    missedCallTitle: 'मुफ्त मिस्ड कॉल सेवा',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'किसी भी फोन से मिस्ड कॉल दें और तुरंत अपनी भाषा में बोलकर भाव सुनें',
    distance: 'दूरी',
    buyersToday: 'सक्रिय व्यापारी',
    paymentInstant: 'भुगतान',
    sevenDayTrend: '7-दिन का भाव ग्राफ और पूर्वानुमान',
    today: 'आज',
    keyFactors: 'यह फैसला क्यों?',
    weatherNotice: 'मौसम चेतावनी',
    locationLabel: 'राज्य / स्थान',
    changeLocation: 'राज्य बदलें',
    detectLocation: 'GPS से खोजें',
    detectedNotice: 'लोकेशन के अनुसार भाषा और मंडी सूची अपडेट की गई',
    searchPlaceholder: 'भारत की किसी भी फसल को खोजें (गेहूं, धान, चना, कपास, प्याज)...',
    allCrops: 'सभी फसलें',
    categoryCereals: 'अनाज और मिलेट्स',
    categoryPulses: 'दलहन (दालें)',
    categoryOilseeds: 'तिलहन',
    categorySpices: 'मसाले',
    categoryVegetables: 'सब्जियां',
    categoryCashCrops: 'नकदी फसलें',
    categoryFruits: 'फल व बागवानी',
    sellBadge: 'आज बेचें',
    waitBadge: 'रुकें',
    riskBadge: 'जोखिम / तुरंत बेचें',
    selectedBadge: 'चुना हुआ',
    selectCropBtn: 'चुनें',
    resetFilters: 'फ़िल्टर हटाएं',
    filterOptions: 'विकल्प',
    cropSelectedBanner: 'चुनी गई फसल',
    noCropsFound: 'कोई फसल नहीं मिली',
    tryDifferentSearch: 'कृपया दूसरा नाम खोजें या फ़िल्टर साफ़ करें',
    allSignals: 'सभी',
    proceedToDecision: '2. आज का निर्णय ➡️',
    backToCrops: '⬅️ 1. फसल बदलें',
    proceedToProfit: '3. मंडी मुनाफा जांचें ➡️',
    backToDecision: '⬅️ 2. आज का निर्णय',
    proceedToWeather: '4. मौसम व भंडारण ➡️',
    backToProfit: '⬅️ 3. मंडी मुनाफा',
    proceedToHelp: '5. किसान सहायता ➡️',
    checkAnotherCrop: '1. दूसरी फसल चुनें',
    voiceSearchBtn: 'बोल कर खोजें',
    connectWithFarmersBtn: 'साथी किसान जोड़ें',
    poolTruckSubtitle: '10 किमी के दायरे में गाड़ी साझा करें',
    poolTruckloadBtn: 'गाड़ी साझा करें (पूल)',
    farmersPooledStatus: 'किसान जुड़े • साझा गाड़ी',
    smallYieldBadge: '< 15 क्विंटल',
    smallYieldAlert: 'कम उपज (< 15 क्विंटल): अकेले गाड़ी करने पर 25-35% भाड़ा कट जाएगा। आसपास के किसानों के साथ गाड़ी साझा कर ₹80-120/क्विंटल बचाएं!',
    arrivalsLabel: 'आवक',
    volumeTrendLabel: 'आवक रुझान',
    sameStateMandiBanner: '≤ 100 किमी नजदीकी मंडियां',
    kmAway: 'किमी दूर',
    transitCautionLabel: 'मंडी ढुलाई सावधानी',
    safeHoldingLabel: 'सुरक्षित भंडारण अवधि',
    recommendedStorageLabel: 'अनुशंसित भंडारण',
    quintalsUnit: 'क्विंटल',
    kgUnit: 'किग्रा',
    costOfCultivationLabel: 'लागत खर्च (₹/क्विंटल)',
    calculateIndividualProfit: 'व्यक्तिगत मुनाफा देखें',
    calculatePooledProfit: 'सामूहिक गाड़ी मुनाफा देखें',
    editPoolBtn: 'पूल बदलें',
    bulkPoolingSavings: 'सामूहिक गाड़ी बचत',
    roundTrip: 'आना-जाना',
    activeTradersLabel: 'सक्रिय व्यापारी',
    licensedTraders: 'लाइसेंस प्राप्त',
    paymentLabel: 'भुगतान',
    scientificStorageTitle: 'वैज्ञानिक भंडारण दिशा-निर्देश',
    scientificStorageSubtitle: 'सुरक्षित भंडारण समय, नमी मानक और मंडी ढुलाई सुरक्षा',
    hideGuidelines: 'छिपाएं',
    viewGuidelines: 'दिशा-निर्देश देखें',
    safeDurationLabel: 'सुरक्षित अवधि',
    moistureStandardLabel: 'नमी मानक',
    keyDirectivesLabel: 'मुख्य निर्देश',
    lowInternetBadge: 'धीमा इंटरनेट व कीपैड फोन सुविधा',
    shareWithKisanGroup: 'किसान समूह में साझा करें',
    smsPrefilledNotice: '✓ एसएमएस खुल गया। मंडी भाव और सलाह तैयार है!',
    kisanCallCenterTitle: 'किसान कॉल सेंटर',
    kisanCallCenterDesc: 'कृषि वैज्ञानिकों से 22 भाषाओं में सीधी बात करें। प्रतिदिन सुबह 6 से रात 10 बजे तक।',
    callFreeBtn: 'कॉल करें 1800-180-1551 (मुफ्त कॉल)',
    outdoorSunlightTitle: 'तेज धूप मोड',
    sunlightModeDesc: 'खेत में तेज धूप में पढ़ने के लिए गहरा कंट्रास्ट और स्पष्ट अक्षर।',
    turnSunlightOn: 'धूप मोड चालू करें',
    turnSunlightOff: 'धूप मोड चालू है',
    languagesCountTitle: '13 भारतीय भाषाएं',
    changeZoneBtn: 'बदलें',
    zoneLabel: 'क्षेत्र',
    cloudSyncTitle: 'किसान क्लाउड सिंक',
    signInBtn: 'साइन इन',
    onlineStatus: 'ऑनलाइन',
    pinCrop: 'पिन करें',
    pinnedCrop: 'पिन किया गया',
    changeCropAction: 'फसल बदलें',
  },
  mr: {
    appName: 'मंडी मित्र',
    tagline: 'शेतकऱ्यांसाठी स्मार्ट बाजारभाव व प्रत्यक्ष निव्वळ नफा सल्ला',
    audioMode: 'सल्ला ऐका',
    audioPlaying: 'सल्ला वाचत आहे...',
    stopAudio: 'आवाज बंद करा',
    sunlightMode: 'उजेड मोड',
    selectCrop: 'आपले पीक निवडा',
    selectCropSubtitle: 'आजचा बाजारभाव आणि योग्य निर्णय पाहण्यासाठी पिकावर टॅप करा',
    voiceSearchPrompt: 'माईक दाबून पिकाचे नाव सांगा (उदा. "कांदा", "सोयाबीन", "कापूस")',
    voiceSearchActive: 'ऐकत आहे... पिकाचे नाव सांगा',
    decisionSignal: 'निर्णय संकेत (Decision Signal)',
    highestPriceToday: 'आजचा सर्वोच्च बाजारभाव',
    perQuintal: 'प्रति क्विंटल (100 किलो)',
    sellTodayVerdict: 'आजच विका - बाजारभाव उच्चांकी पातळीवर आहेत',
    waitVerdict: '२–३ दिवस थांबा - भाव वाढण्याची शक्यता आहे',
    riskVerdict: 'त्वरित विका - पाऊस आणि नासाडीचा धोका',
    netProfitTitle: 'हातात उरणारा खरा निव्वळ नफा',
    netProfitSubtitle: 'फक्त बाजाराचा दर पाहू नका! डिझेल आणि वाहतूक खर्च वजा करून खिशात काय उरेल ते तपासा.',
    yourHarvestQuantity: 'पिकाचे प्रमाण (क्विंटल)',
    chooseVehicle: 'वाहतुकीचे वाहन निवडा',
    dieselTransportCost: 'अंदाजे डिझेल / वाहतूक खर्च',
    grossSale: 'एकूण बाजार विक्री',
    actualNetCash: 'हातात प्रत्यक्ष रोकड (Net Cash)',
    bestProfitBadge: 'सर्वाधिक नफ्याचा पर्याय',
    extraCash: 'जास्तीचा नफा',
    offlineBannerTitle: 'कमी इंटरनेट किंवा साधा कीपॅड फोन?',
    sendSmsBtn: 'SMS द्वारे माझ्या फोनवर दर मागवा',
    playAudioBtn: 'ऑडिओ सल्ला मराठीत ऐका',
    missedCallTitle: 'मोफत मिस्ड कॉल सेवा',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'कोणत्याही फोनवरून मिस्ड कॉल द्या आणि मोफत ऑडिओ रिपोर्ट मिळवा',
    distance: 'अंतर',
    buyersToday: 'खरेदीदार व्यापारी',
    paymentInstant: 'पैसे भरणा',
    sevenDayTrend: '७-दिवसीय भाव कल आणि अंदाज',
    today: 'आज',
    keyFactors: 'हा सल्ला का दिला?',
    weatherNotice: 'हवामान इशारा',
    locationLabel: 'स्थान / राज्य',
    changeLocation: 'राज्य बदला',
    detectLocation: 'GPS द्वारे शोधा',
    detectedNotice: 'तुमच्या स्थानानुसार भाषा आणि स्थानिक बाजारपेठा निवडल्या आहेत',
    searchPlaceholder: 'कोणतेही पीक शोधा (कांदा, सोयाबीन, कापूस, तूर, गहू)...',
    allCrops: 'सर्व पिके',
    categoryCereals: 'धान्य आणि तृणधान्य',
    categoryPulses: 'कडधान्ये (डाळी)',
    categoryOilseeds: 'गळीत धान्ये (तेलबिया)',
    categorySpices: 'मसाले पिके',
    categoryVegetables: 'भाजीपाला',
    categoryCashCrops: 'नगदी पिके',
    categoryFruits: 'फळे व बागायती',
    sellBadge: 'आजच विका',
    waitBadge: 'थांबा',
    riskBadge: 'धोका / त्वरित विका',
    selectedBadge: 'निवडलेले',
    selectCropBtn: 'निवडा',
    resetFilters: 'फिल्टर रीसेट',
    filterOptions: 'पर्याय',
    cropSelectedBanner: 'निवडलेले पीक',
    noCropsFound: 'कोणतेही पीक आढळले नाही',
    tryDifferentSearch: 'दुसरे नाव शोधा किंवा फिल्टर साफ करा',
    allSignals: 'सर्व',
    proceedToDecision: '2. आजचा विक्री निर्णय ➡️',
    backToCrops: '⬅️ 1. पीक बदला',
    proceedToProfit: '3. निव्वळ नफा हिशोब ➡️',
    backToDecision: '⬅️ 2. आजचा निर्णय',
    proceedToWeather: '4. हवामान व साठवणूक ➡️',
    backToProfit: '⬅️ 3. निव्वळ नफा',
    proceedToHelp: '5. शेतकरी मदत ➡️',
    checkAnotherCrop: '1. दुसरे पीक तपासा',
    voiceSearchBtn: 'बोलून शोधा',
    connectWithFarmersBtn: 'शेतकरी एकत्र करा',
    poolTruckSubtitle: '१० किमी परिसरात एकत्र वाहन करा',
    poolTruckloadBtn: 'एकत्र गाडी करा (पूल)',
    farmersPooledStatus: 'शेतकरी जोडले • सामायिक वाहन',
    smallYieldBadge: '< १५ क्विंटल',
    smallYieldAlert: 'कमी उत्पन्न (< १५ क्विंटल): एकट्याने गाडी केल्यास २५-३५% नफा भाड्यात जाईल. परिसरातील शेतकऱ्यांसोबत वाहन एकत्र करून ₹८०-१२०/क्विंटल वाचवा!',
    arrivalsLabel: 'आवक',
    volumeTrendLabel: 'आवक कल',
    sameStateMandiBanner: '≤ १०० किमी स्थानिक बाजारपेठा',
    kmAway: 'किमी अंतर',
    transitCautionLabel: 'बाजार वाहतूक दक्षता',
    safeHoldingLabel: 'सुरक्षित साठवणूक कालावधी',
    recommendedStorageLabel: 'शिफारस केलेली साठवणूक',
    quintalsUnit: 'क्विंटल',
    kgUnit: 'किलो',
    costOfCultivationLabel: 'उत्पादन खर्च (₹/क्विंटल)',
    calculateIndividualProfit: 'वैयक्तिक नफा तपासा',
    calculatePooledProfit: 'एकत्रित वाहनाचा सामूहिक नफा',
    editPoolBtn: 'पूल बदला',
    bulkPoolingSavings: 'एकत्रित वाहन बचत',
    roundTrip: 'येणे-जाणे',
    activeTradersLabel: 'सक्रिय व्यापारी',
    licensedTraders: 'परवानाधारक',
    paymentLabel: 'पेमेंट',
    scientificStorageTitle: 'वैज्ञानिक साठवणूक मार्गदर्शक तत्त्वे',
    scientificStorageSubtitle: 'सुरक्षित साठवण कालावधी, ओलावा मानके व वाहतूक दक्षता',
    hideGuidelines: 'लपवा',
    viewGuidelines: 'मार्गदर्शक तत्त्वे पहा',
    safeDurationLabel: 'सुरक्षित कालावधी',
    moistureStandardLabel: 'ओलावा मानक',
    keyDirectivesLabel: 'महत्त्वाचे निर्देश',
    lowInternetBadge: 'कमी इंटरनेट व साधा फोन सुविधा',
    shareWithKisanGroup: 'शेतकरी ग्रुपवर पाठवा',
    smsPrefilledNotice: '✓ एसएमएस ॲप उघडले. बाजारभाव आणि सल्ला तयार आहे!',
    kisanCallCenterTitle: 'किसान कॉल सेंटर',
    kisanCallCenterDesc: 'कृषी शास्त्रज्ञांशी थेट बोला. दररोज सकाळी ६ ते रात्री १० पर्यंत मोफत सेवा.',
    callFreeBtn: 'कॉल करा 1800-180-1551 (मोफत कॉल)',
    outdoorSunlightTitle: 'प्रखर ऊन मोड',
    sunlightModeDesc: 'शेतात उन्हात वाचण्यासाठी स्पष्ट अक्षरे आणि गडद रंग.',
    turnSunlightOn: 'ऊन मोड सुरू करा',
    turnSunlightOff: 'ऊन मोड सुरू आहे',
    languagesCountTitle: '१३ भारतीय भाषा',
    changeZoneBtn: 'बदला',
    zoneLabel: 'विभाग',
    cloudSyncTitle: 'शेतकरी क्लाउड सिंक',
    signInBtn: 'साइन इन',
    onlineStatus: 'ऑनलाइन',
    pinCrop: 'पिन करा',
    pinnedCrop: 'पिन केले',
    changeCropAction: 'पीक बदला',
  },
  gu: {
    appName: 'મંડી મિત્ર',
    tagline: 'ખેડૂતો માટે સ્માર્ટ પાક ભાવ અને ચોખ્ખો નફો',
    audioMode: 'સલાહ સાંભળો',
    audioPlaying: 'સલાહ સંભળાઈ રહી છે...',
    stopAudio: 'અવાજ બંધ કરો',
    sunlightMode: 'તડકો મોડ',
    selectCrop: 'તમારો પાક પસંદ કરો',
    selectCropSubtitle: 'આજના માર્કેટ યાર્ડ ભાવ અને સ્માર્ટ નિર્ણય જોવા માટે પાક પર ટેપ કરો',
    voiceSearchPrompt: 'માઇક દબાવી પાકનું નામ બોલો (દા.ત. "જીરું", "કપાસ", "મગફળી")',
    voiceSearchActive: 'સાંભળી રહ્યા છીએ... પાકનું નામ બોલો',
    decisionSignal: 'નિર્ણય સંકેત (Decision Signal)',
    highestPriceToday: 'આજનો સૌથી ઊંચો યાર્ડ ભાવ',
    perQuintal: 'પ્રતિ ક્વિન્ટલ (100 કિલો)',
    sellTodayVerdict: 'આજે જ વેચો - માર્કેટ યાર્ડ ભાવ ટોચ પર છે',
    waitVerdict: '૨–૩ દિવસ રાહ જુઓ - ભાવ વધવાની ધારણા છે',
    riskVerdict: 'તરત જ વેચો - હવામાન બગડવા કે નુકસાનનું જોખમ',
    netProfitTitle: 'હાથમાં આવતો વાસ્તવિક ચોખ્ખો નફો',
    netProfitSubtitle: 'માત્ર યાર્ડ ભાવ ન જુઓ! ડીઝલ અને પરિવહન ખર્ચ બાદ કરી હાથમાં કેટલા પૈસા બચે તે સરખાવો.',
    yourHarvestQuantity: 'પાકની માત્રા (ક્વિન્ટલ)',
    chooseVehicle: 'વાહન પસંદ કરો',
    dieselTransportCost: 'અંદાજિત પરિવહન/ડીઝલ ખર્ચ',
    grossSale: 'કુલ યાર્ડ વેચાણ',
    actualNetCash: 'હાથમાં ચોખ્ખી રોકડ',
    bestProfitBadge: 'સૌથી વધુ નફાકારક યાર્ડ',
    extraCash: 'વધારાની રોકડ બચત',
    offlineBannerTitle: 'ધીમું ઇન્ટરનેટ કે સાદો કીપેડ ફોન?',
    sendSmsBtn: 'SMS દ્વારા મારા ફોન પર ભાવ મેળવો',
    playAudioBtn: 'ઓડિયો સલાહ સાંભળો',
    missedCallTitle: 'મફત મિસ્ડ કૉલ સેવા',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'કોઈપણ ફોન પરથી મિસ્ડ કૉલ કરો અને મફત ઓડિયો ભાવ સાંભળો',
    distance: 'અંતર',
    buyersToday: 'વેપારીઓ',
    paymentInstant: 'ચૂકવણી',
    sevenDayTrend: '૭-દિવસનો ભાવ ટ્રેન્ડ અને આગાહી',
    today: 'આજે',
    keyFactors: 'આ નિર્ણય કેમ?',
    weatherNotice: 'હવામાન ચેતવણી',
    locationLabel: 'રાજ્ય / સ્થાન',
    changeLocation: 'રાજ્ય બદલો',
    detectLocation: 'GPS થી શોધો',
    detectedNotice: 'તમારા સ્થાન મુજબ ગુજરાતી ભાષા અને યાર્ડ પસંદ કરવામાં આવ્યા છે',
    searchPlaceholder: 'પાક શોધો (કપાસ, મગફળી, જીરું, ડુંગળી, ઘઉં)...',
    allCrops: 'બધા પાકો',
    categoryCereals: 'અનાજ અને બાજરી',
    categoryPulses: 'કઠોળ',
    categoryOilseeds: 'તેલીબિયાં',
    categorySpices: 'મસાલા',
    categoryVegetables: 'શાકભાજી',
    categoryCashCrops: 'રોકડિયા પાક',
    categoryFruits: 'ફળો અને બાગાયત',
    sellBadge: 'આજે જ વેચો',
    waitBadge: 'રાહ જુઓ',
    riskBadge: 'જોખમ / તરત વેચો',
    selectedBadge: 'પસંદ કરેલ',
    selectCropBtn: 'પસંદ કરો',
    resetFilters: 'ફિલ્ટર રીસેટ',
    filterOptions: 'વિકલ્પો',
    cropSelectedBanner: 'પસંદ કરેલ પાક',
    noCropsFound: 'કોઈ પાક મળ્યો નથી',
    tryDifferentSearch: 'બીજું નામ શોધો અથવા ફિલ્ટર સાફ કરો',
    allSignals: 'બધા',
    proceedToDecision: '2. આજનો નિર્ણય ➡️',
    backToCrops: '⬅️ 1. પાક બદલો',
    proceedToProfit: '3. ચોખ્ખો નફો તપાસો ➡️',
    backToDecision: '⬅️ 2. આજનો નિર્ણય',
    proceedToWeather: '4. હવામાન અને સંગ્રહ ➡️',
    backToProfit: '⬅️ 3. ચોખ્ખો નફો',
    proceedToHelp: '5. ખેડૂત સહાય ➡️',
    checkAnotherCrop: '1. બીજો પાક તપાસો',
    voiceSearchBtn: 'બોલીને શોધો',
    connectWithFarmersBtn: 'ખેડૂતો સાથે જોડાઓ',
    poolTruckSubtitle: '૧૦ કિમીમાં વાહન શેર કરો',
    poolTruckloadBtn: 'વાહન શેર કરો (પૂલ)',
    farmersPooledStatus: 'ખેડૂતો જોડાયા • સંયુક્ત વાહન',
    smallYieldBadge: '< ૧૫ ક્વિન્ટલ',
    smallYieldAlert: 'ઓછું ઉત્પાદન (< ૧૫ ક્વિન્ટલ): એકલા વાહન કરવાથી ૨૫-૩૫% નફો ભાડામાં જશે. પડોશી ખેડૂતો સાથે વાહન શેર કરી ₹૮૦-૧૨૦/ક્વિન્ટલ બચાવો!',
    arrivalsLabel: 'આવક',
    volumeTrendLabel: 'આવક વલણ',
    sameStateMandiBanner: '≤ ૧૦૦ કિમી સ્થાનિક માર્કેટ યાર્ડ',
    kmAway: 'કિમી દૂર',
    transitCautionLabel: 'પરિવહન સાવચેતી',
    safeHoldingLabel: 'સલામત સંગ્રહ સમયગાળો',
    recommendedStorageLabel: 'ભલામણ કરેલ સંગ્રહ',
    quintalsUnit: 'ક્વિન્ટલ',
    kgUnit: 'કિલો',
    costOfCultivationLabel: 'ખેતી ખર્ચ (₹/ક્વિન્ટલ)',
    calculateIndividualProfit: 'વ્યક્તિગત નફો જુઓ',
    calculatePooledProfit: 'સંયુક્ત જૂથ નફો જુઓ',
    editPoolBtn: 'પૂલ બદલો',
    bulkPoolingSavings: 'સંયુક્ત વાહન બચત',
    roundTrip: 'આવવા-જવાનું',
    activeTradersLabel: 'સક્રિય વેપારીઓ',
    licensedTraders: 'લાઇસન્સ પ્રાપ્ત',
    paymentLabel: 'ચૂકવણી',
    scientificStorageTitle: 'વૈજ્ઞાનિક સંગ્રહ માર્ગદર્શિકા',
    scientificStorageSubtitle: 'સલામત સંગ્રહ સમય, ભેજનું પ્રમાણ અને પરિવહન સુરક્ષા',
    hideGuidelines: 'છુપાવો',
    viewGuidelines: 'માર્ગદર્શિકા જુઓ',
    safeDurationLabel: 'સલામત સમયગાળો',
    moistureStandardLabel: 'ભેજનું પ્રમાણ',
    keyDirectivesLabel: 'મુખ્ય સૂચનાઓ',
    lowInternetBadge: 'ધીમું ઇન્ટરનેટ અને સાદા ફોન સુવિધા',
    shareWithKisanGroup: 'ખેડૂત ગ્રૂપમાં શેર કરો',
    smsPrefilledNotice: '✓ એસએમએસ ખૂલી ગયું. ભાવ અને સલાહ તૈયાર છે!',
    kisanCallCenterTitle: 'કિસાન કૉલ સેન્ટર',
    kisanCallCenterDesc: 'કૃષિ વૈજ્ઞાનિકો સાથે ૨૨ ભાષાઓમાં સીધી વાત કરો. સવારે ૬ થી રાત્રે ૧૦.',
    callFreeBtn: 'કૉલ કરો 1800-180-1551 (મફત કૉલ)',
    outdoorSunlightTitle: 'તડકો મોડ',
    sunlightModeDesc: 'ખેતરમાં સૂર્યપ્રકાશમાં વાંચવા માટે ઉચ્ચ કોન્ટ્રાસ્ટ.',
    turnSunlightOn: 'તડકો મોડ ચાલુ કરો',
    turnSunlightOff: 'તડકો મોડ ચાલુ છે',
    languagesCountTitle: '૧૩ ભારતીય ભાષાઓ',
    changeZoneBtn: 'બદલો',
    zoneLabel: 'વિસ્તાર',
    cloudSyncTitle: 'કિસાન ક્લાઉડ સિંક',
    signInBtn: 'સાઇન ઇન',
    onlineStatus: 'ઓનલાઇન',
    pinCrop: 'પિન કરો',
    pinnedCrop: 'પિન કરેલ',
    changeCropAction: 'પાક બદલો',
  },
  pa: {
    appName: 'ਮੰਡੀ ਮਿੱਤਰ',
    tagline: 'ਕਿਸਾਨਾਂ ਲਈ ਸਮਾਰਟ ਫ਼ਸਲ ਭਾਅ ਅਤੇ ਅਸਲ ਮੁਨਾਫ਼ਾ ਪ੍ਰਣਾਲੀ',
    audioMode: 'ਸਲਾਹ ਸੁਣੋ',
    audioPlaying: 'ਸਲਾਹ ਪੜ੍ਹੀ ਜਾ ਰਹੀ ਹੈ...',
    stopAudio: 'ਆਵਾਜ਼ ਬੰਦ ਕਰੋ',
    sunlightMode: 'ਧੁੱਪ ਮੋਡ',
    selectCrop: 'ਆਪਣੀ ਫ਼ਸਲ ਚੁਣੋ',
    selectCropSubtitle: 'ਅੱਜ ਦੇ ਮੰਡੀ ਭਾਅ ਅਤੇ ਸਹੀ ਫ਼ੈਸਲੇ ਲਈ ਫ਼ਸਲ ਤੇ ਕਲਿੱਕ ਕਰੋ',
    voiceSearchPrompt: 'ਮਾਈਕ ਦਬਾ ਕੇ ਫ਼ਸਲ ਦਾ ਨਾਮ ਬੋਲੋ (ਜਿਵੇਂ "ਕਣਕ", "ਝੋਨਾ", "ਨਰਮਾ")',
    voiceSearchActive: 'ਸੁਣ ਰਹੇ ਹਾਂ... ਫ਼ਸਲ ਦਾ ਨਾਮ ਬੋਲੋ',
    decisionSignal: 'ਫ਼ੈਸਲਾ ਸੰਕੇਤ (Decision Signal)',
    highestPriceToday: 'ਅੱਜ ਦਾ ਸਭ ਤੋਂ ਉੱਚਾ ਮੰਡੀ ਰੇਟ',
    perQuintal: 'ਪ੍ਰਤੀ ਕੁਇੰਟਲ (100 ਕਿਲੋ)',
    sellTodayVerdict: 'ਅੱਜ ਹੀ ਵੇਚੋ - ਮੰਡੀ ਰੇਟ ਸਿਖਰ ਤੇ ਹਨ',
    waitVerdict: '੨–੩ ਦਿਨ ਰੁਕੋ - ਭਾਅ ਹੋਰ ਵਧਣ ਦੀ ਉਮੀਦ ਹੈ',
    riskVerdict: 'ਤੁਰੰਤ ਵੇਚੋ - ਮੌਸਮ ਖ਼ਰਾਬੀ ਜਾਂ ਖ਼ਰਾਬ ਹੋਣ ਦਾ ਖ਼ਤਰਾ',
    netProfitTitle: 'ਹੱਥ ਵਿੱਚ ਆਉਣ ਵਾਲਾ ਅਸਲ ਮੁਨਾਫ਼ਾ (Net Profit)',
    netProfitSubtitle: 'ਸਿਰਫ਼ ਮੰਡੀ ਦਾ ਭਾਅ ਨਾ ਦੇਖੋ! ਡੀਜ਼ਲ ਅਤੇ ਢੋਆ-ਢੁਆਈ ਖ਼ਰਚ ਕੱਢ ਕੇ ਅਸਲ ਬਚਤ ਦੇਖੋ।',
    yourHarvestQuantity: 'ਫ਼ਸਲ ਦੀ ਮਾਤਰਾ (ਕੁਇੰਟਲ)',
    chooseVehicle: 'ਢੋਆ-ਢੁਆਈ ਵਾਹਨ ਚੁਣੋ',
    dieselTransportCost: 'ਅੰਦਾਜ਼ਨ ਡੀਜ਼ਲ / ਕਿਰਾਇਆ ਖ਼ਰਚ',
    grossSale: 'ਕੁੱਲ ਮੰਡੀ ਵਿਕਰੀ',
    actualNetCash: 'ਹੱਥ ਵਿੱਚ ਸ਼ੁੱਧ ਨਕਦੀ',
    bestProfitBadge: 'ਸਭ ਤੋਂ ਵੱਧ ਮੁਨਾਫ਼ੇ ਵਾਲੀ ਮੰਡੀ',
    extraCash: 'ਵਾਧੂ ਨਕਦ ਬਚਤ',
    offlineBannerTitle: 'ਧੀਮਾ ਇੰਟਰਨੈੱਟ ਜਾਂ ਸਾਦਾ ਕੀਪੈਡ ਫ਼ੋਨ?',
    sendSmsBtn: 'SMS ਰਾਹੀਂ ਮੋਬਾਈਲ ਤੇ ਭਾਅ ਮੰਗਵਾਓ',
    playAudioBtn: 'ਆਡੀਓ ਸਲਾਹ ਪੰਜਾਬੀ ਵਿੱਚ ਸੁਣੋ',
    missedCallTitle: 'ਮੁਫ਼ਤ ਮਿਸਡ ਕਾਲ ਸੇਵਾ',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ਕਿਸੇ ਵੀ ਫ਼ੋਨ ਤੋਂ ਮਿਸਡ ਕਾਲ ਦਿਓ ਅਤੇ ਆਪਣੀ ਬੋਲੀ ਵਿੱਚ ਤੁਰੰਤ ਭਾਅ ਸੁਣੋ',
    distance: 'ਦੂਰੀ',
    buyersToday: 'ਸਰਗਰਮ ਵਪਾਰੀ',
    paymentInstant: 'ਭੁਗਤਾਨ',
    sevenDayTrend: '੭-ਦਿਨ ਦਾ ਭਾਅ ਗ੍ਰਾਫ਼ ਅਤੇ ਭਵਿੱਖਬਾਣੀ',
    today: 'ਅੱਜ',
    keyFactors: 'ਇਹ ਫ਼ੈਸਲਾ ਕਿਉਂ?',
    weatherNotice: 'ਮੌਸਮ ਚੇਤਾਵਨੀ',
    locationLabel: 'ਸੂਬਾ / ਸਥਾਨ',
    changeLocation: 'ਸੂਬਾ ਬਦਲੋ',
    detectLocation: 'GPS ਰਾਹੀਂ ਲੱਭੋ',
    detectedNotice: 'ਤੁਹਾਡੇ ਇਲਾਕੇ ਮੁਤਾਬਕ ਪੰਜਾਬੀ ਭਾਸ਼ਾ ਅਤੇ ਉੱਤਰੀ ਮੰਡੀਆਂ ਚੁਣੀਆਂ ਗਈਆਂ ਹਨ',
    searchPlaceholder: 'ਕਿਸੇ ਵੀ ਫ਼ਸਲ ਦੀ ਖੋਜ ਕਰੋ (ਕਣਕ, ਝੋਨਾ, ਨਰਮਾ, ਸਰ੍ਹੋਂ, ਮੱਕੀ)...',
    allCrops: 'ਸਾਰੀਆਂ ਫ਼ਸਲਾਂ',
    categoryCereals: 'ਅਨਾਜ ਅਤੇ ਬਾਜਰਾ',
    categoryPulses: 'ਦਾਲਾਂ',
    categoryOilseeds: 'ਤੇਲ ਬੀਜ',
    categorySpices: 'ਮਸਾਲੇ',
    categoryVegetables: 'ਸਬਜ਼ੀਆਂ',
    categoryCashCrops: 'ਨਕਦੀ ਫ਼ਸਲਾਂ',
    categoryFruits: 'ਫ਼ਲ ਅਤੇ ਬਾਗ਼ਬਾਨੀ',
    sellBadge: 'ਅੱਜ ਹੀ ਵੇਚੋ',
    waitBadge: 'ਰੁਕੋ',
    riskBadge: 'ਖ਼ਤਰਾ / ਤੁਰੰਤ ਵੇਚੋ',
    selectedBadge: 'ਚੁਣੀ ਗਈ',
    selectCropBtn: 'ਚੁਣੋ',
    resetFilters: 'ਫਿਲਟਰ ਹਟਾਓ',
    filterOptions: 'ਵਿਕਲਪ',
    cropSelectedBanner: 'ਚੁਣੀ ਗਈ ਫ਼ਸਲ',
    noCropsFound: 'ਕੋਈ ਫ਼ਸਲ ਨਹੀਂ ਮਿਲੀ',
    tryDifferentSearch: 'ਕੋਈ ਹੋਰ ਨਾਮ ਖੋਜੋ ਜਾਂ ਫਿਲਟਰ ਸਾਫ਼ ਕਰੋ',
    allSignals: 'ਸਾਰੇ',
    proceedToDecision: '2. ਅੱਜ ਦਾ ਫ਼ੈਸਲਾ ➡️',
    backToCrops: '⬅️ 1. ਫ਼ਸਲ ਬਦਲੋ',
    proceedToProfit: '3. ਮੰਡੀ ਮੁਨਾਫ਼ਾ ਵੇਖੋ ➡️',
    backToDecision: '⬅️ 2. ਅੱਜ ਦਾ ਫ਼ੈਸਲਾ',
    proceedToWeather: '4. ਮੌਸਮ ਅਤੇ ਭੰਡਾਰਨ ➡️',
    backToProfit: '⬅️ 3. ਮੰਡੀ ਮੁਨਾਫ਼ਾ',
    proceedToHelp: '5. ਕਿਸਾਨ ਸਹਾਇਤਾ ➡️',
    checkAnotherCrop: '1. ਦੂਜੀ ਫ਼ਸਲ ਚੁਣੋ',
    voiceSearchBtn: 'ਬੋਲ ਕੇ ਖੋਜੋ',
    connectWithFarmersBtn: 'ਸਾਥੀ ਕਿਸਾਨ ਜੋੜੋ',
    poolTruckSubtitle: '10 ਕਿਮੀ ਵਿੱਚ ਗੱਡੀ ਸਾਂਝੀ ਕਰੋ',
    poolTruckloadBtn: 'ਗੱਡੀ ਸਾਂਝੀ ਕਰੋ (ਪੂਲ)',
    farmersPooledStatus: 'ਕਿਸਾਨ ਜੁੜੇ • ਸਾਂਝੀ ਗੱਡੀ',
    smallYieldBadge: '< 15 ਕੁਇੰਟਲ',
    smallYieldAlert: 'ਘੱਟ ਝਾੜ (< 15 ਕੁਇੰਟਲ): ਇਕੱਲੇ ਗੱਡੀ ਕਰਨ ਤੇ 25-35% ਕਿਰਾਇਆ ਲੱਗ ਸਕਦਾ ਹੈ। ਨੇੜਲੇ ਕਿਸਾਨਾਂ ਨਾਲ ਗੱਡੀ ਸਾਂਝੀ ਕਰਕੇ ₹80-120/ਕੁਇੰਟਲ ਬਚਾਓ!',
    arrivalsLabel: 'ਆਵਕ',
    volumeTrendLabel: 'ਆਵਕ ਰੁਝਾਨ',
    sameStateMandiBanner: '≤ 100 ਕਿਮੀ ਸਥਾਨਕ ਮੰਡੀਆਂ',
    kmAway: 'ਕਿਮੀ ਦੂਰ',
    transitCautionLabel: 'ਮੰਡੀ ਢੋਆ-ਢੁਆਈ ਸਾਵਧਾਨੀ',
    safeHoldingLabel: 'ਸੁਰੱਖਿਅਤ ਭੰਡਾਰਨ ਸਮਾਂ',
    recommendedStorageLabel: 'ਸਿਫ਼ਾਰਸ਼ੀ ਭੰਡਾਰਨ',
    quintalsUnit: 'ਕੁਇੰਟਲ',
    kgUnit: 'ਕਿਲੋ',
    costOfCultivationLabel: 'ਲਾਗਤ ਖ਼ਰਚਾ (₹/ਕੁਇੰਟਲ)',
    calculateIndividualProfit: 'ਨਿੱਜੀ ਮੁਨਾਫ਼ਾ ਵੇਖੋ',
    calculatePooledProfit: 'ਸਾਂਝਾ ਗਰੁੱਪ ਮੁਨਾਫ਼ਾ ਵੇਖੋ',
    editPoolBtn: 'ਪੂਲ ਬਦਲੋ',
    bulkPoolingSavings: 'ਸਾਂਝੀ ਗੱਡੀ ਬਚਤ',
    roundTrip: 'ਆਉਣਾ-ਜਾਣਾ',
    activeTradersLabel: 'ਸਰਗਰਮ ਵਪਾਰੀ',
    licensedTraders: 'ਲਸੰਸਸ਼ੁਦਾ',
    paymentLabel: 'ਭੁਗਤਾਨ',
    scientificStorageTitle: 'ਵਿਗਿਆਨਕ ਭੰਡਾਰਨ ਨਿਯਮ',
    scientificStorageSubtitle: 'ਸੁਰੱਖਿਅਤ ਸਮਾਂ, ਨਮੀ ਦਾ ਪੱਧਰ ਅਤੇ ਢੋਆ-ਢੁਆਈ ਸੁਰੱਖਿਆ',
    hideGuidelines: 'ਲੁਕਾਓ',
    viewGuidelines: 'ਨਿਯਮ ਵੇਖੋ',
    safeDurationLabel: 'ਸੁਰੱਖਿਅਤ ਸਮਾਂ',
    moistureStandardLabel: 'ਨਮੀ ਦਾ ਪੱਧਰ',
    keyDirectivesLabel: 'ਮੁੱਖ ਹਦਾਇਤਾਂ',
    lowInternetBadge: 'ਧੀਮਾ ਇੰਟਰਨੈੱਟ ਅਤੇ ਸਾਦਾ ਫ਼ੋਨ ਸਹੂਲਤ',
    shareWithKisanGroup: 'ਕਿਸਾਨ ਗਰੁੱਪ ਵਿੱਚ ਭੇਜੋ',
    smsPrefilledNotice: '✓ ਐੱਸਐੱਮਐੱਸ ਖੁੱਲ੍ਹ ਗਿਆ। ਮੰਡੀ ਰੇਟ ਅਤੇ ਸਲਾਹ ਤਿਆਰ ਹੈ!',
    kisanCallCenterTitle: 'ਕਿਸਾਨ ਕਾਲ ਸੈਂਟਰ',
    kisanCallCenterDesc: 'ਖੇਤੀ ਵਿਗਿਆਨੀਆਂ ਨਾਲ 22 ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਗੱਲ ਕਰੋ। ਸਵੇਰੇ 6 ਤੋਂ ਰਾਤ 10 ਵਜੇ ਤੱਕ।',
    callFreeBtn: 'ਕਾਲ ਕਰੋ 1800-180-1551 (ਮੁਫ਼ਤ ਕਾਲ)',
    outdoorSunlightTitle: 'ਧੁੱਪ ਮੋਡ',
    sunlightModeDesc: 'ਖੇਤ ਵਿੱਚ ਤੇਜ਼ ਧੁੱਪ ਵਿੱਚ ਪੜ੍ਹਨ ਲਈ ਗੂੜ੍ਹਾ ਕੰਟਰਾਸਟ।',
    turnSunlightOn: 'ਧੁੱਪ ਮੋਡ ਚਾਲੂ ਕਰੋ',
    turnSunlightOff: 'ਧੁੱਪ ਮੋਡ ਚਾਲੂ ਹੈ',
    languagesCountTitle: '13 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ',
    changeZoneBtn: 'ਬਦਲੋ',
    zoneLabel: 'ਜ਼ੋਨ',
    cloudSyncTitle: 'ਕਿਸਾਨ ਕਲਾਊਡ ਸਿੰਕ',
    signInBtn: 'ਸਾਈਨ ਇਨ',
    onlineStatus: 'ਆਨਲਾਈਨ',
    pinCrop: 'ਪਿੰਨ ਕਰੋ',
    pinnedCrop: 'ਪਿੰਨ ਕੀਤਾ',
    changeCropAction: 'ਫ਼ਸਲ ਬਦਲੋ',
  },
  bn: {
    appName: 'মান্ডি মিত্র',
    tagline: 'কৃষকদের জন্য স্মার্ট ফসলের বাজারদর ও আসল মুনাফা পরামর্শ',
    audioMode: 'পরামর্শ শুনুন',
    audioPlaying: 'পরামর্শ পড়া হচ্ছে...',
    stopAudio: 'শব্দ বন্ধ করুন',
    sunlightMode: 'রোদ মোড',
    selectCrop: 'আপনার ফসল বেছে নিন',
    selectCropSubtitle: 'আজকের বাজারদর ও সঠিক সিদ্ধান্তের জন্য ফসলে ক্লিক করুন',
    voiceSearchPrompt: 'মাইক টিপে ফসলের নাম বলুন (যেমন "ধান", "আলু", "পাট")',
    voiceSearchActive: 'শুনছি... ফসলের নাম বলুন',
    decisionSignal: 'সিদ্ধান্ত সংকেত (Decision Signal)',
    highestPriceToday: 'আজকের সর্বোচ্চ বাজারদর',
    perQuintal: 'প্রতি কুইন্টাল (১০০ কেজি)',
    sellTodayVerdict: 'আজই বিক্রি করুন - বাজারদর শীর্ষে রয়েছে',
    waitVerdict: '২–৩ দিন অপেক্ষা করুন - দর আরও বাড়ার সম্ভাবনা',
    riskVerdict: 'অবিলম্বে বিক্রি করুন - আবহাওয়া বা নষ্ট হওয়ার ঝুঁকি',
    netProfitTitle: 'হাতে পাওয়া আসল লাভ (Net Profit)',
    netProfitSubtitle: 'শুধু বাজারের দর দেখবেন না! পরিবহন ও ডিজেল খরচ বাদ দিয়ে আসল টাকা হিসাব করুন।',
    yourHarvestQuantity: 'ফসলের পরিমাণ (কুইন্টাল)',
    chooseVehicle: 'পরিবহন গাড়ি বেছে নিন',
    dieselTransportCost: 'আনুমানিক ডিজেল ও পরিবহন খরচ',
    grossSale: 'মোট বাজার বিক্রয়',
    actualNetCash: 'হাতে নগদ আসল টাকা',
    bestProfitBadge: 'সেরা লাভের বাজার',
    extraCash: 'অতিরিক্ত নগদ লাভ',
    offlineBannerTitle: 'ধীরগতির ইন্টারনেট বা বোতামের ফোন?',
    sendSmsBtn: 'SMS এর মাধ্যমে ফোনে দর আনুন',
    playAudioBtn: 'বাংলায় ভয়েস পরামর্শ শুনুন',
    missedCallTitle: 'বিনামূল্যে মিসড কল সেবা',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'যেকোনো ফোন থেকে মিসড কল দিন এবং আপনার ভাষায় বিনামূল্যে দর শুনুন',
    distance: 'দূরত্ব',
    buyersToday: 'সক্রিয় ব্যবসায়ী',
    paymentInstant: 'পেমেন্ট',
    sevenDayTrend: '৭ দিনের দর গ্রাফ ও পূর্বাভাস',
    today: 'আজ',
    keyFactors: 'কেন এই সিদ্ধান্ত?',
    weatherNotice: 'আবহাওয়া সতর্কতা',
    locationLabel: 'রাজ্য / স্থান',
    changeLocation: 'রাজ্য পরিবর্তন করুন',
    detectLocation: 'GPS দিয়ে খুঁজুন',
    detectedNotice: 'আপনার অবস্থান অনুসারে বাংলা ভাষা ও আঞ্চলিক বাজার নির্ধারণ করা হয়েছে',
    searchPlaceholder: 'যেকোনো ফসল খুঁজুন (ধান, আলু, পাট, চা, সরিষা)...',
    allCrops: 'সব ফসল',
    categoryCereals: 'দানা শস্য ও বাজরা',
    categoryPulses: 'ডাল শস্য',
    categoryOilseeds: 'তৈলবীজ',
    categorySpices: 'মশলা',
    categoryVegetables: 'শাকসবজি',
    categoryCashCrops: 'অর্থকরী ফসল',
    categoryFruits: 'ফল ও বাগান',
    sellBadge: 'আজই বিক্রি করুন',
    waitBadge: 'অপেক্ষা করুন',
    riskBadge: 'ঝুঁকি / দ্রুত বিক্রি করুন',
    selectedBadge: 'নির্বাচিত',
    selectCropBtn: 'নির্বাচন করুন',
    resetFilters: 'ফিল্টার মুছুন',
    filterOptions: 'বিকল্প',
    cropSelectedBanner: 'নির্বাচিত ফসল',
    noCropsFound: 'কোনো ফসল পাওয়া যায়নি',
    tryDifferentSearch: 'অন্য নাম খুঁজুন বা ফিল্টার পরিষ্কার করুন',
    allSignals: 'সব',
    proceedToDecision: '2. আজকের সিদ্ধান্ত ➡️',
    backToCrops: '⬅️ 1. ফসল পরিবর্তন',
    proceedToProfit: '3. নিট লাভ হিসাব ➡️',
    backToDecision: '⬅️ 2. আজকের সিদ্ধান্ত',
    proceedToWeather: '4. আবহাওয়া ও সংরক্ষণ ➡️',
    backToProfit: '⬅️ 3. নিট লাভ',
    proceedToHelp: '5. কৃষক সহায়তা ➡️',
    checkAnotherCrop: '1. অন্য ফসল দেখুন',
    voiceSearchBtn: 'কথা বলে খুঁজুন',
    connectWithFarmersBtn: 'কৃষকদের সাথে যুক্ত হন',
    poolTruckSubtitle: '১০ কিমির মধ্যে গাড়ি ভাগ করুন',
    poolTruckloadBtn: 'গাড়ি ভাগ করুন (পুল)',
    farmersPooledStatus: 'কৃষক যুক্ত • যৌথ গাড়ি',
    smallYieldBadge: '< ১৫ কুইন্টাল',
    smallYieldAlert: 'কম ফলন (< ১৫ কুইন্টাল): একা গাড়ি নিলে ২৫-৩৫% ভাড়া চলে যেতে পারে। আশপাশের কৃষকদের সাথে গাড়ি ভাগ করে ₹৮০-১২০/কুইন্টাল বাঁচান!',
    arrivalsLabel: 'আমদানি',
    volumeTrendLabel: 'আমদানি ধারা',
    sameStateMandiBanner: '≤ ১০০ কিমি স্থানীয় বাজার',
    kmAway: 'কিমি দূরে',
    transitCautionLabel: 'পরিবহন সতর্কতা',
    safeHoldingLabel: 'নিরাপদ সংরক্ষণ সময়',
    recommendedStorageLabel: 'প্রস্তাবিত সংরক্ষণ',
    quintalsUnit: 'কুইন্টাল',
    kgUnit: 'কেজি',
    costOfCultivationLabel: 'উৎপাদন খরচ (₹/কুইন্টাল)',
    calculateIndividualProfit: 'ব্যক্তিগত লাভ দেখুন',
    calculatePooledProfit: 'যৌথ গাড়ির লাভ দেখুন',
    editPoolBtn: 'পুল পরিবর্তন',
    bulkPoolingSavings: 'যৌথ গাড়ি সাশ্রয়',
    roundTrip: 'যাওয়া-আসা',
    activeTradersLabel: 'সক্রিয় ব্যবসায়ী',
    licensedTraders: 'লাইসেন্সপ্রাপ্ত',
    paymentLabel: 'পেমেন্ট',
    scientificStorageTitle: 'বৈজ্ঞানিক সংরক্ষণ নির্দেশিকা',
    scientificStorageSubtitle: 'নিরাপদ সময়, আর্দ্রতা মান ও পরিবহন নিরাপত্তা',
    hideGuidelines: 'লুকান',
    viewGuidelines: 'নির্দেশিকা দেখুন',
    safeDurationLabel: 'নিরাপদ সময়',
    moistureStandardLabel: 'আর্দ্রতা মান',
    keyDirectivesLabel: 'মূল নির্দেশাবলী',
    lowInternetBadge: 'কম ইন্টারনেট ও বোতাম ফোন সুবিধা',
    shareWithKisanGroup: 'কৃষক গ্রুপে শেয়ার করুন',
    smsPrefilledNotice: '✓ এসএমএস খুলেছে। দর ও পরামর্শ প্রস্তুত!',
    kisanCallCenterTitle: 'কিসান কল সেন্টার',
    kisanCallCenterDesc: 'কৃষি বিজ্ঞানীদের সাথে সরাসরি কথা বলুন। প্রতিদিন সকাল ৬টা থেকে রাত ১০টা পর্যন্ত।',
    callFreeBtn: 'কল করুন 1800-180-1551 (টোল-ফ্রি)',
    outdoorSunlightTitle: 'রোদ মোড',
    sunlightModeDesc: 'মাঠে তীব্র রোদে পড়ার জন্য উচ্চ কনট্রাস্ট।',
    turnSunlightOn: 'রোদ মোড চালু করুন',
    turnSunlightOff: 'রোদ মোড চালু আছে',
    languagesCountTitle: '১৩টি ভারতীয় ভাষা',
    changeZoneBtn: 'পরিবর্তন',
    zoneLabel: 'অঞ্চল',
    cloudSyncTitle: 'কিসান ক্লাউড সিঙ্ক',
    signInBtn: 'সাইন ইন',
    onlineStatus: 'অনলাইন',
    pinCrop: 'পিন করুন',
    pinnedCrop: 'পিন করা হয়েছে',
    changeCropAction: 'ফসল পরিবর্তন',
  },
  te: {
    appName: 'మండి మిత్ర',
    tagline: 'రైతుల కోసం స్మార్ట్ మార్కెట్ ధరలు & నికర లాభ సూచిక',
    audioMode: 'సలహా వినండి',
    audioPlaying: 'సలహా చదువుతోంది...',
    stopAudio: 'ఆపండి',
    sunlightMode: 'ఎండ మోడ్',
    selectCrop: 'మీ పంటను ఎంచుకోండి',
    selectCropSubtitle: 'నేటి మార్కెట్ యార్డ్ ధరలు & సరైన నిర్ణయం కోసం పంటను నొక్కండి',
    voiceSearchPrompt: 'మైక్ నొక్కి పంట పేరు చెప్పండి (ఉదా. "మిర్చి", "వరి", "పత్తి")',
    voiceSearchActive: 'వింటున్నాము... పంట పేరు చెప్పండి',
    decisionSignal: 'నిర్ణయ సంకేతం (Decision Signal)',
    highestPriceToday: 'నేటి అత్యధిక మార్కెట్ ధర',
    perQuintal: 'క్వింటాల్‌కు (100 కిలోలు)',
    sellTodayVerdict: 'ఈరోజే అమ్మండి - మార్కెట్ ధరలు గరిష్ట స్థాయికి చేరాయి',
    waitVerdict: '2–3 రోజులు ఆగండి - ధరలు పెరిగే అవకాశం ఉంది',
    riskVerdict: 'వెంటనే అమ్మండి - వాతావరణం లేదా నష్టం ముప్పు',
    netProfitTitle: 'చేతికి అందే నికర లాభం (Net Profit)',
    netProfitSubtitle: 'కేవలం రేటు మాత్రమే చూడకండి! రవాణా ఖర్చులు తీసివేసిన తర్వాత మిగిలే డబ్బును లెక్కించండి.',
    yourHarvestQuantity: 'పంట పరిమాణం (క్వింటాళ్ళు)',
    chooseVehicle: 'రవాణా వాహనాన్ని ఎంచుకోండి',
    dieselTransportCost: 'అంచనా డీజిల్ / రవాణా ఖర్చు',
    grossSale: 'మొత్తం మార్కెట్ అమ్మకం',
    actualNetCash: 'చేతికి వచ్చే నికర నగదు',
    bestProfitBadge: 'అత్యధిక లాభం వచ్చే మార్కెట్',
    extraCash: 'అదనపు నగదు ఆదా',
    offlineBannerTitle: 'నెట్ స్లోగా ఉందా లేదా కీప్యాడ్ ఫోనా?',
    sendSmsBtn: 'SMS ద్వారా ఫోన్‌కు ధరలను పొందండి',
    playAudioBtn: 'తెలుగులో ఆడియో సలహా వినండి',
    missedCallTitle: 'ఉచిత మిస్డ్ కాల్ సేవ',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ఏ ఫోన్ నుంచైనా మిస్డ్ కాల్ ఇచ్చి మీ మాతృభాషలో ధరలు తెలుసుకోండి',
    distance: 'దూరం',
    buyersToday: 'కొనుగోలు వ్యాపారులు',
    paymentInstant: 'చెల్లింపు',
    sevenDayTrend: '7 రోజుల ధరల ట్రెండ్ & అంచనా',
    today: 'నేడు',
    keyFactors: 'ఈ నిర్ణయం ఎందుకు?',
    weatherNotice: 'వాతావరణ హెచ్చరిక',
    locationLabel: 'రాష్ట్రం / ప్రాంతం',
    changeLocation: 'రాష్ట్రం మార్చండి',
    detectLocation: 'GPS ద్వారా గుర్తించండి',
    detectedNotice: 'మీ ప్రాంతం ప్రకారం తెలుగు భాష మరియు మార్కెట్లు ఎంపిక చేయబడ్డాయి',
    searchPlaceholder: 'ఏదైనా పంటను వెతకండి (మిర్చి, పత్తి, వరి, మొక్కజొన్న, పసుపు)...',
    allCrops: 'అన్ని పంటలు',
    categoryCereals: 'ధాన్యాలు & మిల్లెట్లు',
    categoryPulses: 'పప్పుధాన్యాలు',
    categoryOilseeds: 'నూనె గింజలు',
    categorySpices: 'మసాలా దినుసులు',
    categoryVegetables: 'కూరగాయలు',
    categoryCashCrops: 'వాణిజ్య పంటలు',
    categoryFruits: 'పండ్లు & తోటలు',
    sellBadge: 'ఈరోజే అమ్మండి',
    waitBadge: 'వేచి ఉండండి',
    riskBadge: 'ప్రమాదం / వెంటనే అమ్మండి',
    selectedBadge: 'ఎంచుకున్నారు',
    selectCropBtn: 'ఎంచుకోండి',
    resetFilters: 'ఫిల్టర్లు రీసెట్',
    filterOptions: 'ఎంపికలు',
    cropSelectedBanner: 'ఎంచుకున్న పంట',
    noCropsFound: 'పంటలు కనుగొనబడలేదు',
    tryDifferentSearch: 'వేరే పేరుతో వెతకండి లేదా ఫిల్టర్ తొలగించండి',
    allSignals: 'అన్నీ',
    proceedToDecision: '2. నేటి నిర్ణయం ➡️',
    backToCrops: '⬅️ 1. పంట మార్చండి',
    proceedToProfit: '3. నికర లాభం చూడండి ➡️',
    backToDecision: '⬅️ 2. నేటి నిర్ణయం',
    proceedToWeather: '4. వాతావరణం & నిల్వ ➡️',
    backToProfit: '⬅️ 3. నికర లాభం',
    proceedToHelp: '5. రైతు సహాయం ➡️',
    checkAnotherCrop: '1. వేరే పంట చూడండి',
    voiceSearchBtn: 'మాట్లాడి వెతకండి',
    connectWithFarmersBtn: 'రైతులతో కనెక్ట్ అవ్వండి',
    poolTruckSubtitle: '10 కి.మీ పరిధిలో వాహనం పంచుకోండి',
    poolTruckloadBtn: 'వాహనం షేర్ చేయండి (పూల్)',
    farmersPooledStatus: 'రైతులు కలిశారు • ఉమ్మడి వాహనం',
    smallYieldBadge: '< 15 క్వింటాళ్లు',
    smallYieldAlert: 'తక్కువ దిగుబడి (< 15 క్వింటాళ్లు): సొంతంగా వాహనం మాట్లాడితే 25-35% రవాణా ఖర్చు అవుతుంది. సమీప రైతులతో వాహనం పంచుకొని ₹80-120/క్వింటాల్ ఆదా చేయండి!',
    arrivalsLabel: 'రాబడులు',
    volumeTrendLabel: 'రాబడుల సరళి',
    sameStateMandiBanner: '≤ 100 కి.మీ సమీప మార్కెట్లు',
    kmAway: 'కి.మీ దూరం',
    transitCautionLabel: 'రవాణా జాగ్రత్తలు',
    safeHoldingLabel: 'సురక్షిత నిల్వ సమయం',
    recommendedStorageLabel: 'సిఫార్సు చేసిన నిల్వ',
    quintalsUnit: 'క్వింటాళ్లు',
    kgUnit: 'కిలోలు',
    costOfCultivationLabel: 'సాగు ఖర్చు (₹/క్వింటాల్)',
    calculateIndividualProfit: 'వ్యక్తిగత లాభం చూడండి',
    calculatePooledProfit: 'ఉమ్మడి వాహన లాభం చూడండి',
    editPoolBtn: 'పూల్ మార్చండి',
    bulkPoolingSavings: 'ఉమ్మడి వాహన ఆదా',
    roundTrip: 'రాను-పోను',
    activeTradersLabel: 'క్రియాశీల వ్యాపారులు',
    licensedTraders: 'లైసెన్స్ పొందిన',
    paymentLabel: 'చెల్లింపు',
    scientificStorageTitle: 'శాస్త్రీయ నిల్వ మార్గదర్శకాలు',
    scientificStorageSubtitle: 'సురక్షిత సమయం, తేమ ప్రమాణాలు మరియు రవాణా భద్రత',
    hideGuidelines: 'దాచు',
    viewGuidelines: 'మార్గదర్శకాలు చూడండి',
    safeDurationLabel: 'సురక్షిత సమయం',
    moistureStandardLabel: 'తేమ ప్రమాణం',
    keyDirectivesLabel: 'ముఖ్య సూచనలు',
    lowInternetBadge: 'తక్కువ ఇంటర్నెట్ & బటన్ ఫోన్ సౌకర్యం',
    shareWithKisanGroup: 'రైతు గ్రూపులో షేర్ చేయండి',
    smsPrefilledNotice: '✓ ఎస్ఎంఎస్ ఓపెన్ అయింది. రేట్లు, సలహా సిద్ధంగా ఉన్నాయి!',
    kisanCallCenterTitle: 'కిసాన్ కాల్ సెంటర్',
    kisanCallCenterDesc: 'వ్యవసాయ శాస్త్రవేత్తలతో 22 భాషల్లో మాట్లాడండి. ఉదయం 6 నుండి రాత్రి 10 వరకు.',
    callFreeBtn: 'కాల్ చేయండి 1800-180-1551 (ఉచితం)',
    outdoorSunlightTitle: 'ఎండ మోడ్',
    sunlightModeDesc: 'పొలంలో ఎండలో స్పష్టంగా చదవడానికి అధిక కాంట్రాస్ట్.',
    turnSunlightOn: 'ఎండ మోడ్ ఆన్ చేయండి',
    turnSunlightOff: 'ఎండ మోడ్ ఆన్‌లో ఉంది',
    languagesCountTitle: '13 భారతీయ భాషలు',
    changeZoneBtn: 'మార్చండి',
    zoneLabel: 'ప్రాంతం',
    cloudSyncTitle: 'రైతు క్లౌడ్ సింక్',
    signInBtn: 'సైన్ ఇన్',
    onlineStatus: 'ఆన్‌లైన్',
    pinCrop: 'పిన్ చేయండి',
    pinnedCrop: 'పిన్ చేయబడింది',
    changeCropAction: 'పంట మార్చండి',
  },
  ta: {
    appName: 'மண்டி மித்ரா',
    tagline: 'விவசாயிகளுக்கான சந்தை விலை மற்றும் நிகர லாப வழிகாட்டி',
    audioMode: 'ஆலோசனை கேட்க',
    audioPlaying: 'ஆலோசனை ஒலிக்கிறது...',
    stopAudio: 'நிறுத்து',
    sunlightMode: 'வெயில் முறை',
    selectCrop: 'உங்கள் பயிரைத் தேர்வுசெய்க',
    selectCropSubtitle: 'இன்றைய சந்தை விலை மற்றும் முடிவுகளை அறிய பயிரைத் தொடவும்',
    voiceSearchPrompt: 'மைக்கை அழுத்தி பயிர் பெயரைப் பேசுங்கள் (எ.கா. "நெல்", "மஞ்சள்", "வெங்காயம்")',
    voiceSearchActive: 'கேட்கிறது... பயிரின் பெயரைச் சொல்லுங்கள்',
    decisionSignal: 'முடிவு சமிக்ஞை (Decision Signal)',
    highestPriceToday: 'இன்றைய அதிகபட்ச சந்தை விலை',
    perQuintal: 'குவிண்டாலுக்கு (100 கிலோ)',
    sellTodayVerdict: 'இன்றே விற்கவும் - சந்தை விலை உச்சத்தில் உள்ளது',
    waitVerdict: '2–3 நாட்கள் காத்திருக்கவும் - விலை உயரும் வாய்ப்பு',
    riskVerdict: 'உடனடியாக விற்கவும் - வானிலை அல்லது சேத அபாயம்',
    netProfitTitle: 'கைக்கு கிடைக்கும் நிகர லாபம் (Net Profit)',
    netProfitSubtitle: 'சந்தை விலையை மட்டும் பார்க்காதீர்கள்! போக்குவரத்து செலவைக் கழித்த பிறகான நிகர தொகையை அறியுங்கள்.',
    yourHarvestQuantity: 'பயிர் அளவு (குவிண்டால்)',
    chooseVehicle: 'வாகனத்தைத் தேர்ந்தெடுக்கவும்',
    dieselTransportCost: 'போக்குவரத்து செலவு',
    grossSale: 'மொத்த சந்தை விற்பனை',
    actualNetCash: 'கைக்கு வரும் நிகர பணம்',
    bestProfitBadge: 'அதிக லாபகரமான சந்தை',
    extraCash: 'கூடுதல் லாப சேமிப்பு',
    offlineBannerTitle: 'இணையம் மெதுவாக உள்ளதா அல்லது பட்டன் போனா?',
    sendSmsBtn: 'SMS மூலம் விலையை அறியவும்',
    playAudioBtn: 'தமிழில் குரல் வழிகாட்டல் கேட்க',
    missedCallTitle: 'இலவச மிஸ்டு கால் சேவை',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'எந்த போனிலிருந்தும் மிஸ்டு கால் கொடுத்து உங்கள் மொழியில் விலை அறியலாம்',
    distance: 'தொலைவு',
    buyersToday: 'வணிகர்கள்',
    paymentInstant: 'பணம் பட்டுவாடா',
    sevenDayTrend: '7 நாள் விலை நிலவரம் மற்றும் கணிப்பு',
    today: 'இன்று',
    keyFactors: 'இந்த முடிவு ஏன்?',
    weatherNotice: 'வானிலை எச்சரிக்கை',
    locationLabel: 'மாநிலம் / இருப்பிடம்',
    changeLocation: 'மாநிலத்தை மாற்றுக',
    detectLocation: 'GPS மூலம் கண்டறி',
    detectedNotice: 'உங்கள் இருப்பிடத்திற்கு ஏற்ப தமிழ் மொழி மற்றும் சந்தைகள் தேர்வு செய்யப்பட்டுள்ளன',
    searchPlaceholder: 'பயிர்களைத் தேடுங்கள் (நெல், மஞ்சள், பருத்தி, வாழை, தேங்காய்)...',
    allCrops: 'அனைத்துப் பயிர்கள்',
    categoryCereals: 'தானியங்கள் மற்றும் சிறுதானியங்கள்',
    categoryPulses: 'பருப்பு வகைகள்',
    categoryOilseeds: 'எண்ணெய் வித்துக்கள்',
    categorySpices: 'நறுமணப் பொருட்கள்',
    categoryVegetables: 'காய்கறிகள்',
    categoryCashCrops: 'பணப்பயிர்கள்',
    categoryFruits: 'பழங்கள் & தோட்டங்கள்',
    sellBadge: 'இன்றே விற்கவும்',
    waitBadge: 'காத்திருக்கவும்',
    riskBadge: 'அபாயம் / உடனே விற்கவும்',
    selectedBadge: 'தேர்ந்தெடுக்கப்பட்டது',
    selectCropBtn: 'தேர்வு செய்க',
    resetFilters: 'வடிகட்டிகளை மீட்டமை',
    filterOptions: 'விருப்பங்கள்',
    cropSelectedBanner: 'தேர்ந்தெடுக்கப்பட்ட பயிர்',
    noCropsFound: 'பயிர்கள் எதுவும் கிடைக்கவில்லை',
    tryDifferentSearch: 'வேறு பெயரைத் தேடவும் அல்லது வடிகட்டியை அழிக்கவும்',
    allSignals: 'அனைத்தும்',
    proceedToDecision: '2. இன்றைய முடிவு ➡️',
    backToCrops: '⬅️ 1. பயிர் மாற்றுக',
    proceedToProfit: '3. நிகர லாபம் கணக்கிடுக ➡️',
    backToDecision: '⬅️ 2. இன்றைய முடிவு',
    proceedToWeather: '4. வானிலை & சேமிப்பு ➡️',
    backToProfit: '⬅️ 3. நிகர லாபம்',
    proceedToHelp: '5. உழவர் உதவி ➡️',
    checkAnotherCrop: '1. வேறு பயிர் பார்க்க',
    voiceSearchBtn: 'பேசி தேடவும்',
    connectWithFarmersBtn: 'விவசாயிகளுடன் இணையுங்கள்',
    poolTruckSubtitle: '10 கி.மீ-க்குள் வாகனத்தைப் பகிருங்கள்',
    poolTruckloadBtn: 'வாகனம் பகிரவும் (Pool)',
    farmersPooledStatus: 'விவசாயிகள் இணைந்தனர் • கூட்டு வாகனம்',
    smallYieldBadge: '< 15 குவிண்டால்',
    smallYieldAlert: 'குறைந்த விளைச்சல் (< 15 குவிண்டால்): தனியாக வாகனம் பேசினால் 25-35% வாடகைக்கே போகும். அருகில் உள்ள விவசாயிகளுடன் இணைந்து ₹80-120/குவிண்டால் மிச்சப்படுத்துங்கள்!',
    arrivalsLabel: 'வரத்து',
    volumeTrendLabel: 'வரத்து போக்கு',
    sameStateMandiBanner: '≤ 100 கி.மீ மண்டிகள்',
    kmAway: 'கி.மீ தூரம்',
    transitCautionLabel: 'போக்குவரத்து எச்சரிக்கை',
    safeHoldingLabel: 'பாதுகாப்பான சேமிப்பு காலம்',
    recommendedStorageLabel: 'பரிந்துரைக்கப்பட்ட சேமிப்பு',
    quintalsUnit: 'குவிண்டால்',
    kgUnit: 'கிலோ',
    costOfCultivationLabel: 'சாகுபடி செலவு (₹/குவிண்டால்)',
    calculateIndividualProfit: 'தனிநபர் லாபம் பார்க்க',
    calculatePooledProfit: 'கூட்டு வாகன லாபம் பார்க்க',
    editPoolBtn: 'பகிர்வு மாற்று',
    bulkPoolingSavings: 'கூட்டு வாகன சேமிப்பு',
    roundTrip: 'போய்-வர',
    activeTradersLabel: 'செயலில் உள்ள வியாபாரிகள்',
    licensedTraders: 'உரிமம் பெற்ற',
    paymentLabel: 'பணம் செலுத்துதல்',
    scientificStorageTitle: 'அறிவியல் பூர்வ சேமிப்பு வழிகாட்டுதல்கள்',
    scientificStorageSubtitle: 'பாதுகாப்பான காலம், ஈரப்பத அளவு & போக்குவரத்து பாதுகாப்பு',
    hideGuidelines: 'மறைக்க',
    viewGuidelines: 'வழிகாட்டுதலைப் பார்க்க',
    safeDurationLabel: 'பாதுகாப்பான காலம்',
    moistureStandardLabel: 'ஈரப்பத அளவு',
    keyDirectivesLabel: 'முக்கிய வழிகாட்டுதல்கள்',
    lowInternetBadge: 'குறைந்த இணையம் & சாதாரண போன் வசதி',
    shareWithKisanGroup: 'விவசாயிகள் குழுவில் பகிரவும்',
    smsPrefilledNotice: '✓ எஸ்.எம்.எஸ் திறந்தது. விலை மற்றும் ஆலோசனை தயார்!',
    kisanCallCenterTitle: 'கிசான் கால் சென்டர்',
    kisanCallCenterDesc: 'விவசாய விஞ்ஞானிகளுடன் 22 மொழிகளில் பேசுங்கள். காலை 6 முதல் இரவு 10 வரை.',
    callFreeBtn: 'அழைக்கவும் 1800-180-1551 (இலவசம்)',
    outdoorSunlightTitle: 'வெயில் முறை (Sunlight Mode)',
    sunlightModeDesc: 'வயலில் வெளிச்சத்தில் படிக்க சிறந்த காண்ட்ராஸ்ட்.',
    turnSunlightOn: 'வெயில் முறை இயக்கவும்',
    turnSunlightOff: 'வெயில் முறை இயங்குகிறது',
    languagesCountTitle: '13 இந்திய மொழிகள்',
    changeZoneBtn: 'மாற்றுக',
    zoneLabel: 'மண்டலம்',
    cloudSyncTitle: 'விவசாயி கிளவுட் இணைப்பு',
    signInBtn: 'உள்நுழைக',
    onlineStatus: 'ஆன்லைன்',
    pinCrop: 'பின் செய்க',
    pinnedCrop: 'பின் செய்யப்பட்டது',
    changeCropAction: 'பயிர் மாற்றுக',
  },
  kn: {
    appName: 'ಮಂಡಿ ಮಿತ್ರ',
    tagline: 'ರೈತರಿಗಾಗಿ ಸ್ಮಾರ್ಟ್ ಮಾರುಕಟ್ಟೆ ದರ ಮತ್ತು ನಿವ್ವಳ ಲಾಭ ವ್ಯವಸ್ಥೆ',
    audioMode: 'ಸಲಹೆ ಆಲಿಸಿ',
    audioPlaying: 'ಸಲಹೆ ಓದಲಾಗುತ್ತಿದೆ...',
    stopAudio: 'ಧ್ವನಿ ನಿಲ್ಲಿಸಿ',
    sunlightMode: 'ಬಿಸಿಲು ಮೋಡ್',
    selectCrop: 'ನಿಮ್ಮ ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ',
    selectCropSubtitle: 'ಇಂದಿನ ಮಾರುಕಟ್ಟೆ ದರ ಮತ್ತು ಸರಿಯಾದ ನಿರ್ಧಾರ ತಿಳಿಯಲು ಬೆಳೆ ಮೇಲೆ ಸ್ಪರ್ಶಿಸಿ',
    voiceSearchPrompt: 'ಮೈಕ್ ಒತ್ತಿ ಬೆಳೆಯ ಹೆಸರು ಹೇಳಿ (ಉದಾ: "ರಾಗಿ", "ತೊಗರಿ", "ಟೊಮೆಟೊ")',
    voiceSearchActive: 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ... ಬೆಳೆಯ ಹೆಸರು ಹೇಳಿ',
    decisionSignal: 'ನಿರ್ಧಾರ ಸಂಕೇತ (Decision Signal)',
    highestPriceToday: 'ಇಂದಿನ ಗರಿಷ್ಠ ಮಾರುಕಟ್ಟೆ ದರ',
    perQuintal: 'ಪ್ರತಿ ಕ್ವಿಂಟಾಲ್‌ಗೆ (100 ಕೆಜಿ)',
    sellTodayVerdict: 'ಇಂದೇ ಮಾರಾಟ ಮಾಡಿ - ಮಾರುಕಟ್ಟೆ ದರ ಗರಿಷ್ಠ ಮಟ್ಟದಲ್ಲಿದೆ',
    waitVerdict: '೨–೩ ದಿನ ಕಾಯಿರಿ - ದರ ಹೆಚ್ಚಾಗುವ ನಿರೀಕ್ಷೆ ಇದೆ',
    riskVerdict: 'ತಕ್ಷಣ ಮಾರಿ - ಹವಾಮಾನ ಅಥವಾ ಕೊಳೆಯುವ ಅಪಾಯ',
    netProfitTitle: 'ಕೈಗೆ ಸಿಗುವ ನೈಜ ನಿವ್ವಳ ಲಾಭ (Net Profit)',
    netProfitSubtitle: 'ಕೇವಲ ಮಾರುಕಟ್ಟೆ ದರ ನೋಡಬೇಡಿ! ಸಾರಿಗೆ ವೆಚ್ಚ ಕಳೆದು ಕೈಗೆ ಎಷ್ಟು ಹಣ ಉಳಿಯುತ್ತದೆ ಎಂದು ಹೋಲಿಸಿ.',
    yourHarvestQuantity: 'ಬೆಳೆಯ ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್)',
    chooseVehicle: 'ಸಾರಿಗೆ ವಾಹನ ಆಯ್ಕೆಮಾಡಿ',
    dieselTransportCost: 'ಅಂದಾಜು ಸಾರಿಗೆ ವೆಚ್ಚ',
    grossSale: 'ಒಟ್ಟು ಮಾರುಕಟ್ಟೆ ಮಾರಾಟ',
    actualNetCash: 'ಕೈಗೆ ಸಿಗುವ ನಿವ್ವಳ ಹಣ',
    bestProfitBadge: 'ಅತ್ಯುತ್ತಮ ಲಾಭದ ಮಾರುಕಟ್ಟೆ',
    extraCash: 'ಹೆಚ್ಚುವರಿ ನಗದು ಉಳಿತಾಯ',
    offlineBannerTitle: 'ಕಡಿಮೆ ಇಂಟರ್ನೆಟ್ ಅಥವಾ ಕೀಪ್ಯಾಡ್ ಫೋನ್?',
    sendSmsBtn: 'SMS ಮೂಲಕ ಮೊಬೈಲ್‌ಗೆ ದರ ಪಡೆಯಿರಿ',
    playAudioBtn: 'ಕನ್ನಡದಲ್ಲಿ ಆಡಿಯೋ ಸಲಹೆ ಕೇಳಿ',
    missedCallTitle: 'ಉಚಿತ ಮಿಸ್ಡ್ ಕಾಲ್ ಸೇವೆ',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ಯಾವುದೇ ಫೋನ್‌ನಿಂದ ಮಿಸ್ಡ್ ಕಾಲ್ ನೀಡಿ ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ದರಗಳನ್ನು ಆಲಿಸಿ',
    distance: 'ದೂರ',
    buyersToday: 'ವ್ಯಾಪಾರಿಗಳು',
    paymentInstant: 'ಪಾವತಿ',
    sevenDayTrend: '೭ ದಿನಗಳ ದರ ಪ್ರವೃತ್ತಿ ಮತ್ತು ಮುನ್ಸೂಚನೆ',
    today: 'ಇಂದು',
    keyFactors: 'ಈ ನಿರ್ಧಾರ ಏಕೆ?',
    weatherNotice: 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ',
    locationLabel: 'ರಾಜ್ಯ / ಸ್ಥಳ',
    changeLocation: 'ರಾಜ್ಯ ಬದಲಾಯಿಸಿ',
    detectLocation: 'GPS ನಿಂದ ಪತ್ತೆಹಚ್ಚಿ',
    detectedNotice: 'ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ತಕ್ಕಂತೆ ಕನ್ನಡ ಭಾಷೆ ಮತ್ತು ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ',
    searchPlaceholder: 'ಯಾವುದೇ ಬೆಳೆಯನ್ನು ಹುಡುಕಿ (ರಾಗಿ, ಭತ್ತ, ತೊಗರಿ, ಹತ್ತಿ, ಕಾಫಿ)...',
    allCrops: 'ಎಲ್ಲಾ ಬೆಳೆಗಳು',
    categoryCereals: 'ಧಾನ್ಯಗಳು ಮತ್ತು ಸಿರಿಧಾನ್ಯಗಳು',
    categoryPulses: 'ಕಾಳುಗಳು (ಬೇಳೆಕಾಳು)',
    categoryOilseeds: 'ಎಣ್ಣೆಕಾಳುಗಳು',
    categorySpices: 'ಮಸಾಲೆ ಬೆಳೆಗಳು',
    categoryVegetables: 'ತರಕಾರಿಗಳು',
    categoryCashCrops: 'ವಾಣಿಜ್ಯ ಬೆಳೆಗಳು',
    categoryFruits: 'ಹಣ್ಣುಗಳು ಮತ್ತು ತೋಟಗಾರಿಕೆ',
    sellBadge: 'ಇಂದೇ ಮಾರಿ',
    waitBadge: 'ಕಾಯಿರಿ',
    riskBadge: 'ಅಪಾಯ / ತಕ್ಷಣ ಮಾರಿ',
    selectedBadge: 'ಆಯ್ಕೆಯಾಗಿದೆ',
    selectCropBtn: 'ಆರಿಸಿ',
    resetFilters: 'ಫಿಲ್ಟರ್ ತೆರವು',
    filterOptions: 'ಆಯ್ಕೆಗಳು',
    cropSelectedBanner: 'ಆಯ್ಕೆಮಾಡಿದ ಬೆಳೆ',
    noCropsFound: 'ಯಾವುದೇ ಬೆಳೆ ಕಂಡುಬಂದಿಲ್ಲ',
    tryDifferentSearch: 'ಬೇರೆ ಹೆಸರು ಹುಡುಕಿ ಅಥವಾ ಫಿಲ್ಟರ್ ತೆರವುಗೊಳಿಸಿ',
    allSignals: 'ಎಲ್ಲಾ',
    proceedToDecision: '2. ಇಂದಿನ ನಿರ್ಧಾರ ➡️',
    backToCrops: '⬅️ 1. ಬೆಳೆ ಬದಲಾಯಿಸಿ',
    proceedToProfit: '3. ನಿವ್ವಳ ಲಾಭ ನೋಡಿ ➡️',
    backToDecision: '⬅️ 2. ಇಂದಿನ ನಿರ್ಧಾರ',
    proceedToWeather: '4. ಹವಾಮಾನ & ಸಂಗ್ರಹಣೆ ➡️',
    backToProfit: '⬅️ 3. ನಿವ್ವಳ ಲಾಭ',
    proceedToHelp: '5. ರೈತ ಸಹಾಯ ➡️',
    checkAnotherCrop: '1. ಇನ್ನೊಂದು ಬೆಳೆ ನೋಡಿ',
    voiceSearchBtn: 'ಮಾತನಾಡಿ ಹುಡುಕಿ',
    connectWithFarmersBtn: 'ರೈತರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ',
    poolTruckSubtitle: '10 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ವಾಹನ ಹಂಚಿಕೊಳ್ಳಿ',
    poolTruckloadBtn: 'ವಾಹನ ಹಂಚಿಕೊಳ್ಳಿ (ಪೂಲ್)',
    farmersPooledStatus: 'ರೈತರು ಜೊತೆಗೂಡಿದ್ದಾರೆ • ಹಂಚಿಕೆಯ ವಾಹನ',
    smallYieldBadge: '< 15 ಕ್ವಿಂಟಾಲ್',
    smallYieldAlert: 'ಕಡಿಮೆ ಇಳುವರಿ (< 15 ಕ್ವಿಂಟಾಲ್): ಒಬ್ಬರೇ ವಾಹನ ಮಾಡಿದರೆ 25-35% ಬಾಡಿಗೆಗೆ ಹೋಗುತ್ತದೆ. ಹತ್ತಿರದ ರೈತರೊಂದಿಗೆ ವಾಹನ ಹಂಚಿಕೊಂಡು ₹80-120/ಕ್ವಿಂಟಾಲ್ ಉಳಿಸಿ!',
    arrivalsLabel: 'ಆವಕ',
    volumeTrendLabel: 'ಆವಕ ಪ್ರವೃತ್ತಿ',
    sameStateMandiBanner: '≤ 100 ಕಿಮೀ ಮಾರುಕಟ್ಟೆಗಳು',
    kmAway: 'ಕಿಮೀ ದೂರ',
    transitCautionLabel: 'ಸಾರಿಗೆ ಎಚ್ಚರಿಕೆ',
    safeHoldingLabel: 'ಸುರಕ್ಷಿತ ಸಂಗ್ರಹಣಾ ಅವಧಿ',
    recommendedStorageLabel: 'ಶಿಫಾರಸು ಮಾಡಿದ ಸಂಗ್ರಹಣೆ',
    quintalsUnit: 'ಕ್ವಿಂಟಾಲ್',
    kgUnit: 'ಕೆಜಿ',
    costOfCultivationLabel: 'ಉತ್ಪಾದನಾ ವೆಚ್ಚ (₹/ಕ್ವಿಂಟಾಲ್)',
    calculateIndividualProfit: 'ವೈಯಕ್ತಿಕ ಲಾಭ ನೋಡಿ',
    calculatePooledProfit: 'ಸಾಮೂಹಿಕ ವಾಹನ ಲಾಭ ನೋಡಿ',
    editPoolBtn: 'ಪೂಲ್ ಬದಲಿಸಿ',
    bulkPoolingSavings: 'ಸಾಮೂಹಿಕ ವಾಹನ ಉಳಿತಾಯ',
    roundTrip: 'ಹೋಗಿ-ಬರಲು',
    activeTradersLabel: 'ಸಕ್ರಿಯ ವ್ಯಾಪಾರಿಗಳು',
    licensedTraders: 'ಪರವಾನಗಿ ಪಡೆದ',
    paymentLabel: 'ಪಾವತಿ',
    scientificStorageTitle: 'ವೈಜ್ಞಾನಿಕ ಸಂಗ್ರಹಣಾ ಮಾರ್ಗಸೂಚಿಗಳು',
    scientificStorageSubtitle: 'ಸುರಕ್ಷಿತ ಅವಧಿ, ತೇವಾಂಶ ಮಾನದಂಡ ಮತ್ತು ಸಾರಿಗೆ ಸುರಕ್ಷತೆ',
    hideGuidelines: 'ಮರೆಮಾಡಿ',
    viewGuidelines: 'ಮಾರ್ಗಸೂಚಿ ವೀಕ್ಷಿಸಿ',
    safeDurationLabel: 'ಸುರಕ್ಷಿತ ಅವಧಿ',
    moistureStandardLabel: 'ತೇವಾಂಶ ಮಾನದಂಡ',
    keyDirectivesLabel: 'ಪ್ರಮುಖ ನಿರ್ದೇಶನಗಳು',
    lowInternetBadge: 'ಕಡಿಮೆ ಇಂಟರ್ನೆಟ್ ಮತ್ತು ಕೀಪ್ಯಾಡ್ ಫೋನ್ ಸೌಲಭ್ಯ',
    shareWithKisanGroup: 'ರೈತ ಗುಂಪಿನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    smsPrefilledNotice: '✓ ಎಸ್ಎಂಎಸ್ ತೆರೆದಿದೆ. ದರ ಮತ್ತು ಸಲಹೆ ಸಿದ್ಧವಾಗಿದೆ!',
    kisanCallCenterTitle: 'ಕಿಸಾನ್ ಕಾಲ್ ಸೆಂಟರ್',
    kisanCallCenterDesc: 'ಕೃಷಿ ವಿಜ್ಞಾನಿಗಳೊಂದಿಗೆ 22 ಭಾಷೆಗಳಲ್ಲಿ ಮಾತನಾಡಿ. ಬೆಳಗ್ಗೆ 6 ರಿಂದ ರಾತ್ರಿ 10 ರವರೆಗೆ.',
    callFreeBtn: 'ಕರೆ ಮಾಡಿ 1800-180-1551 (ಉಚಿತ)',
    outdoorSunlightTitle: 'ಬಿಸಿಲು ಮೋಡ್',
    sunlightModeDesc: 'ಹೊಲದಲ್ಲಿ ಬಿಸಿಲಿನಲ್ಲಿ ಸುಲಭವಾಗಿ ಓದಲು ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್.',
    turnSunlightOn: 'ಬಿಸಿಲು ಮೋಡ್ ಆನ್ ಮಾಡಿ',
    turnSunlightOff: 'ಬಿಸಿಲು ಮೋಡ್ ಆನ್ ಆಗಿದೆ',
    languagesCountTitle: '13 ಭಾರತೀಯ ಭಾಷೆಗಳು',
    changeZoneBtn: 'ಬದಲಿಸಿ',
    zoneLabel: 'ವಲಯ',
    cloudSyncTitle: 'ರೈತ ಕ್ಲೌಡ್ ಸಿಂಕ್',
    signInBtn: 'ಸೈನ್ ಇನ್',
    onlineStatus: 'ಆನ್‌ಲೈನ್',
    pinCrop: 'ಪಿನ್ ಮಾಡಿ',
    pinnedCrop: 'ಪಿನ್ ಮಾಡಲಾಗಿದೆ',
    changeCropAction: 'ಬೆಳೆ ಬದಲಾಯಿಸಿ',
  },
  ml: {
    appName: 'മണ്ടി മിത്ര',
    tagline: 'കർഷകർക്കായി മികച്ച വിപണി വിലയും അറ്റാദായ വഴികാട്ടിയും',
    audioMode: 'ഉപദേശം കേൾക്കുക',
    audioPlaying: 'ഉപദേശം വായിക്കുന്നു...',
    stopAudio: 'ശബ്ദം നിർത്തുക',
    sunlightMode: 'വെയിൽ മോഡ്',
    selectCrop: 'വിള തിരഞ്ഞെടുക്കുക',
    selectCropSubtitle: 'ഇന്നത്തെ മാർക്കറ്റ് നിരക്കും കൃത്യമായ തീരുമാനവും കാണാൻ ക്ലിക്ക് ചെയ്യുക',
    voiceSearchPrompt: 'മൈക്ക് അമർത്തി വിളയുടെ പേര് പറയുക (ഉദാ: "കുരുമുളക്", "തേങ്ങ", "റബ്ബർ")',
    voiceSearchActive: 'ശ്രദ്ധിക്കുന്നു... വിളയുടെ പേര് പറയുക',
    decisionSignal: 'തീരുമാന സൂചിക (Decision Signal)',
    highestPriceToday: 'ഇന്നത്തെ ഏറ്റവും ഉയർന്ന വിപണി വില',
    perQuintal: 'ക്വിന്റലിന് (100 കിലോ)',
    sellTodayVerdict: 'ഇന്ന് തന്നെ വിൽക്കുക - നിരക്കുകൾ ഏറ്റവും ഉയർന്ന നിലയിൽ',
    waitVerdict: '2–3 ദിവസം കാത്തിരിക്കുക - വില ഉയരാൻ സാധ്യതയുണ്ട്',
    riskVerdict: 'ഉടൻ വിൽക്കുക - കാലാവസ്ഥ അല്ലെങ്കിൽ കേടുപാടുകൾ സാധ്യത',
    netProfitTitle: 'കൈയിൽ ലഭിക്കുന്ന അറ്റാദായം (Net Profit)',
    netProfitSubtitle: 'മാർക്കറ്റ് നിരക്ക് മാത്രം നോക്കരുത്! ഇന്ധന/വാഹന ചെലവ് കുറച്ചുള്ള യഥാർത്ഥ ലാഭം താരതമ്യം ചെയ്യുക.',
    yourHarvestQuantity: 'വിളവിന്റെ അളവ് (ക്വിന്റൽ)',
    chooseVehicle: 'വാഹനം തിരഞ്ഞെടുക്കുക',
    dieselTransportCost: 'ഗതാഗത ചെലവ്',
    grossSale: 'മൊത്തം മാർക്കറ്റ് വിൽപ്പന',
    actualNetCash: 'കൈയിൽ ലഭിക്കുന്ന അറ്റ പണം',
    bestProfitBadge: 'കൂടുതൽ ലാഭം നൽകുന്ന മാർക്കറ്റ്',
    extraCash: 'കൂടുതൽ ലാഭത്തുക',
    offlineBannerTitle: 'ഇന്റർനെറ്റ് കുറവോ സാധാരണ ബട്ടൺ ഫോണോ ആണോ?',
    sendSmsBtn: 'SMS വഴി വില മൊബൈലിൽ നേടൂ',
    playAudioBtn: 'മലയാളത്തിൽ ഉപദേശം കേൾക്കൂ',
    missedCallTitle: 'സൗജന്യ മിസ്ഡ് കോൾ സർവീസ്',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ഏത് ഫോണിൽ നിന്നും മിസ്ഡ് കോൾ ചെയ്ത് സ്വന്തം ഭാഷയിൽ മാർക്കറ്റ് വില അറിയാം',
    distance: 'ദൂരം',
    buyersToday: 'വ്യാപാരികൾ',
    paymentInstant: 'പണമിടപാട്',
    sevenDayTrend: '7 ദിവസത്തെ വില നിലവാരവും പ്രവചനവും',
    today: 'ഇന്ന്',
    keyFactors: 'എന്തുകൊണ്ട് ഈ തീരുമാനം?',
    weatherNotice: 'കാലാവസ്ഥ മുന്നറിയിപ്പ്',
    locationLabel: 'സംസ്ഥാനം / സ്ഥലം',
    changeLocation: 'മാറ്റുക',
    detectLocation: 'GPS വഴി കണ്ടെത്തുക',
    detectedNotice: 'താങ്കളുടെ പ്രദേശത്തിനനുസരിച്ച് മലയാളം ഭാഷയും പ്രാദേശിക മാർക്കറ്റുകളും ക്രമീകരിച്ചു',
    searchPlaceholder: 'വിളകൾ തിരയുക (കുരുമുളക്, തേങ്ങ, റബ്ബർ, ഇഞ്ചി, ചായ)...',
    allCrops: 'എല്ലാ വിളകളും',
    categoryCereals: 'ധാന്യങ്ങളും ചെറുധാന്യങ്ങളും',
    categoryPulses: 'പയറുവർഗ്ഗങ്ങൾ',
    categoryOilseeds: 'എണ്ണക്കുരുക്കൾ',
    categorySpices: 'സുഗന്ധവ്യഞ്ജനങ്ങൾ',
    categoryVegetables: 'പച്ചക്കറികൾ',
    categoryCashCrops: 'നാണ്യവിളകൾ',
    categoryFruits: 'പഴങ്ങളും തോട്ടവിളകളും',
    sellBadge: 'ഇന്ന് തന്നെ വിൽക്കൂ',
    waitBadge: 'കാത്തിരിക്കൂ',
    riskBadge: 'അപകടസാധ്യത / ഉടൻ വിൽക്കൂ',
    selectedBadge: 'തിരഞ്ഞെടുത്തു',
    selectCropBtn: 'തിരഞ്ഞെടുക്കൂ',
    resetFilters: 'ഫിൽട്ടർ മാറ്റൂ',
    filterOptions: 'ഓപ്ഷനുകൾ',
    cropSelectedBanner: 'തിരഞ്ഞെടുത്ത വിള',
    noCropsFound: 'വിളകളൊന്നും കണ്ടെത്തിയില്ല',
    tryDifferentSearch: 'മറ്റൊരു പേര് തിരയുക അല്ലെങ്കിൽ ഫിൽട്ടർ മാറ്റുക',
    allSignals: 'എല്ലാം',
    proceedToDecision: '2. ഇന്നത്തെ തീരുമാനം ➡️',
    backToCrops: '⬅️ 1. വിള മാറ്റുക',
    proceedToProfit: '3. ലാഭം കണക്കാക്കൂ ➡️',
    backToDecision: '⬅️ 2. ഇന്നത്തെ തീരുമാനം',
    proceedToWeather: '4. കാലാവസ്ഥയും സംഭരണവും ➡️',
    backToProfit: '⬅️ 3. ലാഭം',
    proceedToHelp: '5. കർഷക സഹായം ➡️',
    checkAnotherCrop: '1. മറ്റൊരു വിള നോക്കുക',
    voiceSearchBtn: 'സംസാരിച്ച് തിരയുക',
    connectWithFarmersBtn: 'കർഷകരുമായി ബന്ധപ്പെടുക',
    poolTruckSubtitle: '10 കി.മീറ്ററിനുള്ളിൽ വാഹനം പങ്കിടുക',
    poolTruckloadBtn: 'വാഹനം പങ്കിടുക (പൂൾ)',
    farmersPooledStatus: 'കർഷകർ ഒത്തുചേർന്നു • സംയുക്ത വാഹനം',
    smallYieldBadge: '< 15 ക്വിന്റൽ',
    smallYieldAlert: 'കുറഞ്ഞ വിളവ് (< 15 ക്വിന്റൽ): സ്വന്തമായി വാഹനം വിളിച്ചാൽ 25-35% കൂലി പോകും. സമീപ കർഷകരുമായി വാഹനം പങ്ക് വെച്ച് ₹80-120/ക്വിന്റൽ ലാഭിക്കൂ!',
    arrivalsLabel: 'വരവ്',
    volumeTrendLabel: 'വരവ് പ്രവണത',
    sameStateMandiBanner: '≤ 100 കി.മീ മാർക്കറ്റുകൾ',
    kmAway: 'കി.മീ അകലെ',
    transitCautionLabel: 'യാത്രാ മുൻകരുതൽ',
    safeHoldingLabel: 'സുരക്ഷിത സംഭരണ കാലാവധി',
    recommendedStorageLabel: 'ശുപാർശ ചെയ്ത സംഭരണം',
    quintalsUnit: 'ക്വിന്റൽ',
    kgUnit: 'കിലോ',
    costOfCultivationLabel: 'ഉൽപ്പാദനച്ചെലവ് (₹/ക്വിന്റൽ)',
    calculateIndividualProfit: 'വ്യക്തിഗത ലാഭം കാണുക',
    calculatePooledProfit: 'കൂട്ടായ ലാഭം കാണുക',
    editPoolBtn: 'പൂൾ മാറ്റുക',
    bulkPoolingSavings: 'കൂട്ടായ വാഹന ലാഭം',
    roundTrip: 'പോയി-വരാൻ',
    activeTradersLabel: 'വ്യാപാരികൾ',
    licensedTraders: 'ലൈസൻസുള്ള',
    paymentLabel: 'പേയ്മെന്റ്',
    scientificStorageTitle: 'ശാസ്ത്രീയ സംഭരണ മാർഗ്ഗനിർദ്ദേശങ്ങൾ',
    scientificStorageSubtitle: 'സുരക്ഷിത കാലാവധി, ഈർപ്പത്തിന്റെ അളവ്, ഗതാഗത സുരക്ഷ',
    hideGuidelines: 'മറയ്ക്കുക',
    viewGuidelines: 'മാർഗ്ഗനിർദ്ദേശം കാണുക',
    safeDurationLabel: 'സുരക്ഷിത കാലാവധി',
    moistureStandardLabel: 'ഈർപ്പത്തിന്റെ അളവ്',
    keyDirectivesLabel: 'പ്രധാന നിർദ്ദേശങ്ങൾ',
    lowInternetBadge: 'കുറഞ്ഞ ഇന്റർനെറ്റ് & കീപാഡ് ഫോൺ സൗകര്യം',
    shareWithKisanGroup: 'കർഷക ഗ്രൂപ്പിൽ പങ്കിടുക',
    smsPrefilledNotice: '✓ എസ്എംഎസ് തുറന്നു. നിരക്കും ഉപദേശവും തയ്യാറാണ്!',
    kisanCallCenterTitle: 'കിസാൻ കോൾ സെന്റർ',
    kisanCallCenterDesc: 'കാർഷിക ശാസ്ത്രജ്ഞരുമായി 22 ഭാഷകളിൽ സംസാരിക്കുക. രാവിലെ 6 മുതൽ രാത്രി 10 വരെ.',
    callFreeBtn: 'വിളിക്കുക 1800-180-1551 (ടോൾ ഫ്രീ)',
    outdoorSunlightTitle: 'സൂര്യപ്രകാശ മോഡ്',
    sunlightModeDesc: 'പാടത്ത് വെയിലത്ത് വ്യക്തമായി വായിക്കാൻ ഉയർന്ന കോൺട്രാസ്റ്റ്.',
    turnSunlightOn: 'വെയിൽ മോഡ് ഓണാക്കുക',
    turnSunlightOff: 'വെയിൽ മോഡ് ഓണാണ്',
    languagesCountTitle: '13 ഇന്ത്യൻ ഭാഷകൾ',
    changeZoneBtn: 'മാറ്റുക',
    zoneLabel: 'മേഖല',
    cloudSyncTitle: 'കർഷക ക്ലൗഡ് സമന്വയം',
    signInBtn: 'സൈൻ ഇൻ',
    onlineStatus: 'ഓൺലൈൻ',
    pinCrop: 'പിൻ ചെയ്യുക',
    pinnedCrop: 'പിൻ ചെയ്തു',
    changeCropAction: 'വിള മാറ്റുക',
  },
  or: {
    appName: 'ମଣ୍ଡି ମିତ୍ର',
    tagline: 'କୃଷକମାନଙ୍କ ପାଇଁ ସ୍ମାର୍ଟ ଫସଲ ଦର ଏବଂ ନିଟ୍ ଲାଭ ପରାମର୍ଶ',
    audioMode: 'ପରାମର୍ଶ ଶୁଣନ୍ତୁ',
    audioPlaying: 'ପରାମର୍ଶ ପଢ଼ାଯାଉଛି...',
    stopAudio: 'ବନ୍ଦ କରନ୍ତୁ',
    sunlightMode: 'ଖରା ମୋଡ୍',
    selectCrop: 'ନିଜର ଫସଲ ବାଛନ୍ତୁ',
    selectCropSubtitle: 'ଆଜିର ମଣ୍ଡି ଦର ଏବଂ ଠିକ୍ ନିଷ୍ପତ୍ତି ପାଇଁ ଫସଲ ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ',
    voiceSearchPrompt: 'ମାଇକ୍ ଦବାଇ ଫସଲର ନାମ କୁହନ୍ତୁ (ଯେପରି "ଧାନ", "ହଳଦୀ", "ଚିନାବାଦାମ")',
    voiceSearchActive: 'ଶୁଣୁଛୁ... ଫସଲର ନାମ କୁହନ୍ତୁ',
    decisionSignal: 'ନିଷ୍ପତ୍ତି ସଙ୍କେତ (Decision Signal)',
    highestPriceToday: 'ଆଜିର ସର୍ବୋଚ୍ଚ ମଣ୍ଡି ଦର',
    perQuintal: 'କ୍ୱିଣ୍ଟାଲ୍ ପିଛା (୧୦୦ କିଲୋ)',
    sellTodayVerdict: 'ଆଜି ହିଁ ବିକ୍ରି କରନ୍ତୁ - ଦର ସର୍ବୋଚ୍ଚ ସ୍ତରରେ ଅଛି',
    waitVerdict: '୨–୩ ଦିନ ଅପେକ୍ଷା କରନ୍ତୁ - ଦର ବଢ଼ିବାର ସମ୍ଭାବନା ଅଛି',
    riskVerdict: 'ତୁରନ୍ତ ବିକ୍ରି କରନ୍ତୁ - ପାଣିପାଗ ଖରାପ କିମ୍ବା ନଷ୍ଟ ହେବାର ଆଶଙ୍କା',
    netProfitTitle: 'ହାତକୁ ଆସୁଥିବା ଅସଲି ନିଟ୍ ଲାଭ (Net Profit)',
    netProfitSubtitle: 'କେବଳ ମଣ୍ଡି ଦର ଦେଖନ୍ତୁ ନାହିଁ! ଗାଡ଼ି ଭଡ଼ା ଓ ଡିଜେଲ ଖର୍ଚ୍ଚ କାଟି ହାତରେ କେତେ ରହିବ ତାହା ଯାଞ୍ଚ କରନ୍ତୁ।',
    yourHarvestQuantity: 'ଫସଲର ପରିମାଣ (କ୍ୱିଣ୍ଟାଲ୍)',
    chooseVehicle: 'ପରିବହନ ଗାଡ଼ି ବାଛନ୍ତୁ',
    dieselTransportCost: 'ଆନୁମାନିକ ପରିବହନ ଖର୍ଚ୍ଚ',
    grossSale: 'ମୋଟ ମଣ୍ଡି ବିକ୍ରୟ',
    actualNetCash: 'ହାତରେ ନଗଦ ଅସଲି ଟଙ୍କା',
    bestProfitBadge: 'ସର୍ବାଧିକ ଲାଭର ମଣ୍ଡି',
    extraCash: 'ଅତିରିକ୍ତ ଲାଭ',
    offlineBannerTitle: 'ଧୀମା ଇଣ୍ଟରନେଟ୍ କିମ୍ବା ସାଧା କିପ୍ୟାଡ୍ ଫୋନ୍?',
    sendSmsBtn: 'SMS ଦ୍ୱାରା ଫୋନକୁ ଦର ମଗାନ୍ତୁ',
    playAudioBtn: 'ଓଡ଼ିଆରେ ଅଡିଓ ପରାମର୍ଶ ଶୁଣନ୍ତୁ',
    missedCallTitle: 'ମାଗଣା ମିସଡ୍ କଲ୍ ସେବା',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ଯେକୌଣସି ଫୋନରୁ ମିସଡ୍ କଲ୍ ଦିଅନ୍ତୁ ଏବଂ ନିଜ ଭାଷାରେ ଦର ଶୁଣନ୍ତୁ',
    distance: 'ଦୂରତା',
    buyersToday: 'ବ୍ୟବସାୟୀ',
    paymentInstant: 'ଟଙ୍କା ପୈଠ',
    sevenDayTrend: '୭-ଦିନର ଦର ଟ୍ରେଣ୍ଡ୍ ଓ ପୂର୍ବାନୁମାନ',
    today: 'ଆଜି',
    keyFactors: 'ଏହି ନିଷ୍ପତ୍ତି କାହିଁକି?',
    weatherNotice: 'ପାଣିପାଗ ସତର୍କତା',
    locationLabel: 'ରାଜ୍ୟ / ସ୍ଥାନ',
    changeLocation: 'ରାଜ୍ୟ ବଦଳାନ୍ତୁ',
    detectLocation: 'GPS ମାଧ୍ୟମରେ ଖୋଜନ୍ତୁ',
    detectedNotice: 'ଆପଣଙ୍କ ଅଞ୍ଚଳ ଅନୁସାରେ ଓଡ଼ିଆ ଭାଷା ଏବଂ ସ୍ଥାନୀୟ ମଣ୍ଡି ଚୟନ କରାଯାଇଛି',
    searchPlaceholder: 'ଯେକୌଣସି ଫସଲ ଖୋଜନ୍ତୁ (ଧାନ, ହଳଦୀ, ଚିନାବାଦାମ, ମୁଗ)...',
    allCrops: 'ସମସ୍ତ ଫସଲ',
    categoryCereals: 'ଶସ୍ୟ ଓ ମିଲେଟ୍ସ',
    categoryPulses: 'ଡାଲି ଜାତୀୟ',
    categoryOilseeds: 'ତୈଳବୀଜ',
    categorySpices: 'ମସଲା',
    categoryVegetables: 'ପନିପରିବା',
    categoryCashCrops: 'ଅର୍ଥକରୀ ଫସଲ',
    categoryFruits: 'ଫଳ ଓ ବଗିଚା',
    sellBadge: 'ଆଜି ହିଁ ବିକ୍ରି କରନ୍ତୁ',
    waitBadge: 'ଅପେକ୍ଷା କରନ୍ତୁ',
    riskBadge: 'ବିପଦ / ଶୀଘ୍ର ବିକ୍ରି କରନ୍ତୁ',
    selectedBadge: 'ମନୋନୀତ',
    selectCropBtn: 'ଚୟନ କରନ୍ତୁ',
    resetFilters: 'ଫିଲ୍ଟର୍ ହଟାନ୍ତୁ',
    filterOptions: 'ବିକଳ୍ପ',
    cropSelectedBanner: 'ମନୋନୀତ ଫସଲ',
    noCropsFound: 'କୌଣସି ଫସଲ ମିଳିଲା ନାହିଁ',
    tryDifferentSearch: 'ଅନ୍ୟ ନାମ ଖୋଜନ୍ତୁ କିମ୍ବା ଫିଲ୍ଟର୍ ସଫା କରନ୍ତୁ',
    allSignals: 'ସବୁ',
    proceedToDecision: '2. ଆଜିର ନିଷ୍ପତ୍ତି ➡️',
    backToCrops: '⬅️ 1. ଫସଲ ପରିବର୍ତ୍ତନ',
    proceedToProfit: '3. ନିଟ୍ ଲାଭ ଦେଖନ୍ତୁ ➡️',
    backToDecision: '⬅️ 2. ଆଜିର ନିଷ୍ପତ୍ତି',
    proceedToWeather: '4. ପାଣିପାଗ ଓ ସଂରକ୍ଷଣ ➡️',
    backToProfit: '⬅️ 3. ନିଟ୍ ଲାଭ',
    proceedToHelp: '5. କୃଷକ ସହାୟତା ➡️',
    checkAnotherCrop: '1. ଅନ୍ୟ ଫସଲ ଯାଞ୍ଚ କରନ୍ତୁ',
    voiceSearchBtn: 'କହିକି ଖୋଜନ୍ତୁ',
    connectWithFarmersBtn: 'କୃଷକଙ୍କ ସହ ଯୋଡ଼ି ହୁଅନ୍ତୁ',
    poolTruckSubtitle: '୧୦ କିମି ମଧ୍ୟରେ ଗାଡ଼ି ଭାଗ କରନ୍ତୁ',
    poolTruckloadBtn: 'ଗାଡ଼ି ଭାଗ କରନ୍ତୁ (ପୁଲ)',
    farmersPooledStatus: 'କୃଷକ ଯୋଡ଼ି ହେଲେ • ମିଳିତ ଗାଡ଼ି',
    smallYieldBadge: '< ୧୫ କ୍ୱିଣ୍ଟାଲ',
    smallYieldAlert: 'କମ୍ ଅମଳ (< ୧୫ କ୍ୱିଣ୍ଟାଲ): ଏକୁଟିଆ ଗାଡ଼ି କଲେ ୨୫-୩୫% ଭଡ଼ା ଯିବ। ପାଖ କୃଷକଙ୍କ ସହ ଗାଡ଼ି ଭାଗ କରି ₹୮୦-୧୨୦/କ୍ୱିଣ୍ଟାଲ ବଞ୍ଚାନ୍ତୁ!',
    arrivalsLabel: 'ଆମଦାନୀ',
    volumeTrendLabel: 'ଆମଦାନୀ ଧାରା',
    sameStateMandiBanner: '≤ ୧୦୦ କିମି ସ୍ଥାନୀୟ ମଣ୍ଡି',
    kmAway: 'କିମି ଦୂର',
    transitCautionLabel: 'ପରିବହନ ସାବଧାନତା',
    safeHoldingLabel: 'ସୁରକ୍ଷିତ ସଂରକ୍ଷଣ ଅବଧି',
    recommendedStorageLabel: 'ପରାମର୍ଶିତ ସଂରକ୍ଷଣ',
    quintalsUnit: 'କ୍ୱିଣ୍ଟାଲ',
    kgUnit: 'କେଜି',
    costOfCultivationLabel: 'ଉତ୍ପାଦନ ଖର୍ଚ୍ଚ (₹/କ୍ୱିଣ୍ଟାଲ)',
    calculateIndividualProfit: 'ବ୍ୟକ୍ତିଗତ ଲାଭ ଦେଖନ୍ତୁ',
    calculatePooledProfit: 'ମିଳିତ ଗାଡ଼ିର ଲାଭ ଦେଖନ୍ତୁ',
    editPoolBtn: 'ପୁଲ ପରିବର୍ତ୍ତନ',
    bulkPoolingSavings: 'ମିଳିତ ଗାଡ଼ି ସଞ୍ଚୟ',
    roundTrip: 'ଯିବା-ଆସିବା',
    activeTradersLabel: 'ସକ୍ରିୟ ବ୍ୟବସାୟୀ',
    licensedTraders: 'ଲାଇସେନ୍ସପ୍ରାପ୍ତ',
    paymentLabel: 'ପେମେଣ୍ଟ',
    scientificStorageTitle: 'ବୈଜ୍ଞାନିକ ସଂରକ୍ଷଣ ନିର୍ଦ୍ଦେଶାବଳୀ',
    scientificStorageSubtitle: 'ସୁରକ୍ଷିତ ଅବଧି, ଆର୍ଦ୍ରତା ମାନ ଓ ପରିବହନ ସୁରକ୍ଷା',
    hideGuidelines: 'ଲୁଚାନ୍ତୁ',
    viewGuidelines: 'ନିର୍ଦ୍ଦେଶାବଳୀ ଦେଖନ୍ତୁ',
    safeDurationLabel: 'ସୁରକ୍ଷିତ ଅବଧି',
    moistureStandardLabel: 'ଆର୍ଦ୍ରତା ମାନ',
    keyDirectivesLabel: 'ମୁଖ୍ୟ ନିର୍ଦ୍ଦେଶାବଳୀ',
    lowInternetBadge: 'ଧୀମା ଇଣ୍ଟରନେଟ୍ ଓ ସାଧା ଫୋନ୍ ସୁବିଧା',
    shareWithKisanGroup: 'କୃଷକ ଗ୍ରୁପରେ ସେୟାର କରନ୍ତୁ',
    smsPrefilledNotice: '✓ ଏସଏମଏସ ଖୋଲିଗଲା। ଦର ଓ ପରାମର୍ଶ ପ୍ରସ୍ତୁତ!',
    kisanCallCenterTitle: 'କିଷାନ କଲ୍ ସେଣ୍ଟର',
    kisanCallCenterDesc: 'କୃଷି ବୈଜ୍ଞାନିକଙ୍କ ସହ ୨୨ଟି ଭାଷାରେ କଥା ହୁଅନ୍ତୁ। ସକାଳ ୬ରୁ ରାତି ୧୦ ପର୍ଯ୍ୟନ୍ତ।',
    callFreeBtn: 'କଲ୍ କରନ୍ତୁ 1800-180-1551 (ମାଗଣା)',
    outdoorSunlightTitle: 'ଖରା ମୋଡ୍ (Sunlight Mode)',
    sunlightModeDesc: 'ବିଲରେ ଖରାରେ ସହଜରେ ପଢ଼ିବା ପାଇଁ ଡାର୍କ କଣ୍ଟ୍ରାଷ୍ଟ।',
    turnSunlightOn: 'ଖରା ମୋଡ୍ ଅନ୍ କରନ୍ତୁ',
    turnSunlightOff: 'ଖରା ମୋଡ୍ ଅନ୍ ଅଛି',
    languagesCountTitle: '୧୩ଟି ଭାରତୀୟ ଭାଷା',
    changeZoneBtn: 'ପରିବର୍ତ୍ତନ',
    zoneLabel: 'ଅଞ୍ଚଳ',
    cloudSyncTitle: 'କୃଷକ କ୍ଲାଉଡ୍ ସିଙ୍କ୍',
    signInBtn: 'ସାଇନ୍ ଇନ୍',
    onlineStatus: 'ଅନଲାଇନ୍',
    pinCrop: 'ପିନ୍ କରନ୍ତୁ',
    pinnedCrop: 'ପିନ୍ ହୋଇଛି',
    changeCropAction: 'ଫସଲ ପରିବର୍ତ୍ତନ',
  },
  as: {
    appName: 'মন্ডি মিত্ৰ',
    tagline: 'কৃষকসকলৰ বাবে স্মাৰ্ট ফচলৰ বজাৰদৰ আৰু প্ৰকৃত লাভৰ পৰামৰ্শ',
    audioMode: 'পৰামৰ্শ শুনক',
    audioPlaying: 'পৰামৰ্শ পঢ়ি থকা হৈছে...',
    stopAudio: 'শব্দ বন্ধ কৰক',
    sunlightMode: 'ৰ’দ মোড',
    selectCrop: 'আপোনাৰ ফচল বাছক',
    selectCropSubtitle: 'আজিৰ বজাৰদৰ আৰু সঠিক সিদ্ধান্ত জানিবলৈ ফচলত ক্লিক কৰক',
    voiceSearchPrompt: 'মাইক টিপি ফচলৰ নাম কওক (যেনে "ধান", "চাহ", "মৰাপাট")',
    voiceSearchActive: 'শুনি আছোঁ... ফচলৰ নাম কওক',
    decisionSignal: 'সিদ্ধান্ত সংকেত (Decision Signal)',
    highestPriceToday: 'আজিৰ সৰ্বোচ্চ বজাৰদৰ',
    perQuintal: 'প্ৰতি কুইন্টলত (১০০ কেজি)',
    sellTodayVerdict: 'আজিয়েই বিক্ৰী কৰক - বজাৰদৰ শীৰ্ষত আছে',
    waitVerdict: '২–৩ দিন অপেক্ষা কৰক - দৰ বৃদ্ধি পোৱাৰ সম্ভাৱনা',
    riskVerdict: 'ততালিকে বিক্ৰী কৰক - বতৰ বা নষ্ট হোৱাৰ সম্ভাৱনা',
    netProfitTitle: 'হাতলৈ অহা প্ৰকৃত লাভ (Net Profit)',
    netProfitSubtitle: 'কেৱল বজাৰদৰ নাচাব! পৰিবহণ আৰু ইন্ধন খৰচ বাদ দি হাতত কিমান ৰব তুলনা কৰক।',
    yourHarvestQuantity: 'ফচলৰ পৰিমাণ (কুইন্টল)',
    chooseVehicle: 'পৰিবহণ বাহন বাছক',
    dieselTransportCost: 'আনুমানিক পৰিবহণ খৰচ',
    grossSale: 'মুঠ বজাৰ বিক্ৰী',
    actualNetCash: 'হাতত নগদ ধন',
    bestProfitBadge: 'সৰ্বাধিক লাভৰ বজাৰ',
    extraCash: 'অতিৰিক্ত লাভ',
    offlineBannerTitle: 'লেহেমীয়া ইণ্টাৰনেট বা সাধাৰণ বটন ফোন?',
    sendSmsBtn: 'SMS যোগে মোবাইললৈ দৰ আনক',
    playAudioBtn: 'অসমীয়াত অডিঅ’ পৰামৰ্শ শুনক',
    missedCallTitle: 'বিনামূলীয়া মিছড কল সেৱা',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'যিকোনো ফোনৰ পৰা মিছড কল দি নিজৰ ভাষাত বজাৰদৰ শুনক',
    distance: 'দূৰত্ব',
    buyersToday: 'ব্যৱসায়ীসকল',
    paymentInstant: 'পেমেন্ট',
    sevenDayTrend: '৭-দিনীয়া দৰৰ গতি আৰু পূৰ্বানুমান',
    today: 'আজি',
    keyFactors: 'এই সিদ্ধান্ত কিয়?',
    weatherNotice: 'বতৰৰ সতৰ্কবাৰ্তা',
    locationLabel: 'ৰাজ্য / স্থান',
    changeLocation: 'ৰাজ্য সলনি কৰক',
    detectLocation: 'GPS ৰে সন্ধান কৰক',
    detectedNotice: 'আপোনাৰ স্থান অনুসৰি অসমীয়া ভাষা আৰু স্থানীয় বজাৰ নিৰ্বাচিত হৈছে',
    searchPlaceholder: 'যিকোনো ফচল বিচাৰক (ধান, চাহ পাত, মৰাপাট, সৰিয়হ, আদা)...',
    allCrops: 'সকলো ফচল',
    categoryCereals: 'শস্য আৰু মিলেট',
    categoryPulses: 'দাইল জাতীয়',
    categoryOilseeds: 'তেলবীজ',
    categorySpices: 'মছলা',
    categoryVegetables: 'শাক-পাচলি',
    categoryCashCrops: 'নগদ ফচল',
    categoryFruits: 'ফল-মূল আৰু বাগিচা',
    sellBadge: 'আজিই বিক্ৰী কৰক',
    waitBadge: 'অপেক্ষা কৰক',
    riskBadge: 'বিপদ / সোনকালে বিক্ৰী কৰক',
    selectedBadge: 'নিৰ্বাচিত',
    selectCropBtn: 'বাছনি কৰক',
    resetFilters: 'ফিল্টাৰ আতঁৰাওক',
    filterOptions: 'বিকল্প',
    cropSelectedBanner: 'নিৰ্বাচিত শস্য',
    noCropsFound: 'কোনো শস্য পোৱা নগল',
    tryDifferentSearch: 'অন্য নাম সন্ধান কৰক বা ফিল্টাৰ পৰিষ্কাৰ কৰক',
    allSignals: 'সকলো',
    proceedToDecision: '2. আজিৰ সিদ্ধান্ত ➡️',
    backToCrops: '⬅️ 1. শস্য সলনি কৰক',
    proceedToProfit: '3. নিগুট লাভ চাওক ➡️',
    backToDecision: '⬅️ 2. আজিৰ সিদ্ধান্ত',
    proceedToWeather: '4. বতৰ আৰু সংৰক্ষণ ➡️',
    backToProfit: '⬅️ 3. নিগুট লাভ',
    proceedToHelp: '5. কৃষক সাহায্য ➡️',
    checkAnotherCrop: '1. অন্য শস্য পৰীক্ষা কৰক',
    voiceSearchBtn: 'কৈ সন্ধান কৰক',
    connectWithFarmersBtn: 'কৃষকসকলৰ সৈতে সংযোগ কৰক',
    poolTruckSubtitle: '১০ কিমিৰ ভিতৰত গাড়ী ভাগ কৰক',
    poolTruckloadBtn: 'গাড়ী ভাগ কৰক (পুল)',
    farmersPooledStatus: 'কৃষক সংযুক্ত • যুটীয়া গাড়ী',
    smallYieldBadge: '< ১৫ কুইণ্টল',
    smallYieldAlert: 'কম উৎপাদন (< ১৫ কুইণ্টল): অকলে গাড়ী কৰিলে ২৫-৩৫% ভাড়া যাব। ওচৰৰ কৃষকৰ সৈতে গাড়ী ভগাই ₹৮০-১২০/কুইণ্টল ৰাহি কৰক!',
    arrivalsLabel: 'আমদানি',
    volumeTrendLabel: 'আমদানি ধাৰা',
    sameStateMandiBanner: '≤ ১০০ কিমি স্থানীয় বজাৰ',
    kmAway: 'কিমি দূৰৈত',
    transitCautionLabel: 'পৰিবহণ সাৱধানতা',
    safeHoldingLabel: 'সুৰক্ষিত সংৰক্ষণ সময়',
    recommendedStorageLabel: 'পৰামৰ্শিত সংৰক্ষণ',
    quintalsUnit: 'কুইণ্টল',
    kgUnit: 'কেজি',
    costOfCultivationLabel: 'উৎপাদন খৰচ (₹/কুইণ্টল)',
    calculateIndividualProfit: 'ব্যক্তিগত লাভ চাওক',
    calculatePooledProfit: 'যুটীয়া গাড়ীৰ লাভ চাওক',
    editPoolBtn: 'পুল সলনি',
    bulkPoolingSavings: 'যুটীয়া গাড়ী ৰাহি',
    roundTrip: 'যোৱা-অহা',
    activeTradersLabel: 'সক্ৰিয় ব্যৱসায়ী',
    licensedTraders: 'অনুজ্ঞাপত্ৰপ্ৰাপ্ত',
    paymentLabel: 'পৰিশোধ',
    scientificStorageTitle: 'বৈজ্ঞানিক সংৰক্ষণ নিৰ্দেশাৱলী',
    scientificStorageSubtitle: 'সুৰক্ষিত সময়, আৰ্দ্ৰতাৰ মান আৰু পৰিবহণ সুৰক্ষা',
    hideGuidelines: 'লুকুৱাওক',
    viewGuidelines: 'নিৰ্দেশনা চাওক',
    safeDurationLabel: 'সুৰক্ষিত সময়',
    moistureStandardLabel: 'আৰ্দ্ৰতাৰ মান',
    keyDirectivesLabel: 'মুখ্য নিৰ্দেশনা',
    lowInternetBadge: 'লেহেমীয়া ইণ্টাৰনেট আৰু বুটাম ফোনৰ সুবিধা',
    shareWithKisanGroup: 'কৃষক গোটত শ্বেয়াৰ কৰক',
    smsPrefilledNotice: '✓ এছএমএছ খোল খালে। দৰ আৰু পৰামৰ্শ প্ৰস্তুত!',
    kisanCallCenterTitle: 'কিষাণ কল চেণ্টাৰ',
    kisanCallCenterDesc: 'কৃষি বিজ্ঞানীসকলৰ সৈতে ২২ টা ভাষাত কথা পাতক। পুৱা ৬ বজাৰ পৰা নিশা ১০ বজালৈ।',
    callFreeBtn: 'কল কৰক 1800-180-1551 (বিনামূলীয়া)',
    outdoorSunlightTitle: 'ৰ’দ মোড',
    sunlightModeDesc: 'পথাৰত ৰ’দত পঢ়িবলৈ গাঢ় কণ্ট্ৰাষ্ট।',
    turnSunlightOn: 'ৰ’দ মোড অন কৰক',
    turnSunlightOff: 'ৰ’দ মোড অন আছে',
    languagesCountTitle: '১৩ টা ভাৰতীয় ভাষা',
    changeZoneBtn: 'সলনি কৰক',
    zoneLabel: 'অঞ্চল',
    cloudSyncTitle: 'কৃষক ক্লাউড সংমিশ্ৰণ',
    signInBtn: 'ছাইন ইন',
    onlineStatus: 'অনলাইন',
    pinCrop: 'পিন কৰক',
    pinnedCrop: 'পিন কৰা হৈছে',
    changeCropAction: 'শস্য সলনি কৰক',
  },
  ur: {
    appName: 'منڈی متر',
    tagline: 'کسانوں کے لیے اسمارٹ فصل ریٹ اور خالص منافع کا نظام',
    audioMode: 'مشورہ سنیں',
    audioPlaying: 'مشورہ پڑھا جا رہا ہے...',
    stopAudio: 'آواز بند کریں',
    sunlightMode: 'دھوپ موڈ',
    selectCrop: 'اپنی فصل منتخب کریں',
    selectCropSubtitle: 'آج کے منڈی ریٹ اور درست فیصلے کے لیے فصل پر کلک کریں',
    voiceSearchPrompt: 'مائک دبا کر فصل کا نام بولیں (جیسے "سیب", "گیہوں", "کپاس")',
    voiceSearchActive: 'سن رہے ہیں... فصل کا نام بولیں',
    decisionSignal: 'فیصلہ کا اشارہ (Decision Signal)',
    highestPriceToday: 'آج کا سب سے اونچا منڈی ریٹ',
    perQuintal: 'فی کوئنٹل (100 کلو)',
    sellTodayVerdict: 'آج ہی فروخت کریں - منڈی ریٹ عروج پر ہیں',
    waitVerdict: '2–3 دن رکیں - ریٹ بڑھنے کا امکان ہے',
    riskVerdict: 'فوری فروخت کریں - خراب موسم یا خراب ہونے کا خطرہ',
    netProfitTitle: 'ہاتھ میں آنے والا اصل خالص منافع (Net Profit)',
    netProfitSubtitle: 'صرف منڈی کا ریٹ نہ دیکھیں! کرایہ اور ایندھن کا خرچ نکال کر اصل بچت دیکھیں۔',
    yourHarvestQuantity: 'فصل کی مقدار (کوئنٹل)',
    chooseVehicle: 'ٹرانسپورٹ گاڑی منتخب کریں',
    dieselTransportCost: 'گاڑی / ڈیزل کا تخمینہ خرچ',
    grossSale: 'کل منڈی فروخت',
    actualNetCash: 'ہاتھ میں خالص رقم',
    bestProfitBadge: 'سب سے زیادہ منافع کی منڈی',
    extraCash: 'اضافی نقد بچت',
    offlineBannerTitle: 'سست انٹرنیٹ یا سادہ کی پیڈ فون؟',
    sendSmsBtn: 'SMS سے ریٹ منگوائیں',
    playAudioBtn: 'اردو میں آڈیو مشورہ سنیں',
    missedCallTitle: 'مفت مسڈ کال سروس',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'کسی بھی فون سے مسڈ کال دیں اور اپنی زبان میں تازہ ترین منڈی ریٹ سنیں',
    distance: 'فاصلہ',
    buyersToday: 'خریدار تاجر',
    paymentInstant: 'ادائیگی',
    sevenDayTrend: '7 دن کا ریٹ گراف اور پیشین گوئی',
    today: 'آج',
    keyFactors: 'یہ فیصلہ کیوں؟',
    weatherNotice: 'موسم کی وارننگ',
    locationLabel: 'ریاست / مقام',
    changeLocation: 'ریاست تبدیل کریں',
    detectLocation: 'GPS سے تلاش کریں',
    detectedNotice: 'آپ کے مقام کے مطابق اردو زبان اور منڈیاں منتخب کی گئی ہیں',
    searchPlaceholder: 'فصل تلاش کریں (سیب, گیہوں, دھان, کپاس, پیاز)...',
    allCrops: 'تمام فصلیں',
    categoryCereals: 'اناج اور باجرہ',
    categoryPulses: 'دالیں',
    categoryOilseeds: 'تیل کے بیج',
    categorySpices: 'مصالحہ جات',
    categoryVegetables: 'سبزیاں',
    categoryCashCrops: 'نقد آور فصلیں',
    categoryFruits: 'پھل اور باغات',
    sellBadge: 'آج ہی بیچیں',
    waitBadge: 'انتظار کریں',
    riskBadge: 'خطرہ / فوراً بیچیں',
    selectedBadge: 'منتخب شدہ',
    selectCropBtn: 'منتخب کریں',
    resetFilters: 'فلٹرز صاف کریں',
    filterOptions: 'آپشنز',
    cropSelectedBanner: 'منتخب کردہ فصل',
    noCropsFound: 'کوئی فصل نہیں ملی',
    tryDifferentSearch: 'دوسرا نام تلاش کریں یا فلٹر صاف کریں',
    allSignals: 'سب',
    proceedToDecision: '2. آج کا فیصلہ ➡️',
    backToCrops: '⬅️ 1. فصل تبدیل کریں',
    proceedToProfit: '3. منڈی منافع دیکھیں ➡️',
    backToDecision: '⬅️ 2. آج کا فیصلہ',
    proceedToWeather: '4. موسم اور اسٹوریج ➡️',
    backToProfit: '⬅️ 3. منڈی منافع',
    proceedToHelp: '5. کسان ہیلپ لائن ➡️',
    checkAnotherCrop: '1. دوسری فصل چیک کریں',
    voiceSearchBtn: 'بول کر تلاش کریں',
    connectWithFarmersBtn: 'ساتھی کسان جوڑیں',
    poolTruckSubtitle: '10 کلومیٹر میں گاڑی شیئر کریں',
    poolTruckloadBtn: 'گاڑی شیئر کریں (پول)',
    farmersPooledStatus: 'کسان جڑے • مشترکہ گاڑی',
    smallYieldBadge: '< 15 کوئنٹل',
    smallYieldAlert: 'کم پیداوار (< 15 کوئنٹل): اکیلے گاڑی کرنے پر 25-35% کرایہ میں چلا جائے گا۔ قریبی کسانوں کے ساتھ گاڑی شیئر کر کے ₹80-120/کوئنٹل بچائیں!',
    arrivalsLabel: 'آمد',
    volumeTrendLabel: 'آمد کا رجحان',
    sameStateMandiBanner: '≤ 100 کلومیٹر قریبی منڈیاں',
    kmAway: 'کلومیٹر دور',
    transitCautionLabel: 'منڈی ٹرانسپورٹ احتیاط',
    safeHoldingLabel: 'محفوظ اسٹوریج مدت',
    recommendedStorageLabel: 'تجویز کردہ اسٹوریج',
    quintalsUnit: 'کوئنٹل',
    kgUnit: 'کلوگرام',
    costOfCultivationLabel: 'لاگت خرچ (₹/کوئنٹل)',
    calculateIndividualProfit: 'انفرادی منافع دیکھیں',
    calculatePooledProfit: 'مشترکہ گاڑی کا منافع دیکھیں',
    editPoolBtn: 'پول تبدیل کریں',
    bulkPoolingSavings: 'مشترکہ گاڑی کی بچت',
    roundTrip: 'آنا جانا',
    activeTradersLabel: 'سرگرم تاجر',
    licensedTraders: 'لائسنس یافتہ',
    paymentLabel: 'ادائیگی',
    scientificStorageTitle: 'سائنسی اسٹوریج ہدایات',
    scientificStorageSubtitle: 'محفوظ مدت، نمی کے معیارات اور ٹرانسپورٹ حفاظت',
    hideGuidelines: 'چھپائیں',
    viewGuidelines: 'ہدایات دیکھیں',
    safeDurationLabel: 'محفوظ مدت',
    moistureStandardLabel: 'نمی کا معیار',
    keyDirectivesLabel: 'اہم ہدایات',
    lowInternetBadge: 'کمزور انٹرنیٹ اور بٹن والے فون کی سہولت',
    shareWithKisanGroup: 'کسان گروپ میں شیئر کریں',
    smsPrefilledNotice: '✓ ایس ایم ایس کھل گیا۔ ریٹ اور مشورہ تیار ہے!',
    kisanCallCenterTitle: 'کسان کال سینٹر',
    kisanCallCenterDesc: 'زرعی سائنسدانوں سے 22 زبانوں میں براہ راست بات کریں۔ روزانہ صبح 6 سے رات 10 بجے تک۔',
    callFreeBtn: 'کال کریں 1800-180-1551 (مفت کال)',
    outdoorSunlightTitle: 'تیز دھوپ موڈ',
    sunlightModeDesc: 'کھیت میں تیز دھوپ میں آسانی سے پڑھنے کیلئے گہرا کنٹراسٹ۔',
    turnSunlightOn: 'دھوپ موڈ آن کریں',
    turnSunlightOff: 'دھوپ موڈ آن ہے',
    languagesCountTitle: '13 ہندوستانی زبانیں',
    changeZoneBtn: 'تبدیل کریں',
    zoneLabel: 'زون',
    cloudSyncTitle: 'کسان کلاؤڈ سنک',
    signInBtn: 'سائن ان',
    onlineStatus: 'آن لائن',
    pinCrop: 'پن کریں',
    pinnedCrop: 'پن شدہ',
    changeCropAction: 'فصل تبدیل کریں',
  },
};

export function speakText(text: string, lang: Language, onEnd?: () => void): SpeechSynthesisUtterance | null {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    return null;
  }

  window.speechSynthesis.cancel(); // Stop ongoing speech

  const utterance = new SpeechSynthesisUtterance(text);
  utterance.rate = 0.9;
  utterance.pitch = 1.0;

  const langCodes: Record<Language, string> = {
    en: 'en-IN',
    hi: 'hi-IN',
    mr: 'mr-IN',
    gu: 'gu-IN',
    pa: 'pa-IN',
    bn: 'bn-IN',
    te: 'te-IN',
    ta: 'ta-IN',
    kn: 'kn-IN',
    ml: 'ml-IN',
    or: 'or-IN',
    as: 'as-IN',
    ur: 'ur-IN',
  };

  utterance.lang = langCodes[lang] || 'hi-IN';

  const voices = window.speechSynthesis.getVoices();
  const indianVoice = voices.find(
    (v) =>
      v.lang === utterance.lang ||
      v.lang.toLowerCase().includes('in') ||
      v.lang.startsWith(utterance.lang.split('-')[0])
  );
  if (indianVoice) {
    utterance.voice = indianVoice;
  }

  if (onEnd) {
    utterance.onend = onEnd;
    utterance.onerror = onEnd;
  }

  window.speechSynthesis.speak(utterance);
  return utterance;
}

export function stopSpeaking() {
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
    window.speechSynthesis.cancel();
  }
}
