import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { Language } from '../types';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}

export interface TranslationStrings {
  appName: string;
  tagline: string;
  audioMode: string;
  audioPlaying: string;
  stopAudio: string;
  sunlightMode: string;
  selectCrop: string;
  selectCropSubtitle: string;
  voiceSearchPrompt: string;
  voiceSearchActive: string;
  decisionSignal: string;
  highestPriceToday: string;
  perQuintal: string;
  sellTodayVerdict: string;
  waitVerdict: string;
  riskVerdict: string;
  netProfitTitle: string;
  netProfitSubtitle: string;
  yourHarvestQuantity: string;
  chooseVehicle: string;
  dieselTransportCost: string;
  grossSale: string;
  actualNetCash: string;
  bestProfitBadge: string;
  extraCash: string;
  offlineBannerTitle: string;
  sendSmsBtn: string;
  playAudioBtn: string;
  missedCallTitle: string;
  missedCallNumber: string;
  missedCallDesc: string;
  distance: string;
  buyersToday: string;
  paymentInstant: string;
  sevenDayTrend: string;
  today: string;
  keyFactors: string;
  weatherNotice: string;
  locationLabel: string;
  changeLocation: string;
  detectLocation: string;
  detectedNotice: string;
  searchPlaceholder: string;
  allCrops: string;
  categoryCereals: string;
  categoryPulses: string;
  categoryOilseeds: string;
  categorySpices: string;
  categoryVegetables: string;
  categoryCashCrops: string;
  categoryFruits: string;
}

export const translations: Record<Language, TranslationStrings> = {
  en: {
    appName: 'MandiMitra',
    tagline: 'All-India Smart Crop Decision & Net Profit System',
    audioMode: 'Listen to Advice',
    audioPlaying: 'Reading Advice...',
    stopAudio: 'Stop Audio',
    sunlightMode: 'Sunlight Mode',
    selectCrop: 'Select Your Crop',
    selectCropSubtitle: 'Tap your crop to view today’s mandi rates & smart decision',
    voiceSearchPrompt: 'Tap mic & speak any crop name in your language',
    voiceSearchActive: 'Listening... Speak your crop name',
    decisionSignal: 'Decision Signal',
    highestPriceToday: 'Highest Mandi Price Today',
    perQuintal: 'per quintal (100 kg)',
    sellTodayVerdict: 'Sell Today - Mandi Prices are Peaking',
    waitVerdict: 'Wait 2–3 Days - Expected Rate Increase',
    riskVerdict: 'Sell Immediately - High Weather/Spoilage Risk',
    netProfitTitle: 'Net In-Hand Profit Calculator',
    netProfitSubtitle: 'Don’t just look at mandi rate! Compare real take-home cash after diesel/transport costs.',
    yourHarvestQuantity: 'Your Crop Quantity (Quintals)',
    chooseVehicle: 'Choose Transport Vehicle',
    dieselTransportCost: 'Est. Fuel / Transport Cost',
    grossSale: 'Gross Mandi Sale',
    actualNetCash: 'Actual Net Cash In-Hand',
    bestProfitBadge: 'Best Profit Choice',
    extraCash: 'Extra Cash In-Hand',
    offlineBannerTitle: 'Low Internet or Feature Phone?',
    sendSmsBtn: 'Send Rates to My Phone via SMS',
    playAudioBtn: 'Play Voice Advisory',
    missedCallTitle: 'Free Toll-Free Missed Call',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'Give a missed call from any keypad phone to hear current rates in your regional language',
    distance: 'Distance',
    buyersToday: 'Active Traders',
    paymentInstant: 'Payment',
    sevenDayTrend: '7-Day Price Trend & Forecast',
    today: 'Today',
    keyFactors: 'Why this decision?',
    weatherNotice: 'Weather Alert',
    locationLabel: 'State Location',
    changeLocation: 'Change Location',
    detectLocation: 'Detect via GPS',
    detectedNotice: 'Location detected: Switched language & regional mandis',
    searchPlaceholder: 'Search all crops across India (Wheat, Cotton, Soybean, Onion, Tur)...',
    allCrops: 'All Crops',
    categoryCereals: 'Cereals & Millets',
    categoryPulses: 'Pulses (Dal)',
    categoryOilseeds: 'Oilseeds',
    categorySpices: 'Spices',
    categoryVegetables: 'Vegetables',
    categoryCashCrops: 'Cash Crops',
    categoryFruits: 'Fruits & Plantation',
  },
  hi: {
    appName: 'मंडी मित्र',
    tagline: 'अखिल भारतीय किसान मंडी भाव और असली मुनाफा प्रणाली',
    audioMode: 'सलाह सुनें',
    audioPlaying: 'सलाह पढ़ी जा रही है...',
    stopAudio: 'आवाज रोकें',
    sunlightMode: 'धूप मोड',
    selectCrop: 'अपनी फसल चुनें',
    selectCropSubtitle: 'आज के मंडी भाव और सही फैसला जानने के लिए फसल पर टैप करें',
    voiceSearchPrompt: 'माइक दबाकर किसी भी फसल का नाम बोलें (जैसे "गेहूं", "चना", "प्याज")',
    voiceSearchActive: 'सुन रहे हैं... फसल का नाम बोलें',
    decisionSignal: 'फैसला संकेत (Decision Signal)',
    highestPriceToday: 'आज का सबसे ऊंचा मंडी भाव',
    perQuintal: 'प्रति क्विंटल (100 किलो)',
    sellTodayVerdict: 'आज ही बेचें - मंडी भाव उच्चतम स्तर पर हैं',
    waitVerdict: '2–3 दिन रुकें - भाव और बढ़ने की उम्मीद है',
    riskVerdict: 'तुरंत बेचें - मौसम खराबी या सड़ने का खतरा',
    netProfitTitle: 'हाथ में आने वाला असली मुनाफा (Net Profit)',
    netProfitSubtitle: 'सिर्फ मंडी भाव मत देखें! डीजल और भाड़ा घटाकर हाथ में बचने वाले असली पैसे देखें।',
    yourHarvestQuantity: 'फसल की कुल मात्रा (क्विंटल)',
    chooseVehicle: 'परिवहन वाहन चुनें',
    dieselTransportCost: 'अनुमानित डीजल / भाड़ा खर्च',
    grossSale: 'कुल मंडी बिक्री',
    actualNetCash: 'हाथ में शुद्ध नकद (Net Cash)',
    bestProfitBadge: 'सबसे ज्यादा फायदे का सौदा',
    extraCash: 'अतिरिक्त नकद बचत',
    offlineBannerTitle: 'धीमा इंटरनेट या सादा कीपैड फोन?',
    sendSmsBtn: 'एसएमएस (SMS) से अपने फोन पर भाव मंगाएं',
    playAudioBtn: 'ऑडियो सलाह हिंदी में सुनें',
    missedCallTitle: 'मुफ्त मिस्ड कॉल सेवा',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'किसी भी फोन से मिस्ड कॉल दें और तुरंत अपनी भाषा में बोलकर भाव सुनें',
    distance: 'दूरी',
    buyersToday: 'सक्रिय व्यापारी',
    paymentInstant: 'भुगतान',
    sevenDayTrend: '7-दिन का भाव ग्राफ और पूर्वानुमान',
    today: 'आज',
    keyFactors: 'यह फैसला क्यों?',
    weatherNotice: 'मौसम चेतावनी',
    locationLabel: 'राज्य / स्थान',
    changeLocation: 'राज्य बदलें',
    detectLocation: 'GPS से खोजें',
    detectedNotice: 'लोकेशन के अनुसार भाषा और मंडी सूची अपडेट की गई',
    searchPlaceholder: 'भारत की किसी भी फसल को खोजें (गेहूं, धान, चना, कपास, प्याज)...',
    allCrops: 'सभी फसलें',
    categoryCereals: 'अनाज और मिलेट्स',
    categoryPulses: 'दलहन (दालें)',
    categoryOilseeds: 'तिलहन',
    categorySpices: 'मसाले',
    categoryVegetables: 'सब्जियां',
    categoryCashCrops: 'नकदी फसलें',
    categoryFruits: 'फल व बागवानी',
  },
  mr: {
    appName: 'मंडी मित्र',
    tagline: 'शेतकऱ्यांसाठी स्मार्ट बाजारभाव व प्रत्यक्ष निव्वळ नफा सल्ला',
    audioMode: 'सल्ला ऐका',
    audioPlaying: 'सल्ला वाचत आहे...',
    stopAudio: 'आवाज बंद करा',
    sunlightMode: 'उजेड मोड',
    selectCrop: 'आपले पीक निवडा',
    selectCropSubtitle: 'आजचा बाजारभाव आणि योग्य निर्णय पाहण्यासाठी पिकावर टॅप करा',
    voiceSearchPrompt: 'माईक दाबून पिकाचे नाव सांगा (उदा. "कांदा", "सोयाबीन", "कापूस")',
    voiceSearchActive: 'ऐकत आहे... पिकाचे नाव सांगा',
    decisionSignal: 'निर्णय संकेत (Decision Signal)',
    highestPriceToday: 'आजचा सर्वोच्च बाजारभाव',
    perQuintal: 'प्रति क्विंटल (100 किलो)',
    sellTodayVerdict: 'आजच विका - बाजारभाव उच्चांकी पातळीवर आहेत',
    waitVerdict: '२–३ दिवस थांबा - भाव वाढण्याची शक्यता आहे',
    riskVerdict: 'त्वरित विका - पाऊस आणि नासाडीचा धोका',
    netProfitTitle: 'हातात उरणारा खरा निव्वळ नफा',
    netProfitSubtitle: 'फक्त बाजाराचा दर पाहू नका! डिझेल आणि वाहतूक खर्च वजा करून खिशात काय उरेल ते तपासा.',
    yourHarvestQuantity: 'पिकाचे प्रमाण (क्विंटल)',
    chooseVehicle: 'वाहतुकीचे वाहन निवडा',
    dieselTransportCost: 'अंदाजे डिझेल / वाहतूक खर्च',
    grossSale: 'एकूण बाजार विक्री',
    actualNetCash: 'हातात प्रत्यक्ष रोकड (Net Cash)',
    bestProfitBadge: 'सर्वाधिक नफ्याचा पर्याय',
    extraCash: 'जास्तीचा नफा',
    offlineBannerTitle: 'कमी इंटरनेट किंवा साधा कीपॅड फोन?',
    sendSmsBtn: 'SMS द्वारे माझ्या फोनवर दर मागवा',
    playAudioBtn: 'ऑडिओ सल्ला मराठीत ऐका',
    missedCallTitle: 'मोफत मिस्ड कॉल सेवा',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'कोणत्याही फोनवरून मिस्ड कॉल द्या आणि मोफत ऑडिओ रिपोर्ट मिळवा',
    distance: 'अंतर',
    buyersToday: 'खरेदीदार व्यापारी',
    paymentInstant: 'पैसे भरणा',
    sevenDayTrend: '७-दिवसीय भाव कल आणि अंदाज',
    today: 'आज',
    keyFactors: 'हा सल्ला का दिला?',
    weatherNotice: 'हवामान इशारा',
    locationLabel: 'स्थान / राज्य',
    changeLocation: 'राज्य बदला',
    detectLocation: 'GPS द्वारे शोधा',
    detectedNotice: 'तुमच्या स्थानानुसार भाषा आणि स्थानिक बाजारपेठा निवडल्या आहेत',
    searchPlaceholder: 'कोणतेही पीक शोधा (कांदा, सोयाबीन, कापूस, तूर, गहू)...',
    allCrops: 'सर्व पिके',
    categoryCereals: 'धान्य आणि तृणधान्य',
    categoryPulses: 'कडधान्ये (डाळी)',
    categoryOilseeds: 'गळीत धान्ये (तेलबिया)',
    categorySpices: 'मसाले पिके',
    categoryVegetables: 'भाजीपाला',
    categoryCashCrops: 'नगदी पिके',
    categoryFruits: 'फळे व बागायती',
  },
  gu: {
    appName: 'મંડી મિત્ર',
    tagline: 'ખેડૂતો માટે સ્માર્ટ પાક ભાવ અને ચોખ્ખો નફો',
    audioMode: 'સલાહ સાંભળો',
    audioPlaying: 'સલાહ સંભળાઈ રહી છે...',
    stopAudio: 'અવાજ બંધ કરો',
    sunlightMode: 'તડકો મોડ',
    selectCrop: 'તમારો પાક પસંદ કરો',
    selectCropSubtitle: 'આજના માર્કેટ યાર્ડ ભાવ અને સ્માર્ટ નિર્ણય જોવા માટે પાક પર ટેપ કરો',
    voiceSearchPrompt: 'માઇક દબાવી પાકનું નામ બોલો (દા.ત. "જીરું", "કપાસ", "મગફળી")',
    voiceSearchActive: 'સાંભળી રહ્યા છીએ... પાકનું નામ બોલો',
    decisionSignal: 'નિર્ણય સંકેત (Decision Signal)',
    highestPriceToday: 'આજનો સૌથી ઊંચો યાર્ડ ભાવ',
    perQuintal: 'પ્રતિ ક્વિન્ટલ (100 કિલો)',
    sellTodayVerdict: 'આજે જ વેચો - માર્કેટ યાર્ડ ભાવ ટોચ પર છે',
    waitVerdict: '૨–૩ દિવસ રાહ જુઓ - ભાવ વધવાની ધારણા છે',
    riskVerdict: 'તરત જ વેચો - હવામાન બગડવા કે નુકસાનનું જોખમ',
    netProfitTitle: 'હાથમાં આવતો વાસ્તવિક ચોખ્ખો નફો',
    netProfitSubtitle: 'માત્ર યાર્ડ ભાવ ન જુઓ! ડીઝલ અને પરિવહન ખર્ચ બાદ કરી હાથમાં કેટલા પૈસા બચે તે સરખાવો.',
    yourHarvestQuantity: 'પાકની માત્રા (ક્વિન્ટલ)',
    chooseVehicle: 'વાહન પસંદ કરો',
    dieselTransportCost: 'અંદાજિત પરિવહન/ડીઝલ ખર્ચ',
    grossSale: 'કુલ યાર્ડ વેચાણ',
    actualNetCash: 'હાથમાં ચોખ્ખી રોકડ',
    bestProfitBadge: 'સૌથી વધુ નફાકારક યાર્ડ',
    extraCash: 'વધારાની રોકડ બચત',
    offlineBannerTitle: 'ધીમું ઇન્ટરનેટ કે સાદો કીપેડ ફોન?',
    sendSmsBtn: 'SMS દ્વારા મારા ફોન પર ભાવ મેળવો',
    playAudioBtn: 'ઓડિયો સલાહ સાંભળો',
    missedCallTitle: 'મફત મિસ્ડ કૉલ સેવા',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'કોઈપણ ફોન પરથી મિસ્ડ કૉલ કરો અને મફત ઓડિયો ભાવ સાંભળો',
    distance: 'અંતર',
    buyersToday: 'વેપારીઓ',
    paymentInstant: 'ચૂકવણી',
    sevenDayTrend: '૭-દિવસનો ભાવ ટ્રેન્ડ અને આગાહી',
    today: 'આજે',
    keyFactors: 'આ નિર્ણય કેમ?',
    weatherNotice: 'હવામાન ચેતવણી',
    locationLabel: 'રાજ્ય / સ્થાન',
    changeLocation: 'રાજ્ય બદલો',
    detectLocation: 'GPS થી શોધો',
    detectedNotice: 'તમારા સ્થાન મુજબ ગુજરાતી ભાષા અને યાર્ડ પસંદ કરવામાં આવ્યા છે',
    searchPlaceholder: 'પાક શોધો (કપાસ, મગફળી, જીરું, ડુંગળી, ઘઉં)...',
    allCrops: 'બધા પાકો',
    categoryCereals: 'અનાજ અને બાજરી',
    categoryPulses: 'કઠોળ',
    categoryOilseeds: 'તેલીબિયાં',
    categorySpices: 'મસાલા',
    categoryVegetables: 'શાકભાજી',
    categoryCashCrops: 'રોકડિયા પાક',
    categoryFruits: 'ફળો અને બાગાયત',
  },
  pa: {
    appName: 'ਮੰਡੀ ਮਿੱਤਰ',
    tagline: 'ਕਿਸਾਨਾਂ ਲਈ ਸਮਾਰਟ ਫ਼ਸਲ ਭਾਅ ਅਤੇ ਅਸਲ ਮੁਨਾਫ਼ਾ ਪ੍ਰਣਾਲੀ',
    audioMode: 'ਸਲਾਹ ਸੁਣੋ',
    audioPlaying: 'ਸਲਾਹ ਪੜ੍ਹੀ ਜਾ ਰਹੀ ਹੈ...',
    stopAudio: 'ਆਵਾਜ਼ ਬੰਦ ਕਰੋ',
    sunlightMode: 'ਧੁੱਪ ਮੋਡ',
    selectCrop: 'ਆਪਣੀ ਫ਼ਸਲ ਚੁਣੋ',
    selectCropSubtitle: 'ਅੱਜ ਦੇ ਮੰਡੀ ਭਾਅ ਅਤੇ ਸਹੀ ਫ਼ੈਸਲੇ ਲਈ ਫ਼ਸਲ ਤੇ ਕਲਿੱਕ ਕਰੋ',
    voiceSearchPrompt: 'ਮਾਈਕ ਦਬਾ ਕੇ ਫ਼ਸਲ ਦਾ ਨਾਮ ਬੋਲੋ (ਜਿਵੇਂ "ਕਣਕ", "ਝੋਨਾ", "ਨਰਮਾ")',
    voiceSearchActive: 'ਸੁਣ ਰਹੇ ਹਾਂ... ਫ਼ਸਲ ਦਾ ਨਾਮ ਬੋਲੋ',
    decisionSignal: 'ਫ਼ੈਸਲਾ ਸੰਕੇਤ (Decision Signal)',
    highestPriceToday: 'ਅੱਜ ਦਾ ਸਭ ਤੋਂ ਉੱਚਾ ਮੰਡੀ ਰੇਟ',
    perQuintal: 'ਪ੍ਰਤੀ ਕੁਇੰਟਲ (100 ਕਿਲੋ)',
    sellTodayVerdict: 'ਅੱਜ ਹੀ ਵੇਚੋ - ਮੰਡੀ ਰੇਟ ਸਿਖਰ ਤੇ ਹਨ',
    waitVerdict: '੨–੩ ਦਿਨ ਰੁਕੋ - ਭਾਅ ਹੋਰ ਵਧਣ ਦੀ ਉਮੀਦ ਹੈ',
    riskVerdict: 'ਤੁਰੰਤ ਵੇਚੋ - ਮੌਸਮ ਖ਼ਰਾਬੀ ਜਾਂ ਖ਼ਰਾਬ ਹੋਣ ਦਾ ਖ਼ਤਰਾ',
    netProfitTitle: 'ਹੱਥ ਵਿੱਚ ਆਉਣ ਵਾਲਾ ਅਸਲ ਮੁਨਾਫ਼ਾ (Net Profit)',
    netProfitSubtitle: 'ਸਿਰਫ਼ ਮੰਡੀ ਦਾ ਭਾਅ ਨਾ ਦੇਖੋ! ਡੀਜ਼ਲ ਅਤੇ ਢੋਆ-ਢੁਆਈ ਖ਼ਰਚ ਕੱਢ ਕੇ ਅਸਲ ਬਚਤ ਦੇਖੋ।',
    yourHarvestQuantity: 'ਫ਼ਸਲ ਦੀ ਮਾਤਰਾ (ਕੁਇੰਟਲ)',
    chooseVehicle: 'ਢੋਆ-ਢੁਆਈ ਵਾਹਨ ਚੁਣੋ',
    dieselTransportCost: 'ਅੰਦਾਜ਼ਨ ਡੀਜ਼ਲ / ਕਿਰਾਇਆ ਖ਼ਰਚ',
    grossSale: 'ਕੁੱਲ ਮੰਡੀ ਵਿਕਰੀ',
    actualNetCash: 'ਹੱਥ ਵਿੱਚ ਸ਼ੁੱਧ ਨਕਦੀ',
    bestProfitBadge: 'ਸਭ ਤੋਂ ਵੱਧ ਮੁਨਾਫ਼ੇ ਵਾਲੀ ਮੰਡੀ',
    extraCash: 'ਵਾਧੂ ਨਕਦ ਬਚਤ',
    offlineBannerTitle: 'ਧੀਮਾ ਇੰਟਰਨੈੱਟ ਜਾਂ ਸਾਦਾ ਕੀਪੈਡ ਫ਼ੋਨ?',
    sendSmsBtn: 'SMS ਰਾਹੀਂ ਮੋਬਾਈਲ ਤੇ ਭਾਅ ਮੰਗਵਾਓ',
    playAudioBtn: 'ਆਡੀਓ ਸਲਾਹ ਪੰਜਾਬੀ ਵਿੱਚ ਸੁਣੋ',
    missedCallTitle: 'ਮੁਫ਼ਤ ਮਿਸਡ ਕਾਲ ਸੇਵਾ',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ਕਿਸੇ ਵੀ ਫ਼ੋਨ ਤੋਂ ਮਿਸਡ ਕਾਲ ਦਿਓ ਅਤੇ ਆਪਣੀ ਬੋਲੀ ਵਿੱਚ ਤੁਰੰਤ ਭਾਅ ਸੁਣੋ',
    distance: 'ਦੂਰੀ',
    buyersToday: 'ਸਰਗਰਮ ਵਪਾਰੀ',
    paymentInstant: 'ਭੁਗਤਾਨ',
    sevenDayTrend: '੭-ਦਿਨ ਦਾ ਭਾਅ ਗ੍ਰਾਫ਼ ਅਤੇ ਭਵਿੱਖਬਾਣੀ',
    today: 'ਅੱਜ',
    keyFactors: 'ਇਹ ਫ਼ੈਸਲਾ ਕਿਉਂ?',
    weatherNotice: 'ਮੌਸਮ ਚੇਤਾਵਨੀ',
    locationLabel: 'ਸੂਬਾ / ਸਥਾਨ',
    changeLocation: 'ਸੂਬਾ ਬਦਲੋ',
    detectLocation: 'GPS ਰਾਹੀਂ ਲੱਭੋ',
    detectedNotice: 'ਤੁਹਾਡੇ ਇਲਾਕੇ ਮੁਤਾਬਕ ਪੰਜਾਬੀ ਭਾਸ਼ਾ ਅਤੇ ਉੱਤਰੀ ਮੰਡੀਆਂ ਚੁਣੀਆਂ ਗਈਆਂ ਹਨ',
    searchPlaceholder: 'ਕਿਸੇ ਵੀ ਫ਼ਸਲ ਦੀ ਖੋਜ ਕਰੋ (ਕਣਕ, ਝੋਨਾ, ਨਰਮਾ, ਸਰ੍ਹੋਂ, ਮੱਕੀ)...',
    allCrops: 'ਸਾਰੀਆਂ ਫ਼ਸਲਾਂ',
    categoryCereals: 'ਅਨਾਜ ਅਤੇ ਬਾਜਰਾ',
    categoryPulses: 'ਦਾਲਾਂ',
    categoryOilseeds: 'ਤੇਲ ਬੀਜ',
    categorySpices: 'ਮਸਾਲੇ',
    categoryVegetables: 'ਸਬਜ਼ੀਆਂ',
    categoryCashCrops: 'ਨਕਦੀ ਫ਼ਸਲਾਂ',
    categoryFruits: 'ਫ਼ਲ ਅਤੇ ਬਾਗ਼ਬਾਨੀ',
  },
  bn: {
    appName: 'মান্ডি মিত্র',
    tagline: 'কৃষকদের জন্য স্মার্ট ফসলের বাজারদর ও আসল মুনাফা পরামর্শ',
    audioMode: 'পরামর্শ শুনুন',
    audioPlaying: 'পরামর্শ পড়া হচ্ছে...',
    stopAudio: 'শব্দ বন্ধ করুন',
    sunlightMode: 'রোদ মোড',
    selectCrop: 'আপনার ফসল বেছে নিন',
    selectCropSubtitle: 'আজকের বাজারদর ও সঠিক সিদ্ধান্তের জন্য ফসলে ক্লিক করুন',
    voiceSearchPrompt: 'মাইক টিপে ফসলের নাম বলুন (যেমন "ধান", "আলু", "পাট")',
    voiceSearchActive: 'শুনছি... ফসলের নাম বলুন',
    decisionSignal: 'সিদ্ধান্ত সংকেত (Decision Signal)',
    highestPriceToday: 'আজকের সর্বোচ্চ বাজারদর',
    perQuintal: 'প্রতি কুইন্টাল (১০০ কেজি)',
    sellTodayVerdict: 'আজই বিক্রি করুন - বাজারদর শীর্ষে রয়েছে',
    waitVerdict: '২–৩ দিন অপেক্ষা করুন - দর আরও বাড়ার সম্ভাবনা',
    riskVerdict: 'অবিলম্বে বিক্রি করুন - আবহাওয়া বা নষ্ট হওয়ার ঝুঁকি',
    netProfitTitle: 'হাতে পাওয়া আসল লাভ (Net Profit)',
    netProfitSubtitle: 'শুধু বাজারের দর দেখবেন না! পরিবহন ও ডিজেল খরচ বাদ দিয়ে আসল টাকা হিসাব করুন।',
    yourHarvestQuantity: 'ফসলের পরিমাণ (কুইন্টাল)',
    chooseVehicle: 'পরিবহন গাড়ি বেছে নিন',
    dieselTransportCost: 'আনুমানিক ডিজেল ও পরিবহন খরচ',
    grossSale: 'মোট বাজার বিক্রয়',
    actualNetCash: 'হাতে নগদ আসল টাকা',
    bestProfitBadge: 'সেরা লাভের বাজার',
    extraCash: 'অতিরিক্ত নগদ লাভ',
    offlineBannerTitle: 'ধীরগতির ইন্টারনেট বা বোতামের ফোন?',
    sendSmsBtn: 'SMS এর মাধ্যমে ফোনে দর আনুন',
    playAudioBtn: 'বাংলায় ভয়েস পরামর্শ শুনুন',
    missedCallTitle: 'বিনামূল্যে মিসড কল সেবা',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'যেকোনো ফোন থেকে মিসড কল দিন এবং আপনার ভাষায় বিনামূল্যে দর শুনুন',
    distance: 'দূরত্ব',
    buyersToday: 'সক্রিয় ব্যবসায়ী',
    paymentInstant: 'পেমেন্ট',
    sevenDayTrend: '৭ দিনের দর গ্রাফ ও পূর্বাভাস',
    today: 'আজ',
    keyFactors: 'কেন এই সিদ্ধান্ত?',
    weatherNotice: 'আবহাওয়া সতর্কতা',
    locationLabel: 'রাজ্য / স্থান',
    changeLocation: 'রাজ্য পরিবর্তন করুন',
    detectLocation: 'GPS দিয়ে খুঁজুন',
    detectedNotice: 'আপনার অবস্থান অনুসারে বাংলা ভাষা ও আঞ্চলিক বাজার নির্ধারণ করা হয়েছে',
    searchPlaceholder: 'যেকোনো ফসল খুঁজুন (ধান, আলু, পাট, চা, সরিষা)...',
    allCrops: 'সব ফসল',
    categoryCereals: 'দানা শস্য ও বাজরা',
    categoryPulses: 'ডাল শস্য',
    categoryOilseeds: 'তৈলবীজ',
    categorySpices: 'মশলা',
    categoryVegetables: 'শাকসবজি',
    categoryCashCrops: 'অর্থকরী ফসল',
    categoryFruits: 'ফল ও বাগান',
  },
  te: {
    appName: 'మండి మిత్ర',
    tagline: 'రైతుల కోసం స్మార్ట్ మార్కెట్ ధరలు & నికర లాభ సూచిక',
    audioMode: 'సలహా వినండి',
    audioPlaying: 'సలహా చదువుతోంది...',
    stopAudio: 'ఆపండి',
    sunlightMode: 'ఎండ మోడ్',
    selectCrop: 'మీ పంటను ఎంచుకోండి',
    selectCropSubtitle: 'నేటి మార్కెట్ యార్డ్ ధరలు & సరైన నిర్ణయం కోసం పంటను నొక్కండి',
    voiceSearchPrompt: 'మైక్ నొక్కి పంట పేరు చెప్పండి (ఉదా. "మిర్చి", "వరి", "పత్తి")',
    voiceSearchActive: 'వింటున్నాము... పంట పేరు చెప్పండి',
    decisionSignal: 'నిర్ణయ సంకేతం (Decision Signal)',
    highestPriceToday: 'నేటి అత్యధిక మార్కెట్ ధర',
    perQuintal: 'క్వింటాల్‌కు (100 కిలోలు)',
    sellTodayVerdict: 'ఈరోజే అమ్మండి - మార్కెట్ ధరలు గరిష్ట స్థాయికి చేరాయి',
    waitVerdict: '2–3 రోజులు ఆగండి - ధరలు పెరిగే అవకాశం ఉంది',
    riskVerdict: 'వెంటనే అమ్మండి - వాతావరణం లేదా నష్టం ముప్పు',
    netProfitTitle: 'చేతికి అందే నికర లాభం (Net Profit)',
    netProfitSubtitle: 'కేవలం రేటు మాత్రమే చూడకండి! రవాణా ఖర్చులు తీసివేసిన తర్వాత మిగిలే డబ్బును లెక్కించండి.',
    yourHarvestQuantity: 'పంట పరిమాణం (క్వింటాళ్ళు)',
    chooseVehicle: 'రవాణా వాహనాన్ని ఎంచుకోండి',
    dieselTransportCost: 'అంచనా డీజిల్ / రవాణా ఖర్చు',
    grossSale: 'మొత్తం మార్కెట్ అమ్మకం',
    actualNetCash: 'చేతికి వచ్చే నికర నగదు',
    bestProfitBadge: 'అత్యధిక లాభం వచ్చే మార్కెట్',
    extraCash: 'అదనపు నగదు ఆదా',
    offlineBannerTitle: 'నెట్ స్లోగా ఉందా లేదా కీప్యాడ్ ఫోనా?',
    sendSmsBtn: 'SMS ద్వారా ఫోన్‌కు ధరలను పొందండి',
    playAudioBtn: 'తెలుగులో ఆడియో సలహా వినండి',
    missedCallTitle: 'ఉచిత మిస్డ్ కాల్ సేవ',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ఏ ఫోన్ నుంచైనా మిస్డ్ కాల్ ఇచ్చి మీ మాతృభాషలో ధరలు తెలుసుకోండి',
    distance: 'దూరం',
    buyersToday: 'కొనుగోలు వ్యాపారులు',
    paymentInstant: 'చెల్లింపు',
    sevenDayTrend: '7 రోజుల ధరల ట్రెండ్ & అంచనా',
    today: 'నేడు',
    keyFactors: 'ఈ నిర్ణయం ఎందుకు?',
    weatherNotice: 'వాతావరణ హెచ్చరిక',
    locationLabel: 'రాష్ట్రం / ప్రాంతం',
    changeLocation: 'రాష్ట్రం మార్చండి',
    detectLocation: 'GPS ద్వారా గుర్తించండి',
    detectedNotice: 'మీ ప్రాంతం ప్రకారం తెలుగు భాష మరియు మార్కెట్లు ఎంపిక చేయబడ్డాయి',
    searchPlaceholder: 'ఏదైనా పంటను వెతకండి (మిర్చి, పత్తి, వరి, మొక్కజొన్న, పసుపు)...',
    allCrops: 'అన్ని పంటలు',
    categoryCereals: 'ధాన్యాలు & మిల్లెట్లు',
    categoryPulses: 'పప్పుధాన్యాలు',
    categoryOilseeds: 'నూనె గింజలు',
    categorySpices: 'మసాలా దినుసులు',
    categoryVegetables: 'కూరగాయలు',
    categoryCashCrops: 'వాణిజ్య పంటలు',
    categoryFruits: 'పండ్లు & తోటలు',
  },
  ta: {
    appName: 'மண்டி மித்ரா',
    tagline: 'விவசாயிகளுக்கான சந்தை விலை மற்றும் நிகர லாப வழிகாட்டி',
    audioMode: 'ஆலோசனை கேட்க',
    audioPlaying: 'ஆலோசனை ஒலிக்கிறது...',
    stopAudio: 'நிறுத்து',
    sunlightMode: 'வெயில் முறை',
    selectCrop: 'உங்கள் பயிரைத் தேர்வுசெய்க',
    selectCropSubtitle: 'இன்றைய சந்தை விலை மற்றும் முடிவுகளை அறிய பயிரைத் தொடவும்',
    voiceSearchPrompt: 'மைக்கை அழுத்தி பயிர் பெயரைப் பேசுங்கள் (எ.கா. "நெல்", "மஞ்சள்", "வெங்காயம்")',
    voiceSearchActive: 'கேட்கிறது... பயிரின் பெயரைச் சொல்லுங்கள்',
    decisionSignal: 'முடிவு சமிக்ஞை (Decision Signal)',
    highestPriceToday: 'இன்றைய அதிகபட்ச சந்தை விலை',
    perQuintal: 'குவிண்டாலுக்கு (100 கிலோ)',
    sellTodayVerdict: 'இன்றே விற்கவும் - சந்தை விலை உச்சத்தில் உள்ளது',
    waitVerdict: '2–3 நாட்கள் காத்திருக்கவும் - விலை உயரும் வாய்ப்பு',
    riskVerdict: 'உடனடியாக விற்கவும் - வானிலை அல்லது சேத அபாயம்',
    netProfitTitle: 'கைக்கு கிடைக்கும் நிகர லாபம் (Net Profit)',
    netProfitSubtitle: 'சந்தை விலையை மட்டும் பார்க்காதீர்கள்! போக்குவரத்து செலவைக் கழித்த பிறகான நிகர தொகையை அறியுங்கள்.',
    yourHarvestQuantity: 'பயிர் அளவு (குவிண்டால்)',
    chooseVehicle: 'வாகனத்தைத் தேர்ந்தெடுக்கவும்',
    dieselTransportCost: 'போக்குவரத்து செலவு',
    grossSale: 'மொத்த சந்தை விற்பனை',
    actualNetCash: 'கைக்கு வரும் நிகர பணம்',
    bestProfitBadge: 'அதிக லாபகரமான சந்தை',
    extraCash: 'கூடுதல் லாப சேமிப்பு',
    offlineBannerTitle: 'இணையம் மெதுவாக உள்ளதா அல்லது பட்டன் போனா?',
    sendSmsBtn: 'SMS மூலம் விலையை அறியவும்',
    playAudioBtn: 'தமிழில் குரல் வழிகாட்டல் கேட்க',
    missedCallTitle: 'இலவச மிஸ்டு கால் சேவை',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'எந்த போனிலிருந்தும் மிஸ்டு கால் கொடுத்து உங்கள் மொழியில் விலை அறியலாம்',
    distance: 'தொலைவு',
    buyersToday: 'வணிகர்கள்',
    paymentInstant: 'பணம் பட்டுவாடா',
    sevenDayTrend: '7 நாள் விலை நிலவரம் மற்றும் கணிப்பு',
    today: 'இன்று',
    keyFactors: 'இந்த முடிவு ஏன்?',
    weatherNotice: 'வானிலை எச்சரிக்கை',
    locationLabel: 'மாநிலம் / இருப்பிடம்',
    changeLocation: 'மாநிலத்தை மாற்றுக',
    detectLocation: 'GPS மூலம் கண்டறி',
    detectedNotice: 'உங்கள் இருப்பிடத்திற்கு ஏற்ப தமிழ் மொழி மற்றும் சந்தைகள் தேர்வு செய்யப்பட்டுள்ளன',
    searchPlaceholder: 'பயிர்களைத் தேடுங்கள் (நெல், மஞ்சள், பருத்தி, வாழை, தேங்காய்)...',
    allCrops: 'அனைத்துப் பயிர்கள்',
    categoryCereals: 'தானியங்கள் மற்றும் சிறுதானியங்கள்',
    categoryPulses: 'பருப்பு வகைகள்',
    categoryOilseeds: 'எண்ணெய் வித்துக்கள்',
    categorySpices: 'நறுமணப் பொருட்கள்',
    categoryVegetables: 'காய்கறிகள்',
    categoryCashCrops: 'பணப்பயிர்கள்',
    categoryFruits: 'பழங்கள் & தோட்டங்கள்',
  },
  kn: {
    appName: 'ಮಂಡಿ ಮಿತ್ರ',
    tagline: 'ರೈತರಿಗಾಗಿ ಸ್ಮಾರ್ಟ್ ಮಾರುಕಟ್ಟೆ ದರ ಮತ್ತು ನಿವ್ವಳ ಲಾಭ ವ್ಯವಸ್ಥೆ',
    audioMode: 'ಸಲಹೆ ಆಲಿಸಿ',
    audioPlaying: 'ಸಲಹೆ ಓದಲಾಗುತ್ತಿದೆ...',
    stopAudio: 'ಧ್ವನಿ ನಿಲ್ಲಿಸಿ',
    sunlightMode: 'ಬಿಸಿಲು ಮೋಡ್',
    selectCrop: 'ನಿಮ್ಮ ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ',
    selectCropSubtitle: 'ಇಂದಿನ ಮಾರುಕಟ್ಟೆ ದರ ಮತ್ತು ಸರಿಯಾದ ನಿರ್ಧಾರ ತಿಳಿಯಲು ಬೆಳೆ ಮೇಲೆ ಸ್ಪರ್ಶಿಸಿ',
    voiceSearchPrompt: 'ಮೈಕ್ ಒತ್ತಿ ಬೆಳೆಯ ಹೆಸರು ಹೇಳಿ (ಉದಾ: "ರಾಗಿ", "ತೊಗರಿ", "ಟೊಮೆಟೊ")',
    voiceSearchActive: 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ... ಬೆಳೆಯ ಹೆಸರು ಹೇಳಿ',
    decisionSignal: 'ನಿರ್ಧಾರ ಸಂಕೇತ (Decision Signal)',
    highestPriceToday: 'ಇಂದಿನ ಗರಿಷ್ಠ ಮಾರುಕಟ್ಟೆ ದರ',
    perQuintal: 'ಪ್ರತಿ ಕ್ವಿಂಟಾಲ್‌ಗೆ (100 ಕೆಜಿ)',
    sellTodayVerdict: 'ಇಂದೇ ಮಾರಾಟ ಮಾಡಿ - ಮಾರುಕಟ್ಟೆ ದರ ಗರಿಷ್ಠ ಮಟ್ಟದಲ್ಲಿದೆ',
    waitVerdict: '೨–೩ ದಿನ ಕಾಯಿರಿ - ದರ ಹೆಚ್ಚಾಗುವ ನಿರೀಕ್ಷೆ ಇದೆ',
    riskVerdict: 'ತಕ್ಷಣ ಮಾರಿ - ಹವಾಮಾನ ಅಥವಾ ಕೊಳೆಯುವ ಅಪಾಯ',
    netProfitTitle: 'ಕೈಗೆ ಸಿಗುವ ನೈಜ ನಿವ್ವಳ ಲಾಭ (Net Profit)',
    netProfitSubtitle: 'ಕೇವಲ ಮಾರುಕಟ್ಟೆ ದರ ನೋಡಬೇಡಿ! ಸಾರಿಗೆ ವೆಚ್ಚ ಕಳೆದು ಕೈಗೆ ಎಷ್ಟು ಹಣ ಉಳಿಯುತ್ತದೆ ಎಂದು ಹೋಲಿಸಿ.',
    yourHarvestQuantity: 'ಬೆಳೆಯ ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್)',
    chooseVehicle: 'ಸಾರಿಗೆ ವಾಹನ ಆಯ್ಕೆಮಾಡಿ',
    dieselTransportCost: 'ಅಂದಾಜು ಸಾರಿಗೆ ವೆಚ್ಚ',
    grossSale: 'ಒಟ್ಟು ಮಾರುಕಟ್ಟೆ ಮಾರಾಟ',
    actualNetCash: 'ಕೈಗೆ ಸಿಗುವ ನಿವ್ವಳ ಹಣ',
    bestProfitBadge: 'ಅತ್ಯುತ್ತಮ ಲಾಭದ ಮಾರುಕಟ್ಟೆ',
    extraCash: 'ಹೆಚ್ಚುವರಿ ನಗದು ಉಳಿತಾಯ',
    offlineBannerTitle: 'ಕಡಿಮೆ ಇಂಟರ್ನೆಟ್ ಅಥವಾ ಕೀಪ್ಯಾಡ್ ಫೋನ್?',
    sendSmsBtn: 'SMS ಮೂಲಕ ಮೊಬೈಲ್‌ಗೆ ದರ ಪಡೆಯಿರಿ',
    playAudioBtn: 'ಕನ್ನಡದಲ್ಲಿ ಆಡಿಯೋ ಸಲಹೆ ಕೇಳಿ',
    missedCallTitle: 'ಉಚಿತ ಮಿಸ್ಡ್ ಕಾಲ್ ಸೇವೆ',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ಯಾವುದೇ ಫೋನ್‌ನಿಂದ ಮಿಸ್ಡ್ ಕಾಲ್ ನೀಡಿ ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ದರಗಳನ್ನು ಆಲಿಸಿ',
    distance: 'ದೂರ',
    buyersToday: 'ವ್ಯಾಪಾರಿಗಳು',
    paymentInstant: 'ಪಾವತಿ',
    sevenDayTrend: '೭ ದಿನಗಳ ದರ ಪ್ರವೃತ್ತಿ ಮತ್ತು ಮುನ್ಸೂಚನೆ',
    today: 'ಇಂದು',
    keyFactors: 'ಈ ನಿರ್ಧಾರ ಏಕೆ?',
    weatherNotice: 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ',
    locationLabel: 'ರಾಜ್ಯ / ಸ್ಥಳ',
    changeLocation: 'ರಾಜ್ಯ ಬದಲಾಯಿಸಿ',
    detectLocation: 'GPS ನಿಂದ ಪತ್ತೆಹಚ್ಚಿ',
    detectedNotice: 'ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ತಕ್ಕಂತೆ ಕನ್ನಡ ಭಾಷೆ ಮತ್ತು ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ',
    searchPlaceholder: 'ಯಾವುದೇ ಬೆಳೆಯನ್ನು ಹುಡುಕಿ (ರಾಗಿ, ಭತ್ತ, ತೊಗರಿ, ಹತ್ತಿ, ಕಾಫಿ)...',
    allCrops: 'ಎಲ್ಲಾ ಬೆಳೆಗಳು',
    categoryCereals: 'ಧಾನ್ಯಗಳು ಮತ್ತು ಸಿರಿಧಾನ್ಯಗಳು',
    categoryPulses: 'ಕಾಳುಗಳು (ಬೇಳೆಕಾಳು)',
    categoryOilseeds: 'ಎಣ್ಣೆಕಾಳುಗಳು',
    categorySpices: 'ಮಸಾಲೆ ಬೆಳೆಗಳು',
    categoryVegetables: 'ತರಕಾರಿಗಳು',
    categoryCashCrops: 'ವಾಣಿಜ್ಯ ಬೆಳೆಗಳು',
    categoryFruits: 'ಹಣ್ಣುಗಳು ಮತ್ತು ತೋಟಗಾರಿಕೆ',
  },
  ml: {
    appName: 'മണ്ടി മിത്ര',
    tagline: 'കർഷകർക്കായി മികച്ച വിപണി വിലയും അറ്റാദായ വഴികാട്ടിയും',
    audioMode: 'ഉപദേശം കേൾക്കുക',
    audioPlaying: 'ഉപദേശം വായിക്കുന്നു...',
    stopAudio: 'ശബ്ദം നിർത്തുക',
    sunlightMode: 'വെയിൽ മോഡ്',
    selectCrop: 'വിള തിരഞ്ഞെടുക്കുക',
    selectCropSubtitle: 'ഇന്നത്തെ മാർക്കറ്റ് നിരക്കും കൃത്യമായ തീരുമാനവും കാണാൻ ക്ലിക്ക് ചെയ്യുക',
    voiceSearchPrompt: 'മൈക്ക് അമർത്തി വിളയുടെ പേര് പറയുക (ഉദാ: "കുരുമുളക്", "തേങ്ങ", "റബ്ബർ")',
    voiceSearchActive: 'ശ്രദ്ധിക്കുന്നു... വിളയുടെ പേര് പറയുക',
    decisionSignal: 'തീരുമാന സൂചിക (Decision Signal)',
    highestPriceToday: 'ഇന്നത്തെ ഏറ്റവും ഉയർന്ന വിപണി വില',
    perQuintal: 'ക്വിന്റലിന് (100 കിലോ)',
    sellTodayVerdict: 'ഇന്ന് തന്നെ വിൽക്കുക - നിരക്കുകൾ ഏറ്റവും ഉയർന്ന നിലയിൽ',
    waitVerdict: '2–3 ദിവസം കാത്തിരിക്കുക - വില ഉയരാൻ സാധ്യതയുണ്ട്',
    riskVerdict: 'ഉടൻ വിൽക്കുക - കാലാവസ്ഥ അല്ലെങ്കിൽ കേടുപാടുകൾ സാധ്യത',
    netProfitTitle: 'കൈയിൽ ലഭിക്കുന്ന അറ്റാദായം (Net Profit)',
    netProfitSubtitle: 'മാർക്കറ്റ് നിരക്ക് മാത്രം നോക്കരുത്! ഇന്ധന/വാഹന ചെലവ് കുറച്ചുള്ള യഥാർത്ഥ ലാഭം താരതമ്യം ചെയ്യുക.',
    yourHarvestQuantity: 'വിളവിന്റെ അളവ് (ക്വിന്റൽ)',
    chooseVehicle: 'വാഹനം തിരഞ്ഞെടുക്കുക',
    dieselTransportCost: 'ഗതാഗത ചെലവ്',
    grossSale: 'മൊത്തം മാർക്കറ്റ് വിൽപ്പന',
    actualNetCash: 'കൈയിൽ ലഭിക്കുന്ന അറ്റ പണം',
    bestProfitBadge: 'കൂടുതൽ ലാഭം നൽകുന്ന മാർക്കറ്റ്',
    extraCash: 'കൂടുതൽ ലാഭത്തുക',
    offlineBannerTitle: 'ഇന്റർനെറ്റ് കുറവോ സാധാരണ ബട്ടൺ ഫോണോ ആണോ?',
    sendSmsBtn: 'SMS വഴി വില മൊബൈലിൽ നേടൂ',
    playAudioBtn: 'മലയാളത്തിൽ ഉപദേശം കേൾക്കൂ',
    missedCallTitle: 'സൗജന്യ മിസ്ഡ് കോൾ സർവീസ്',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ഏത് ഫോണിൽ നിന്നും മിസ്ഡ് കോൾ ചെയ്ത് സ്വന്തം ഭാഷയിൽ മാർക്കറ്റ് വില അറിയാം',
    distance: 'ദൂരം',
    buyersToday: 'വ്യാപാരികൾ',
    paymentInstant: 'പണമിടപാട്',
    sevenDayTrend: '7 ദിവസത്തെ വില നിലവാരവും പ്രവചനവും',
    today: 'ഇന്ന്',
    keyFactors: 'എന്തുകൊണ്ട് ഈ തീരുമാനം?',
    weatherNotice: 'കാലാവസ്ഥ മുന്നറിയിപ്പ്',
    locationLabel: 'സംസ്ഥാനം / സ്ഥലം',
    changeLocation: 'മാറ്റുക',
    detectLocation: 'GPS വഴി കണ്ടെത്തുക',
    detectedNotice: 'താങ്കളുടെ പ്രദേശത്തിനനുസരിച്ച് മലയാളം ഭാഷയും പ്രാദേശിക മാർക്കറ്റുകളും ക്രമീകരിച്ചു',
    searchPlaceholder: 'വിളകൾ തിരയുക (കുരുമുളക്, തേങ്ങ, റബ്ബർ, ഇഞ്ചി, ചായ)...',
    allCrops: 'എല്ലാ വിളകളും',
    categoryCereals: 'ധാന്യങ്ങളും ചെറുധാന്യങ്ങളും',
    categoryPulses: 'പയറുവർഗ്ഗങ്ങൾ',
    categoryOilseeds: 'എണ്ണക്കുരുക്കൾ',
    categorySpices: 'സുഗന്ധവ്യഞ്ജനങ്ങൾ',
    categoryVegetables: 'പച്ചക്കറികൾ',
    categoryCashCrops: 'നാണ്യവിളകൾ',
    categoryFruits: 'പഴങ്ങളും തോട്ടവിളകളും',
  },
  or: {
    appName: 'ମଣ୍ଡି ମିତ୍ର',
    tagline: 'କୃଷକମାନଙ୍କ ପାଇଁ ସ୍ମାର୍ଟ ଫସଲ ଦର ଏବଂ ନିଟ୍ ଲାଭ ପରାମର୍ଶ',
    audioMode: 'ପରାମର୍ଶ ଶୁଣନ୍ତୁ',
    audioPlaying: 'ପରାମର୍ଶ ପଢ଼ାଯାଉଛି...',
    stopAudio: 'ବନ୍ଦ କରନ୍ତୁ',
    sunlightMode: 'ଖରା ମୋଡ୍',
    selectCrop: 'ନିଜର ଫସଲ ବାଛନ୍ତୁ',
    selectCropSubtitle: 'ଆଜିର ମଣ୍ଡି ଦର ଏବଂ ଠିକ୍ ନିଷ୍ପତ୍ତି ପାଇଁ ଫସଲ ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ',
    voiceSearchPrompt: 'ମାଇକ୍ ଦବାଇ ଫସଲର ନାମ କୁହନ୍ତୁ (ଯେପରି "ଧାନ", "ହଳଦୀ", "ଚିନାବାଦାମ")',
    voiceSearchActive: 'ଶୁଣୁଛୁ... ଫସଲର ନାମ କୁହନ୍ତୁ',
    decisionSignal: 'ନିଷ୍ପତ୍ତି ସଙ୍କେତ (Decision Signal)',
    highestPriceToday: 'ଆଜିର ସର୍ବୋଚ୍ଚ ମଣ୍ଡି ଦର',
    perQuintal: 'କ୍ୱିଣ୍ଟାଲ୍ ପିଛା (୧୦୦ କିଲୋ)',
    sellTodayVerdict: 'ଆଜି ହିଁ ବିକ୍ରି କରନ୍ତୁ - ଦର ସର୍ବୋଚ୍ଚ ସ୍ତରରେ ଅଛି',
    waitVerdict: '୨–୩ ଦିନ ଅପେକ୍ଷା କରନ୍ତୁ - ଦର ବଢ଼ିବାର ସମ୍ଭାବନା ଅଛି',
    riskVerdict: 'ତୁରନ୍ତ ବିକ୍ରି କରନ୍ତୁ - ପାଣିପାଗ ଖରାପ କିମ୍ବା ନଷ୍ଟ ହେବାର ଆଶଙ୍କା',
    netProfitTitle: 'ହାତକୁ ଆସୁଥିବା ଅସଲି ନିଟ୍ ଲାଭ (Net Profit)',
    netProfitSubtitle: 'କେବଳ ମଣ୍ଡି ଦର ଦେଖନ୍ତୁ ନାହିଁ! ଗାଡ଼ି ଭଡ଼ା ଓ ଡିଜେଲ ଖର୍ଚ୍ଚ କାଟି ହାତରେ କେତେ ରହିବ ତାହା ଯାଞ୍ଚ କରନ୍ତୁ।',
    yourHarvestQuantity: 'ଫସଲର ପରିମାଣ (କ୍ୱିଣ୍ଟାଲ୍)',
    chooseVehicle: 'ପରିବହନ ଗାଡ଼ି ବାଛନ୍ତୁ',
    dieselTransportCost: 'ଆନୁମାନିକ ପରିବହନ ଖର୍ଚ୍ଚ',
    grossSale: 'ମୋଟ ମଣ୍ଡି ବିକ୍ରୟ',
    actualNetCash: 'ହାତରେ ନଗଦ ଅସଲି ଟଙ୍କା',
    bestProfitBadge: 'ସର୍ବାଧିକ ଲାଭର ମଣ୍ଡି',
    extraCash: 'ଅତିରିକ୍ତ ଲାଭ',
    offlineBannerTitle: 'ଧୀମା ଇଣ୍ଟରନେଟ୍ କିମ୍ବା ସାଧା କିପ୍ୟାଡ୍ ଫୋନ୍?',
    sendSmsBtn: 'SMS ଦ୍ୱାରା ଫୋନକୁ ଦର ମଗାନ୍ତୁ',
    playAudioBtn: 'ଓଡ଼ିଆରେ ଅଡିଓ ପରାମର୍ଶ ଶୁଣନ୍ତୁ',
    missedCallTitle: 'ମାଗଣା ମିସଡ୍ କଲ୍ ସେବା',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'ଯେକୌଣସି ଫୋନରୁ ମିସଡ୍ କଲ୍ ଦିଅନ୍ତୁ ଏବଂ ନିଜ ଭାଷାରେ ଦର ଶୁଣନ୍ତୁ',
    distance: 'ଦୂରତା',
    buyersToday: 'ବ୍ୟବସାୟୀ',
    paymentInstant: 'ଟଙ୍କା ପୈଠ',
    sevenDayTrend: '୭-ଦିନର ଦର ଟ୍ରେଣ୍ଡ୍ ଓ ପୂର୍ବାନୁମାନ',
    today: 'ଆଜି',
    keyFactors: 'ଏହି ନିଷ୍ପତ୍ତି କାହିଁକି?',
    weatherNotice: 'ପାଣିପାଗ ସତର୍କତା',
    locationLabel: 'ରାଜ୍ୟ / ସ୍ଥାନ',
    changeLocation: 'ରାଜ୍ୟ ବଦଳାନ୍ତୁ',
    detectLocation: 'GPS ମାଧ୍ୟମରେ ଖୋଜନ୍ତୁ',
    detectedNotice: 'ଆପଣଙ୍କ ଅଞ୍ଚଳ ଅନୁସାରେ ଓଡ଼ିଆ ଭାଷା ଏବଂ ସ୍ଥାନୀୟ ମଣ୍ଡି ଚୟନ କରାଯାଇଛି',
    searchPlaceholder: 'ଯେକୌଣସି ଫସଲ ଖୋଜନ୍ତୁ (ଧାନ, ହଳଦୀ, ଚିନାବାଦାମ, ମୁଗ)...',
    allCrops: 'ସମସ୍ତ ଫସଲ',
    categoryCereals: 'ଶସ୍ୟ ଓ ମିଲେଟ୍ସ',
    categoryPulses: 'ଡାଲି ଜାତୀୟ',
    categoryOilseeds: 'ତୈଳବୀଜ',
    categorySpices: 'ମସଲା',
    categoryVegetables: 'ପନିପରିବା',
    categoryCashCrops: 'ଅର୍ଥକରୀ ଫସଲ',
    categoryFruits: 'ଫଳ ଓ ବଗିଚା',
  },
  as: {
    appName: 'মন্ডি মিত্ৰ',
    tagline: 'কৃষকসকলৰ বাবে স্মাৰ্ট ফচলৰ বজাৰদৰ আৰু প্ৰকৃত লাভৰ পৰামৰ্শ',
    audioMode: 'পৰামৰ্শ শুনক',
    audioPlaying: 'পৰামৰ্শ পঢ়ি থকা হৈছে...',
    stopAudio: 'শব্দ বন্ধ কৰক',
    sunlightMode: 'ৰ’দ মোড',
    selectCrop: 'আপোনাৰ ফচল বাছক',
    selectCropSubtitle: 'আজিৰ বজাৰদৰ আৰু সঠিক সিদ্ধান্ত জানিবলৈ ফচলত ক্লিক কৰক',
    voiceSearchPrompt: 'মাইক টিপি ফচলৰ নাম কওক (যেনে "ধান", "চাহ", "মৰাপাট")',
    voiceSearchActive: 'শুনি আছোঁ... ফচলৰ নাম কওক',
    decisionSignal: 'সিদ্ধান্ত সংকেত (Decision Signal)',
    highestPriceToday: 'আজিৰ সৰ্বোচ্চ বজাৰদৰ',
    perQuintal: 'প্ৰতি কুইন্টলত (১০০ কেজি)',
    sellTodayVerdict: 'আজিয়েই বিক্ৰী কৰক - বজাৰদৰ শীৰ্ষত আছে',
    waitVerdict: '২–৩ দিন অপেক্ষা কৰক - দৰ বৃদ্ধি পোৱাৰ সম্ভাৱনা',
    riskVerdict: 'ততালিকে বিক্ৰী কৰক - বতৰ বা নষ্ট হোৱাৰ সম্ভাৱনা',
    netProfitTitle: 'হাতলৈ অহা প্ৰকৃত লাভ (Net Profit)',
    netProfitSubtitle: 'কেৱল বজাৰদৰ নাচাব! পৰিবহণ আৰু ইন্ধন খৰচ বাদ দি হাতত কিমান ৰব তুলনা কৰক।',
    yourHarvestQuantity: 'ফচলৰ পৰিমাণ (কুইন্টল)',
    chooseVehicle: 'পৰিবহণ বাহন বাছক',
    dieselTransportCost: 'আনুমানিক পৰিবহণ খৰচ',
    grossSale: 'মুঠ বজাৰ বিক্ৰী',
    actualNetCash: 'হাতত নগদ ধন',
    bestProfitBadge: 'সৰ্বাধিক লাভৰ বজাৰ',
    extraCash: 'অতিৰিক্ত লাভ',
    offlineBannerTitle: 'লেহেমীয়া ইণ্টাৰনেট বা সাধাৰণ বটন ফোন?',
    sendSmsBtn: 'SMS যোগে মোবাইললৈ দৰ আনক',
    playAudioBtn: 'অসমীয়াত অডিঅ’ পৰামৰ্শ শুনক',
    missedCallTitle: 'বিনামূলীয়া মিছড কল সেৱা',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'যিকোনো ফোনৰ পৰা মিছড কল দি নিজৰ ভাষাত বজাৰদৰ শুনক',
    distance: 'দূৰত্ব',
    buyersToday: 'ব্যৱসায়ীসকল',
    paymentInstant: 'পেমেন্ট',
    sevenDayTrend: '৭-দিনীয়া দৰৰ গতি আৰু পূৰ্বানুমান',
    today: 'আজি',
    keyFactors: 'এই সিদ্ধান্ত কিয়?',
    weatherNotice: 'বতৰৰ সতৰ্কবাৰ্তা',
    locationLabel: 'ৰাজ্য / স্থান',
    changeLocation: 'ৰাজ্য সলনি কৰক',
    detectLocation: 'GPS ৰে সন্ধান কৰক',
    detectedNotice: 'আপোনাৰ স্থান অনুসৰি অসমীয়া ভাষা আৰু স্থানীয় বজাৰ নিৰ্বাচিত হৈছে',
    searchPlaceholder: 'যিকোনো ফচল বিচাৰক (ধান, চাহ পাত, মৰাপাট, সৰিয়হ, আদা)...',
    allCrops: 'সকলো ফচল',
    categoryCereals: 'শস্য আৰু মিলেট',
    categoryPulses: 'দাইল জাতীয়',
    categoryOilseeds: 'তেলবীজ',
    categorySpices: 'মছলা',
    categoryVegetables: 'শাক-পাচলি',
    categoryCashCrops: 'নগদ ফচল',
    categoryFruits: 'ফল-মূল আৰু বাগিচা',
  },
  ur: {
    appName: 'منڈی متر',
    tagline: 'کسانوں کے لیے اسمارٹ فصل ریٹ اور خالص منافع کا نظام',
    audioMode: 'مشورہ سنیں',
    audioPlaying: 'مشورہ پڑھا جا رہا ہے...',
    stopAudio: 'آواز بند کریں',
    sunlightMode: 'دھوپ موڈ',
    selectCrop: 'اپنی فصل منتخب کریں',
    selectCropSubtitle: 'آج کے منڈی ریٹ اور درست فیصلے کے لیے فصل پر کلک کریں',
    voiceSearchPrompt: 'مائک دبا کر فصل کا نام بولیں (جیسے "سیب", "گیہوں", "کپاس")',
    voiceSearchActive: 'سن رہے ہیں... فصل کا نام بولیں',
    decisionSignal: 'فیصلہ کا اشارہ (Decision Signal)',
    highestPriceToday: 'آج کا سب سے اونچا منڈی ریٹ',
    perQuintal: 'فی کوئنٹل (100 کلو)',
    sellTodayVerdict: 'آج ہی فروخت کریں - منڈی ریٹ عروج پر ہیں',
    waitVerdict: '2–3 دن رکیں - ریٹ بڑھنے کا امکان ہے',
    riskVerdict: 'فوری فروخت کریں - خراب موسم یا خراب ہونے کا خطرہ',
    netProfitTitle: 'ہاتھ میں آنے والا اصل خالص منافع (Net Profit)',
    netProfitSubtitle: 'صرف منڈی کا ریٹ نہ دیکھیں! کرایہ اور ایندھن کا خرچ نکال کر اصل بچت دیکھیں۔',
    yourHarvestQuantity: 'فصل کی مقدار (کوئنٹل)',
    chooseVehicle: 'ٹرانسپورٹ گاڑی منتخب کریں',
    dieselTransportCost: 'گاڑی / ڈیزل کا تخمینہ خرچ',
    grossSale: 'کل منڈی فروخت',
    actualNetCash: 'ہاتھ میں خالص رقم',
    bestProfitBadge: 'سب سے زیادہ منافع کی منڈی',
    extraCash: 'اضافی نقد بچت',
    offlineBannerTitle: 'سست انٹرنیٹ یا سادہ کی پیڈ فون؟',
    sendSmsBtn: 'SMS سے ریٹ منگوائیں',
    playAudioBtn: 'اردو میں آڈیو مشورہ سنیں',
    missedCallTitle: 'مفت مسڈ کال سروس',
    missedCallNumber: '1800-889-2040',
    missedCallDesc: 'کسی بھی فون سے مسڈ کال دیں اور اپنی زبان میں تازہ ترین منڈی ریٹ سنیں',
    distance: 'فاصلہ',
    buyersToday: 'خریدار تاجر',
    paymentInstant: 'ادائیگی',
    sevenDayTrend: '7 دن کا ریٹ گراف اور پیشین گوئی',
    today: 'آج',
    keyFactors: 'یہ فیصلہ کیوں؟',
    weatherNotice: 'موسم کی وارننگ',
    locationLabel: 'ریاست / مقام',
    changeLocation: 'ریاست تبدیل کریں',
    detectLocation: 'GPS سے تلاش کریں',
    detectedNotice: 'آپ کے مقام کے مطابق اردو زبان اور منڈیاں منتخب کی گئی ہیں',
    searchPlaceholder: 'فصل تلاش کریں (سیب, گیہوں, دھان, کپاس, پیاز)...',
    allCrops: 'تمام فصلیں',
    categoryCereals: 'اناج اور باجرہ',
    categoryPulses: 'دالیں',
    categoryOilseeds: 'تیل کے بیج',
    categorySpices: 'مصالحہ جات',
    categoryVegetables: 'سبزیاں',
    categoryCashCrops: 'نقد آور فصلیں',
    categoryFruits: 'پھل اور باغات',
  },
};

export function speakText(text: string, lang: Language, onEnd?: () => void): SpeechSynthesisUtterance | null {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    return null;
  }

  window.speechSynthesis.cancel(); // Stop ongoing speech

  const utterance = new SpeechSynthesisUtterance(text);
  utterance.rate = 0.9;
  utterance.pitch = 1.0;

  const langCodes: Record<Language, string> = {
    en: 'en-IN',
    hi: 'hi-IN',
    mr: 'mr-IN',
    gu: 'gu-IN',
    pa: 'pa-IN',
    bn: 'bn-IN',
    te: 'te-IN',
    ta: 'ta-IN',
    kn: 'kn-IN',
    ml: 'ml-IN',
    or: 'or-IN',
    as: 'as-IN',
    ur: 'ur-IN',
  };

  utterance.lang = langCodes[lang] || 'hi-IN';

  const voices = window.speechSynthesis.getVoices();
  const indianVoice = voices.find(
    (v) =>
      v.lang === utterance.lang ||
      v.lang.toLowerCase().includes('in') ||
      v.lang.startsWith(utterance.lang.split('-')[0])
  );
  if (indianVoice) {
    utterance.voice = indianVoice;
  }

  if (onEnd) {
    utterance.onend = onEnd;
    utterance.onerror = onEnd;
  }

  window.speechSynthesis.speak(utterance);
  return utterance;
}

export function stopSpeaking() {
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
    window.speechSynthesis.cancel();
  }
}
